#!/usr/bin/env python3
"""Deterministic, offline projections of the current Mimic extension schema."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys

from model import ROOT, load, pascal, snake

CONTRACT = load()
DEFS = CONTRACT.definitions
HASH = CONTRACT.sha256


def nullable(schema):
    choices = schema.get("oneOf", [])
    concrete = [x for x in choices if x.get("type") != "null"]
    return concrete[0] if len(choices) == 2 and len(concrete) == 1 else None


def model_schema(schema):
    return schema.get("type") == "object" and "properties" in schema


def type_name(schema, lang):
    if "$ref" in schema:
        name = schema["$ref"].split("/")[-1]
        target = DEFS[name]
        if lang in ("cs", "java", "php") and not model_schema(target):
            return type_name(target, lang)
        return 'EmptyValue' if lang == 'php' and name == 'Empty' else name
    null_type = nullable(schema)
    if null_type is not None:
        value = type_name(null_type, lang)
        return {"ts": f"{value} | null", "py": f"Union[{value}, None]", "cs": f"{value}?", "java": value, "go": f"*{value}", "rust": f"Option<{value}>", "ruby": "Object", "php": f"{value}|null"}[lang]
    if "oneOf" in schema and schema.get("type") != "object":
        if lang == "ts": return " | ".join(type_name(x, lang) for x in schema["oneOf"])
        if lang == "py": return "Union[" + ", ".join(type_name(x, lang) for x in schema["oneOf"]) + "]"
        return {"cs":"JsonNode", "java":"JsonElement", "go":"json.RawMessage", "rust":"serde_json::Value", "ruby":"Object", "php":"mixed"}[lang]
    if "enum" in schema and lang in ("ts", "py"):
        values = ", ".join(repr(x) for x in schema["enum"])
        return " | ".join(json.dumps(x) for x in schema["enum"]) if lang == "ts" else f"Literal[{values}]"
    kind = schema.get("type")
    if kind == "array":
        value = type_name(schema["items"], lang)
        return {"ts":f"Array<{value}>","py":f"list[{value}]","cs":f"List<{value}>","java":f"List<{value}>","go":f"[]{value}","rust":f"Vec<{value}>","ruby":"Array","php":"array"}[lang]
    if kind == "object":
        if "properties" in schema:
            if lang == "ts":
                required = schema.get("required", [])
                return "{ " + "; ".join(json.dumps(k) + ("" if k in required else "?") + ": " + type_name(v,lang) for k,v in schema["properties"].items()) + " }"
            return {"py":"dict[str, JsonValue]","cs":"JsonObject","java":"JsonObject","go":"map[string]json.RawMessage","rust":"serde_json::Value","ruby":"Hash","php":"array"}[lang]
        additional = schema.get("additionalProperties", {})
        value = type_name(additional if isinstance(additional,dict) else {},lang)
        return {"ts":f"Record<string, {value}>","py":f"dict[str, {value}]","cs":f"Dictionary<string, {value}>","java":f"Map<String, {value}>","go":f"map[string]{value}","rust":f"std::collections::BTreeMap<String, {value}>","ruby":"Hash","php":"array"}[lang]
    types = {
        "ts":{"string":"string","boolean":"boolean","integer":"number","number":"number","null":"null"},
        "py":{"string":"str","boolean":"bool","integer":"int","number":"float","null":"None"},
        "cs":{"string":"string","boolean":"bool","integer":"long","number":"double","null":"JsonNode"},
        "java":{"string":"String","boolean":"Boolean","integer":"Long","number":"Double","null":"JsonElement"},
        "go":{"string":"string","boolean":"bool","integer":"int64","number":"float64","null":"json.RawMessage"},
        "rust":{"string":"String","boolean":"bool","integer":"i64","number":"f64","null":"serde_json::Value"},
        "ruby":{"string":"String","boolean":"Object","integer":"Integer","number":"Numeric","null":"NilClass"},
        "php":{"string":"string","boolean":"bool","integer":"int","number":"float","null":"null"},
    }
    return types[lang].get(kind,{"ts":"JsonValue","py":"JsonValue","cs":"JsonNode","java":"JsonElement","go":"json.RawMessage","rust":"serde_json::Value","ruby":"Object","php":"mixed"}[lang])


def properties(schema):
    required = schema.get("required", [])
    return sorted(schema.get("properties", {}).items(), key=lambda row: (row[0] not in required,row[0]))


def header(prefix="//"):
    return f"{prefix} Generated by generator/generate.py; DO NOT EDIT.\n{prefix} Schema SHA-256: {HASH}\n"


def typescript():
    lines=[header(), 'export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };',f'export const schemaSha256 = "{HASH}";']
    for name,schema in DEFS.items():
        if model_schema(schema):
            lines.append(f"export interface {name} {{")
            for field, child in properties(schema):
                optional = "" if field in schema.get("required",[]) else "?"
                lines.append(f"  {json.dumps(field)}{optional}: {type_name(child,'ts')};")
            lines.append("}")
        else:
            lines.append(f"export type {name} = {type_name(schema,'ts')};")
    lines.append("export interface CommandMap {")
    for c in CONTRACT.commands:
        name = pascal(c["name"].split(".")[1])
        lines.append(f'  "{c["name"]}": {{ params: {name}Params; result: {name}Result }};')
    lines += ["}", "export class MimicClient {", "  constructor(private readonly sender: (method: string, params?: unknown) => Promise<any>) {}"]
    for c in CONTRACT.commands:
        leaf=c['name'].split('.')[1]; name=pascal(leaf)
        optional = not DEFS[name+'Params'].get('required') and 'oneOf' not in DEFS[name+'Params']
        lines += [f"  {leaf}(params: {name}Params{' = {}' if optional else ''}): Promise<{name}Result> {{", f'    return this.sender("{c["name"]}", params);', "  }"]
    lines.append("}")
    return '\n'.join(lines)+'\n'


PY_HELPERS = '''
class Unset:
    """An absent field, distinct from explicit JSON null."""
    __slots__ = ()

UNSET = Unset()
JsonValue: TypeAlias = Union[None, bool, int, float, str, list["JsonValue"], dict[str, "JsonValue"]]

def to_wire(value: Any) -> Any:
    if isinstance(value, Unset):
        raise TypeError("UNSET is only valid as an omitted object field")
    if is_dataclass(value):
        return {field.metadata["wire"]: to_wire(getattr(value, field.name)) for field in fields(value) if not isinstance(getattr(value, field.name), Unset)}
    if isinstance(value, dict):
        return {key: to_wire(child) for key, child in value.items() if not isinstance(child, Unset)}
    if isinstance(value, (list, tuple)):
        return [to_wire(child) for child in value]
    return value

def from_wire(model: Any, value: Any) -> Any:
    if value is None:
        return None
    origin, args = get_origin(model), get_args(model)
    if origin in (Union, types.UnionType):
        for choice in args:
            if choice in (Unset, type(None)):
                continue
            try:
                return from_wire(choice, value)
            except (TypeError, ValueError, KeyError):
                pass
        raise TypeError("No wire union branch matched")
    if origin is Literal:
        if value not in args:
            raise ValueError("Unknown enum value")
        return value
    if origin is list:
        if not isinstance(value, list): raise TypeError("Expected array")
        return [from_wire(args[0], child) for child in value]
    if origin is dict:
        if not isinstance(value, dict): raise TypeError("Expected object")
        return {key: from_wire(args[1], child) for key, child in value.items()}
    if isinstance(model, type) and is_dataclass(model):
        if not isinstance(value, dict): raise TypeError("Expected object")
        hints = get_type_hints(model)
        options = {}
        for field in fields(model):
            key = field.metadata["wire"]
            if key in value: options[field.name] = from_wire(hints[field.name], value[key])
        return model(**options)
    if model in (str, bool, int, float):
        if model is float and isinstance(value, (int, float)) and not isinstance(value, bool): return value
        if not isinstance(value, model) or model is int and isinstance(value, bool): raise TypeError("Invalid primitive")
    return value
'''


def python():
    lines=[header('#'),'from __future__ import annotations','from dataclasses import dataclass, field, fields, is_dataclass','from typing import Any, TypeAlias, Union, Literal, get_args, get_origin, get_type_hints','import types', f'SCHEMA_SHA256 = "{HASH}"',PY_HELPERS]
    for name,schema in DEFS.items():
        if not model_schema(schema): continue
        lines+=['@dataclass(kw_only=True)',f'class {name}:']
        if not schema['properties']: lines.append('    pass')
        for wire,child in properties(schema):
            attr=snake(wire)
            if attr in ('class','from','global','import'): attr+='_'
            typ=type_name(child,'py')
            if wire not in schema.get('required',[]):
                lines.append(f'    {attr}: Union[{typ}, Unset] = field(default=UNSET, metadata={{"wire": "{wire}"}})')
            else:
                lines.append(f'    {attr}: {typ} = field(metadata={{"wire": "{wire}"}})')
    for name,schema in DEFS.items():
        if not model_schema(schema): lines.append(f'{name}: TypeAlias = {type_name(schema,"py")}')
    for asynchronous in (False,True):
        lines += [f'class {"Async" if asynchronous else ""}MimicCommands:', '    def __init__(self, sender):', '        self._sender = sender']
        for c in CONTRACT.commands:
            name=pascal(c['name'].split('.')[1]); params=DEFS[name+'Params']
            optional = not params.get('required') and 'oneOf' not in params
            signature=f'params: {name}Params | dict' + (' | None = None' if optional else '')
            lines += [f'    {"async " if asynchronous else ""}def {snake(c["name"].split(".")[1])}(self, {signature}) -> {name}Result:',f'        value = {"await " if asynchronous else ""}self._sender("{c["name"]}", to_wire(params) if params is not None else {{}})',f'        return from_wire({name}Result, value)']
    return '\n'.join(lines)+'\n'


CS_HELPERS = '''
public readonly record struct Optional<T>(bool IsSet, T? Value, bool IsNull = false) {
    public static Optional<T> Of(T? value) => new(true, value, value is null);
    public static Optional<T> Null() => new(true, default, true);
    public static implicit operator Optional<T>(T? value) => Of(value);
}
public sealed class OptionalConverterFactory : JsonConverterFactory {
    public override bool CanConvert(Type type) => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Optional<>);
    public override JsonConverter CreateConverter(Type type, JsonSerializerOptions options) => (JsonConverter)Activator.CreateInstance(typeof(OptionalConverter<>).MakeGenericType(type.GetGenericArguments()[0]))!;
    private sealed class OptionalConverter<T> : JsonConverter<Optional<T>> {
        public override bool HandleNull => true;
        public override Optional<T> Read(ref Utf8JsonReader reader, Type type, JsonSerializerOptions options) => reader.TokenType == JsonTokenType.Null ? Optional<T>.Null() : Optional<T>.Of(JsonSerializer.Deserialize<T>(ref reader, options));
        public override void Write(Utf8JsonWriter writer, Optional<T> value, JsonSerializerOptions options) {
            if (!value.IsSet) throw new JsonException("Unset values can only occur as omitted properties");
            if (value.IsNull) writer.WriteNullValue(); else JsonSerializer.Serialize(writer, value.Value, options);
        }
    }
}
public static class Wire {
    public static readonly JsonSerializerOptions Options = CreateOptions();
    private static JsonSerializerOptions CreateOptions() { var options = new JsonSerializerOptions(); options.Converters.Add(new OptionalConverterFactory()); return options; }
    public static JsonObject Encode<T>(T value) => JsonSerializer.SerializeToNode(value, Options)!.AsObject();
    public static T Decode<T>(JsonObject value) => value.Deserialize<T>(Options)!;
}
'''


def csharp():
    lines=[header(),'#nullable enable','using System;','using System.Collections.Generic;','using System.Text.Json;','using System.Text.Json.Nodes;','using System.Text.Json.Serialization;','using System.Threading;','using System.Threading.Tasks;','namespace Mimic.Sdk.Generated;',CS_HELPERS]
    for name,schema in DEFS.items():
        if not model_schema(schema): continue
        lines.append(f'public sealed class {name} {{')
        for wire,child in properties(schema):
            typ=type_name(child,'cs');optional=wire not in schema.get('required',[])
            lines.append(f'    [JsonPropertyName("{wire}")]')
            if optional: lines.append('    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]')
            lines.append(f'    public {"Optional<"+typ+">" if optional else typ} {pascal(wire)} {{ get; set; }}' + (' = default!;' if not optional else ''))
        lines.append('}')
    lines += ['public sealed class MimicCommands {','    private readonly global::Mimic.Sdk.IProtocolTransport transport;',f'    public const string SchemaSha256 = "{HASH}";','    public MimicCommands(global::Mimic.Sdk.IProtocolTransport transport) { this.transport = transport; }']
    for c in CONTRACT.commands:
        name=pascal(c['name'].split('.')[1]);p=DEFS[name+'Params']; optional=not p.get('required') and 'oneOf' not in p
        params=f'{name}Params'+('?' if optional else '')+' parameters'+(' = null' if optional else '')
        lines.append(f'    public async Task<{name}Result> {name}Async({params}, CancellationToken cancellationToken = default) => Wire.Decode<{name}Result>(await transport.SendAsync("{c["name"]}", Wire.Encode(parameters ?? new {name}Params()), cancellationToken).ConfigureAwait(false));')
    lines.append('}')
    return '\n'.join(lines)+'\n'


JAVA_HELPERS = '''
  public static final class OptionalValue<T> {
    public final T value;
    private OptionalValue(T value) { this.value = value; }
    public static <T> OptionalValue<T> of(T value) { return new OptionalValue<>(value); }
  }
  private static final Gson GSON = new GsonBuilder().serializeNulls().create();
  public static JsonElement toWire(Object value) {
    if (value == null) return JsonNull.INSTANCE;
    if (value instanceof OptionalValue<?>) return toWire(((OptionalValue<?>)value).value);
    if (value instanceof JsonElement) return ((JsonElement)value).deepCopy();
    if (value instanceof Map<?,?>) { JsonObject out = new JsonObject(); for (Map.Entry<?,?> e : ((Map<?,?>)value).entrySet()) out.add((String)e.getKey(), toWire(e.getValue())); return out; }
    if (value instanceof Iterable<?>) { JsonArray out = new JsonArray(); for (Object child : (Iterable<?>)value) out.add(toWire(child)); return out; }
    if (value.getClass().getEnclosingClass() != Generated.class) return GSON.toJsonTree(value);
    JsonObject out = new JsonObject();
    try { for (Field field : value.getClass().getFields()) { Object child = field.get(value); if (field.getType() == OptionalValue.class && child == null) continue; out.add(wireName(field), toWire(child)); } }
    catch (IllegalAccessException e) { throw new IllegalArgumentException(e); }
    return out;
  }
  @SuppressWarnings("unchecked")
  private static Object decode(Type type, JsonElement value) {
    if (type instanceof ParameterizedType) {
      ParameterizedType generic = (ParameterizedType)type; Type raw = generic.getRawType(); Type[] args = generic.getActualTypeArguments();
      if (raw == OptionalValue.class) return OptionalValue.of(decode(args[0], value));
      if (value.isJsonNull()) return null;
      if (raw == List.class) { List<Object> out = new ArrayList<>(); for (JsonElement child : value.getAsJsonArray()) out.add(decode(args[0], child)); return out; }
      if (raw == Map.class) { Map<String,Object> out = new LinkedHashMap<>(); for (Map.Entry<String,JsonElement> e : value.getAsJsonObject().entrySet()) out.put(e.getKey(), decode(args[1],e.getValue())); return out; }
    }
    if (value.isJsonNull()) return null;
    if (type instanceof Class<?> && ((Class<?>)type).getEnclosingClass() == Generated.class) {
      try { Object out = ((Class<?>)type).getDeclaredConstructor().newInstance(); for (Field field : ((Class<?>)type).getFields()) if (value.getAsJsonObject().has(wireName(field))) field.set(out,decode(field.getGenericType(),value.getAsJsonObject().get(wireName(field)))); return out; }
      catch (ReflectiveOperationException e) { throw new IllegalArgumentException(e); }
    }
    return GSON.fromJson(value,type);
  }
  public static <T> T fromWire(Class<T> type, JsonElement value) { return type.cast(decode(type,value)); }
  private static String wireName(Field field) { com.google.gson.annotations.SerializedName name = field.getAnnotation(com.google.gson.annotations.SerializedName.class); return name == null ? field.getName() : name.value(); }
'''


def java():
    lines=[header(),'package io.mimicbrowser.sdk;','import com.google.gson.*;','import java.util.*;','import java.lang.reflect.*;','public final class Generated {',f'  public static final String SCHEMA_SHA256 = "{HASH}";',JAVA_HELPERS]
    for name,schema in DEFS.items():
        if not model_schema(schema): continue
        lines.append(f'  public static final class {name} {{')
        for wire,child in properties(schema):
            typ=type_name(child,'java');optional=wire not in schema.get('required',[])
            attr = wire+'_' if wire in ('class','default','new','native','public','private','static','void','enum') else wire
            if attr != wire: lines.append(f'    @com.google.gson.annotations.SerializedName("{wire}")')
            lines.append(f'    public {"OptionalValue<"+typ+">" if optional else typ} {attr};')
        lines.append('  }')
    lines += ['  public static final class MimicCommands {','    private final ProtocolTransport transport;','    public MimicCommands(ProtocolTransport transport) { this.transport = transport; }']
    for c in CONTRACT.commands:
        leaf=c['name'].split('.')[1];name=pascal(leaf)
        lines.append(f'    public {name}Result {leaf}({name}Params parameters) {{ return fromWire({name}Result.class, transport.send("{c["name"]}", toWire(parameters).getAsJsonObject())); }}')
        p=DEFS[name+'Params']
        if not p.get('required') and 'oneOf' not in p:
            lines.append(f'    public {name}Result {leaf}() {{ return {leaf}(new {name}Params()); }}')
    lines+=['  }','}']
    return '\n'.join(lines)+'\n'


GO_HELPERS = '''
// Optional preserves omission and explicit null. Go 1.24's omitzero calls IsZero.
type Optional[T any] struct { Value T; Set bool; Null bool }
func Some[T any](value T) Optional[T] { return Optional[T]{Value:value, Set:true} }
func Null[T any]() Optional[T] { return Optional[T]{Set:true, Null:true} }
func (o Optional[T]) IsZero() bool { return !o.Set }
func (o Optional[T]) MarshalJSON() ([]byte, error) { if o.Null { return []byte("null"),nil }; if !o.Set { return nil,fmt.Errorf("unset field outside an object") }; return json.Marshal(o.Value) }
func (o *Optional[T]) UnmarshalJSON(data []byte) error { o.Set=true; o.Null=string(data)=="null"; if o.Null { var zero T; o.Value=zero; return nil }; return json.Unmarshal(data,&o.Value) }
type ProtocolSender interface { Call(context.Context, string, any, any) error }
type MimicCommands struct { Sender ProtocolSender }
'''


def golang():
    lines=[header(),'package mimic','import ("context"; "encoding/json"; "fmt")',f'const SchemaSHA256 = "{HASH}"',GO_HELPERS]
    for name,schema in DEFS.items():
        if model_schema(schema):
            lines.append(f'type {name} struct {{')
            for wire,child in properties(schema):
                typ=type_name(child,'go');optional=wire not in schema.get('required',[])
                lines.append(f'  {pascal(wire)} {"Optional["+typ+"]" if optional else typ} `json:"{wire}{",omitzero" if optional else ""}"`')
            lines.append('}')
        else: lines.append(f'type {name} = {type_name(schema,"go")}')
    for c in CONTRACT.commands:
        name=pascal(c['name'].split('.')[1])
        lines += [f'func (c *MimicCommands) {name}(ctx context.Context, params {name}Params) ({name}Result, error) {{',f' var result {name}Result',f' err := c.Sender.Call(ctx, "{c["name"]}", params, &result)',' return result, err','}']
    source = '\n'.join(lines)+'\n'
    return subprocess.run(['gofmt'], input=source, text=True, capture_output=True, check=True).stdout.replace('\r\n', '\n')


RUST_HELPERS = '''
/// Missing and explicit JSON null are different wire values.
#[derive(Clone, Debug, PartialEq, Default)]
pub enum WireOptional<T> { #[default] Missing, Null, Value(T) }
impl<T> WireOptional<T> { pub fn is_missing(&self) -> bool { matches!(self, Self::Missing) } }
impl<T: Serialize> Serialize for WireOptional<T> {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self { Self::Value(value) => value.serialize(serializer), Self::Null => serializer.serialize_none(), Self::Missing => Err(serde::ser::Error::custom("missing field outside an object")) }
    }
}
impl<'de, T: Deserialize<'de>> Deserialize<'de> for WireOptional<T> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(match Option::<T>::deserialize(deserializer)? { Some(value) => Self::Value(value), None => Self::Null })
    }
}
'''


def rust():
    lines=[header(),'use serde::{Serialize, Deserialize, Serializer, Deserializer};',f'pub const SCHEMA_SHA256: &str = "{HASH}";',RUST_HELPERS]
    for name,schema in DEFS.items():
        if model_schema(schema):
            lines+=['#[derive(Clone, Debug, Default, Serialize, Deserialize)]',f'pub struct {name} {{']
            for wire,child in properties(schema):
                typ=type_name(child,'rust');optional=wire not in schema.get('required',[])
                attr=snake(wire)
                if attr in ('type','match','ref','self','super','crate','mod','use','loop','move','async','await'): attr='r#'+attr
                lines.append(f'    #[serde(rename = "{wire}"'+(', default, skip_serializing_if = "WireOptional::is_missing"' if optional else '')+')]')
                lines.append(f'    pub {attr}: {"WireOptional<"+typ+">" if optional else typ},')
            lines.append('}')
        else: lines.append(f'pub type {name} = {type_name(schema,"rust")};')
    lines.append('pub const METHODS: &[&str] = &['+', '.join(json.dumps(c['name']) for c in CONTRACT.commands)+'];')
    lines.append('impl crate::transport::Client {')
    for command in CONTRACT.commands:
        leaf=command['name'].split('.')[1];name=pascal(leaf)
        lines += [f'    pub async fn {snake(leaf)}(&self, params: {name}Params) -> crate::transport::Result<{name}Result> {{',f'        Ok(serde_json::from_value(self.call("{command["name"]}", Some(serde_json::to_value(params)?)).await?)?)','    }']
    lines.append('}')
    return '\n'.join(lines)+'\n'


RUBY_HELPERS = '''
    UNSET = Object.new.freeze
    def self.to_wire(value)
      case value
      when Model then value.to_wire
      when Hash then value.each_with_object({}) { |(key, child), result| result[key] = to_wire(child) unless child.equal?(UNSET) }
      when Array then value.map { |child| raise ArgumentError, 'UNSET in array' if child.equal?(UNSET); to_wire(child) }
      else value
      end
    end
    class Model
      def self.from_wire(value)
        raise ArgumentError, 'Expected object' unless value.is_a?(Hash)
        options = {}
        self::FIELDS.each do |name, wire|
          next unless value.key?(wire)
          options[name] = Generated.decode(self::TYPES[name], value[wire])
        end
        new(**options)
      end
      def initialize(**options)
        unknown = options.keys - self.class::FIELDS.keys
        raise ArgumentError, "Unknown fields: #{unknown}" unless unknown.empty?
        self.class::FIELDS.each { |name, _wire| instance_variable_set("@#{name}", options.fetch(name, UNSET)) }
      end
      def to_wire
        self.class::FIELDS.each_with_object({}) do |(name, wire), result|
          value = instance_variable_get("@#{name}")
          raise ArgumentError, "Missing required field: #{name}" if value.equal?(UNSET) && self.class::REQUIRED.include?(name)
          result[wire] = Generated.to_wire(value) unless value.equal?(UNSET)
        end
      end
    end
    def self.decode(type, value)
      return nil if value.nil?
      if type.is_a?(Array)
        return value.map { |child| decode(type[1], child) } if type[0] == :array
        return value.transform_values { |child| decode(type[1], child) } if type[0] == :map
      end
      return const_get(type).from_wire(value) if type.is_a?(String) && const_defined?(type) && const_get(type).is_a?(Class) && const_get(type) < Model
      value
    end
'''


def ruby_type(schema):
    if '$ref' in schema: return json.dumps(schema['$ref'].split('/')[-1])
    if nullable(schema) is not None: return ruby_type(nullable(schema))
    if schema.get('type') == 'array': return '[:array, '+ruby_type(schema['items'])+']'
    if schema.get('type') == 'object' and isinstance(schema.get('additionalProperties'),dict): return '[:map, '+ruby_type(schema['additionalProperties'])+']'
    return 'nil'


def ruby_field(name):
    result=snake(name)
    return result+'_' if result in ('class','send','method','object_id') else result


def ruby():
    lines=[header('#'),'module MimicSDK','  module Generated',f'    SCHEMA_SHA256 = "{HASH}"',RUBY_HELPERS]
    for name,schema in DEFS.items():
        if not model_schema(schema): continue
        pairs=', '.join(f'{ruby_field(wire)}: "{wire}"' for wire in schema['properties'])
        types=', '.join(f'{ruby_field(wire)}: '+ruby_type(child) for wire,child in schema['properties'].items())
        req=', '.join(':'+ruby_field(wire) for wire in schema.get('required',[]))
        lines += [f'    class {name} < Model',f'      FIELDS = {{{pairs}}}.freeze',f'      TYPES = {{{types}}}.freeze',f'      REQUIRED = [{req}].freeze','      attr_accessor(*FIELDS.keys)','    end']
    lines+=['    class MimicCommands','      def initialize(sender)', '        @sender = sender', '      end']
    for c in CONTRACT.commands:
        name=pascal(c['name'].split('.')[1]);p=DEFS[name+'Params'];optional=not p.get('required') and 'oneOf' not in p
        lines += [f'      def {snake(c["name"].split(".")[1])}(params'+(' = {}' if optional else '')+')',f'        {name}Result.from_wire(@sender.call("{c["name"]}", Generated.to_wire(params)))','      end']
    lines+=['    end','  end','end']
    return '\n'.join(lines)+'\n'


PHP_HELPERS = '''
enum Missing { case Value; }
abstract class Model implements \\JsonSerializable {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
    private static function decode(mixed $value, mixed $type): mixed {
        if ($value === null || $type === null) return $value;
        if (is_array($type)) {
            if ($type[0] === 'array') return array_map(fn($child) => self::decode($child, $type[1]), $value);
            $out = [];
            foreach ((array) $value as $key => $child) $out[$key] = self::decode($child, $type[1]);
            return $out;
        }
        return $type::fromWire($value);
    }
    public static function fromWire(object|array $wire): static {
        $model = new static();
        foreach ((array) $wire as $key => $value) {
            if (!property_exists($model, $key)) continue;
            $model->$key = self::decode($value, static::TYPES[$key] ?? null);
        }
        foreach (static::REQUIRED as $key) {
            if ($model->$key === Missing::Value) throw new \\InvalidArgumentException("Missing result field: " . $key);
        }
        return $model;
    }
    public function jsonSerialize(): object {
        $out = [];
        foreach (get_object_vars($this) as $key => $value) {
            if ($value === Missing::Value) {
                if (in_array($key, static::REQUIRED, true)) throw new \\InvalidArgumentException("Missing field: " . $key);
                continue;
            }
            $out[$key] = in_array($key, static::MAP_FIELDS, true) && is_array($value) ? (object) $value : $value;
        }
        return (object) $out;
    }
}
'''


def php():
    def descriptor(schema):
        if '$ref' in schema:
            name = schema['$ref'].split('/')[-1]
            return (('EmptyValue' if name == 'Empty' else name) + '::class') if model_schema(DEFS[name]) else descriptor(DEFS[name])
        if nullable(schema) is not None: return descriptor(nullable(schema))
        if schema.get('type') == 'array': return "['array', " + descriptor(schema['items']) + ']'
        if schema.get('type') == 'object' and 'properties' not in schema:
            child = schema.get('additionalProperties', {})
            return "['map', " + descriptor(child if isinstance(child, dict) else {}) + ']'
        return 'null'
    lines=['<?php',header(),'declare(strict_types=1);','namespace Mimic\\Sdk\\Generated;',f'const SCHEMA_SHA256 = "{HASH}";',PHP_HELPERS]
    for name,schema in DEFS.items():
        if not model_schema(schema): continue
        required=', '.join("'"+wire+"'" for wire in schema.get('required',[]))
        maps = ', '.join("'"+wire+"'" for wire,child in schema['properties'].items() if child.get('type')=='object' and 'properties' not in child)
        types = ', '.join("'"+wire+"' => "+descriptor(child) for wire,child in schema['properties'].items())
        lines += [f'final class {"EmptyValue" if name == "Empty" else name} extends Model {{',f'    protected const REQUIRED = [{required}];',f'    protected const MAP_FIELDS = [{maps}];',f'    protected const TYPES = [{types}];']
        for wire,child in properties(schema):
            typ=type_name(child,'php')
            if typ!='mixed': typ+='|Missing' + ('' if '|null' in typ or typ=='null' else '|null')
            lines.append(f'    public {typ} ${wire} = Missing::Value;')
        lines.append('}')
    lines+=['final class MimicCommands {','    public function __construct(private \\Closure $sender) {}']
    for c in CONTRACT.commands:
        leaf=c['name'].split('.')[1];name=pascal(leaf);p=DEFS[name+'Params'];optional=not p.get('required') and 'oneOf' not in p
        lines.append(f'    public function {leaf}({name}Params|array'+('|null $params = null' if optional else ' $params')+f'): {name}Result {{')
        lines.append(f'        return {name}Result::fromWire(($this->sender)("{c["name"]}", $params ?? new \\stdClass()));')
        lines.append('    }')
    lines.append('}')
    return '\n'.join(lines)+'\n'


OUTPUTS = {
    'node/src/generated.ts':typescript,
    'python/mimic/generated.py':python,
    'dotnet/Mimic.Sdk/Generated.cs':csharp,
    'java/src/main/java/io/mimicbrowser/sdk/Generated.java':java,
    'go/generated.go':golang,
    'rust/src/generated.rs':rust,
    'ruby/lib/mimic_sdk/generated.rb':ruby,
    'php/src/Generated.php':php,
}

# Package-local copies keep published Rust tests/default selection independent
# of the source checkout. These are generated from the same authored inputs.
COPIES = {
    'rust/tests/fixtures/wire.json': lambda: (ROOT/'conformance/fixtures/wire.json').read_text(encoding='utf-8'),
    'rust/src/runtime-lock.json': lambda: (ROOT/'release/runtime-lock.json').read_text(encoding='utf-8'),
}


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    failures=[]
    for name,backend in (OUTPUTS | COPIES).items():
        output=backend()
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_bytes()!=output.encode(): failures.append(name)
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(output,encoding='utf-8',newline='\n')
    if failures:
        print('Generated output differs: '+', '.join(failures),file=sys.stderr)
        return 1
    print(f'{"Checked" if args.check else "Generated"} {len(OUTPUTS)} targets; {len(CONTRACT.commands)} commands; schema {HASH}')
    return 0


if __name__=='__main__':
    raise SystemExit(main())
