// Generated by generator/generate.py; DO NOT EDIT.
// Schema SHA-256: ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6

use serde::{Serialize, Deserialize, Serializer, Deserializer};
pub const SCHEMA_SHA256: &str = "ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6";

/// Missing and explicit JSON null are different wire values.
#[derive(Clone, Debug, PartialEq, Default)]
pub enum WireOptional<T> { #[default] Missing, Null, Value(T) }
impl<T> WireOptional<T> { pub fn is_missing(&self) -> bool { matches!(self, Self::Missing) } }
impl<T: Serialize> Serialize for WireOptional<T> {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self { Self::Value(value) => value.serialize(serializer), Self::Null => serializer.serialize_none(), Self::Missing => Err(serde::ser::Error::custom("missing field outside an object")) }
    }
}
impl<'de, T: Deserialize<'de>> Deserialize<'de> for WireOptional<T> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(match Option::<T>::deserialize(deserializer)? { Some(value) => Self::Value(value), None => Self::Null })
    }
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CameraFormat {
    #[serde(rename = "frameRate")]
    pub frame_rate: f64,
    #[serde(rename = "height")]
    pub height: i64,
    #[serde(rename = "width")]
    pub width: i64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CancelExecutionParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CancelExecutionResult {
    #[serde(rename = "cancelled")]
    pub cancelled: bool,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaptureSnapshotParams {
    #[serde(rename = "interrupt", default, skip_serializing_if = "WireOptional::is_missing")]
    pub interrupt: WireOptional<bool>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CaptureSnapshotResult {
    #[serde(rename = "files")]
    pub files: std::collections::BTreeMap<String, String>,
    #[serde(rename = "timingsMs")]
    pub timings_ms: std::collections::BTreeMap<String, i64>,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "warnings")]
    pub warnings: Vec<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ClearTraceParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ClearTraceResult {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConfigureContextParams {
    #[serde(rename = "browserContextId")]
    pub browser_context_id: String,
    #[serde(rename = "media", default, skip_serializing_if = "WireOptional::is_missing")]
    pub media: WireOptional<MediaConfiguration>,
    #[serde(rename = "profile", default, skip_serializing_if = "WireOptional::is_missing")]
    pub profile: WireOptional<ProfileSelection>,
    #[serde(rename = "proxy", default, skip_serializing_if = "WireOptional::is_missing")]
    pub proxy: WireOptional<Proxy>,
    #[serde(rename = "resourcePolicy", default, skip_serializing_if = "WireOptional::is_missing")]
    pub resource_policy: WireOptional<ResourcePolicy>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ConfigureContextResult {
    #[serde(rename = "browserContextId")]
    pub browser_context_id: String,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "profile")]
    pub profile: String,
    #[serde(rename = "profileId")]
    pub profile_id: String,
    #[serde(rename = "warnings")]
    pub warnings: Vec<String>,
    #[serde(rename = "media", default, skip_serializing_if = "WireOptional::is_missing")]
    pub media: WireOptional<MediaProfile>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CreateContextParams {
    #[serde(rename = "disposeOnDetach", default, skip_serializing_if = "WireOptional::is_missing")]
    pub dispose_on_detach: WireOptional<bool>,
    #[serde(rename = "media", default, skip_serializing_if = "WireOptional::is_missing")]
    pub media: WireOptional<MediaConfiguration>,
    #[serde(rename = "profile", default, skip_serializing_if = "WireOptional::is_missing")]
    pub profile: WireOptional<ProfileSelection>,
    #[serde(rename = "proxy", default, skip_serializing_if = "WireOptional::is_missing")]
    pub proxy: WireOptional<Proxy>,
    #[serde(rename = "resourcePolicy", default, skip_serializing_if = "WireOptional::is_missing")]
    pub resource_policy: WireOptional<ResourcePolicy>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CreateContextResult {
    #[serde(rename = "browserContextId")]
    pub browser_context_id: String,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "profile")]
    pub profile: String,
    #[serde(rename = "profileId")]
    pub profile_id: String,
    #[serde(rename = "warnings")]
    pub warnings: Vec<String>,
    #[serde(rename = "media", default, skip_serializing_if = "WireOptional::is_missing")]
    pub media: WireOptional<MediaProfile>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct DiagnosticCost {
    #[serde(rename = "count")]
    pub count: i64,
    #[serde(rename = "ns")]
    pub ns: i64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Diagnostics {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "costs", default, skip_serializing_if = "WireOptional::is_missing")]
    pub costs: WireOptional<std::collections::BTreeMap<String, DiagnosticCost>>,
    #[serde(rename = "cpu_profiles", default, skip_serializing_if = "WireOptional::is_missing")]
    pub cpu_profiles: WireOptional<std::collections::BTreeMap<String, serde_json::Value>>,
    #[serde(rename = "hostOnly", default, skip_serializing_if = "WireOptional::is_missing")]
    pub host_only: WireOptional<bool>,
    #[serde(rename = "realms", default, skip_serializing_if = "WireOptional::is_missing")]
    pub realms: WireOptional<Vec<RealmDiagnostics>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Empty {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentAudio {
    #[serde(rename = "bufferDuration", default, skip_serializing_if = "WireOptional::is_missing")]
    pub buffer_duration: WireOptional<f64>,
    #[serde(rename = "channels", default, skip_serializing_if = "WireOptional::is_missing")]
    pub channels: WireOptional<i64>,
    #[serde(rename = "maxBufferFrames", default, skip_serializing_if = "WireOptional::is_missing")]
    pub max_buffer_frames: WireOptional<i64>,
    #[serde(rename = "sampleRate", default, skip_serializing_if = "WireOptional::is_missing")]
    pub sample_rate: WireOptional<f64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentCapabilities {
    #[serde(rename = "devices", default, skip_serializing_if = "WireOptional::is_missing")]
    pub devices: WireOptional<EnvironmentDeviceCapabilities>,
    #[serde(rename = "keyboardLayout", default, skip_serializing_if = "WireOptional::is_missing")]
    pub keyboard_layout: WireOptional<std::collections::BTreeMap<String, String>>,
    #[serde(rename = "media", default, skip_serializing_if = "WireOptional::is_missing")]
    pub media: WireOptional<EnvironmentMediaCapabilities>,
    #[serde(rename = "storageQuotaBytes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub storage_quota_bytes: WireOptional<i64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentDeviceCapabilities {
    #[serde(rename = "bluetoothAvailable", default, skip_serializing_if = "WireOptional::is_missing")]
    pub bluetooth_available: WireOptional<bool>,
    #[serde(rename = "posture", default, skip_serializing_if = "WireOptional::is_missing")]
    pub posture: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentDisplay {
    #[serde(rename = "availableHeight", default, skip_serializing_if = "WireOptional::is_missing")]
    pub available_height: WireOptional<i64>,
    #[serde(rename = "availableWidth", default, skip_serializing_if = "WireOptional::is_missing")]
    pub available_width: WireOptional<i64>,
    #[serde(rename = "colorDepth", default, skip_serializing_if = "WireOptional::is_missing")]
    pub color_depth: WireOptional<i64>,
    #[serde(rename = "deviceScaleFactor", default, skip_serializing_if = "WireOptional::is_missing")]
    pub device_scale_factor: WireOptional<f64>,
    #[serde(rename = "height", default, skip_serializing_if = "WireOptional::is_missing")]
    pub height: WireOptional<i64>,
    #[serde(rename = "orientation", default, skip_serializing_if = "WireOptional::is_missing")]
    pub orientation: WireOptional<EnvironmentScreenOrientation>,
    #[serde(rename = "width", default, skip_serializing_if = "WireOptional::is_missing")]
    pub width: WireOptional<i64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentFonts {
    #[serde(rename = "fallback", default, skip_serializing_if = "WireOptional::is_missing")]
    pub fallback: WireOptional<Vec<String>>,
    #[serde(rename = "monospace", default, skip_serializing_if = "WireOptional::is_missing")]
    pub monospace: WireOptional<String>,
    #[serde(rename = "sansSerif", default, skip_serializing_if = "WireOptional::is_missing")]
    pub sans_serif: WireOptional<String>,
    #[serde(rename = "serif", default, skip_serializing_if = "WireOptional::is_missing")]
    pub serif: WireOptional<String>,
    #[serde(rename = "system", default, skip_serializing_if = "WireOptional::is_missing")]
    pub system: WireOptional<std::collections::BTreeMap<String, String>>,
    #[serde(rename = "systemUI", default, skip_serializing_if = "WireOptional::is_missing")]
    pub system_u_i: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentGPUAdapter {
    #[serde(rename = "architecture", default, skip_serializing_if = "WireOptional::is_missing")]
    pub architecture: WireOptional<String>,
    #[serde(rename = "description", default, skip_serializing_if = "WireOptional::is_missing")]
    pub description: WireOptional<String>,
    #[serde(rename = "device", default, skip_serializing_if = "WireOptional::is_missing")]
    pub device: WireOptional<String>,
    #[serde(rename = "features", default, skip_serializing_if = "WireOptional::is_missing")]
    pub features: WireOptional<Vec<String>>,
    #[serde(rename = "initializationDelayMillis", default, skip_serializing_if = "WireOptional::is_missing")]
    pub initialization_delay_millis: WireOptional<f64>,
    #[serde(rename = "isFallbackAdapter", default, skip_serializing_if = "WireOptional::is_missing")]
    pub is_fallback_adapter: WireOptional<bool>,
    #[serde(rename = "limits", default, skip_serializing_if = "WireOptional::is_missing")]
    pub limits: WireOptional<std::collections::BTreeMap<String, i64>>,
    #[serde(rename = "subgroupMaxSize", default, skip_serializing_if = "WireOptional::is_missing")]
    pub subgroup_max_size: WireOptional<i64>,
    #[serde(rename = "subgroupMinSize", default, skip_serializing_if = "WireOptional::is_missing")]
    pub subgroup_min_size: WireOptional<i64>,
    #[serde(rename = "vendor", default, skip_serializing_if = "WireOptional::is_missing")]
    pub vendor: WireOptional<String>,
    #[serde(rename = "wgslLanguageFeatures", default, skip_serializing_if = "WireOptional::is_missing")]
    pub wgsl_language_features: WireOptional<Vec<String>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentGraphics {
    #[serde(rename = "maxTextureSize", default, skip_serializing_if = "WireOptional::is_missing")]
    pub max_texture_size: WireOptional<i64>,
    #[serde(rename = "renderer", default, skip_serializing_if = "WireOptional::is_missing")]
    pub renderer: WireOptional<String>,
    #[serde(rename = "vendor", default, skip_serializing_if = "WireOptional::is_missing")]
    pub vendor: WireOptional<String>,
    #[serde(rename = "webGLCapabilitiesJSON", default, skip_serializing_if = "WireOptional::is_missing")]
    pub web_g_l_capabilities_j_s_o_n: WireOptional<String>,
    #[serde(rename = "webGPU", default, skip_serializing_if = "WireOptional::is_missing")]
    pub web_g_p_u: WireOptional<EnvironmentGPUAdapter>,
    #[serde(rename = "webGPUAdapters", default, skip_serializing_if = "WireOptional::is_missing")]
    pub web_g_p_u_adapters: WireOptional<std::collections::BTreeMap<String, EnvironmentGPUAdapter>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentHardware {
    #[serde(rename = "cpuPerformance", default, skip_serializing_if = "WireOptional::is_missing")]
    pub cpu_performance: WireOptional<i64>,
    #[serde(rename = "cpuPerformanceKnown", default, skip_serializing_if = "WireOptional::is_missing")]
    pub cpu_performance_known: WireOptional<bool>,
    #[serde(rename = "deviceMemoryGB", default, skip_serializing_if = "WireOptional::is_missing")]
    pub device_memory_g_b: WireOptional<f64>,
    #[serde(rename = "logicalProcessors", default, skip_serializing_if = "WireOptional::is_missing")]
    pub logical_processors: WireOptional<i64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentICEProfile {
    #[serde(rename = "endDelayMillis", default, skip_serializing_if = "WireOptional::is_missing")]
    pub end_delay_millis: WireOptional<f64>,
    #[serde(rename = "hostCandidateCount", default, skip_serializing_if = "WireOptional::is_missing")]
    pub host_candidate_count: WireOptional<i64>,
    #[serde(rename = "hostDelayMillis", default, skip_serializing_if = "WireOptional::is_missing")]
    pub host_delay_millis: WireOptional<f64>,
    #[serde(rename = "networkCost", default, skip_serializing_if = "WireOptional::is_missing")]
    pub network_cost: WireOptional<i64>,
    #[serde(rename = "portOffsets", default, skip_serializing_if = "WireOptional::is_missing")]
    pub port_offsets: WireOptional<Vec<i64>>,
    #[serde(rename = "publicAddress", default, skip_serializing_if = "WireOptional::is_missing")]
    pub public_address: WireOptional<String>,
    #[serde(rename = "reflexiveCandidateCount", default, skip_serializing_if = "WireOptional::is_missing")]
    pub reflexive_candidate_count: WireOptional<i64>,
    #[serde(rename = "reflexiveDelayMillis", default, skip_serializing_if = "WireOptional::is_missing")]
    pub reflexive_delay_millis: WireOptional<f64>,
    #[serde(rename = "reflexivePortOffsets", default, skip_serializing_if = "WireOptional::is_missing")]
    pub reflexive_port_offsets: WireOptional<Vec<i64>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentIdentity {
    #[serde(rename = "metadata", default, skip_serializing_if = "WireOptional::is_missing")]
    pub metadata: WireOptional<EnvironmentUserAgentMetadata>,
    #[serde(rename = "platform", default, skip_serializing_if = "WireOptional::is_missing")]
    pub platform: WireOptional<String>,
    #[serde(rename = "userAgent", default, skip_serializing_if = "WireOptional::is_missing")]
    pub user_agent: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentLocale {
    #[serde(rename = "intlLocale", default, skip_serializing_if = "WireOptional::is_missing")]
    pub intl_locale: WireOptional<String>,
    #[serde(rename = "languages", default, skip_serializing_if = "WireOptional::is_missing")]
    pub languages: WireOptional<Vec<String>>,
    #[serde(rename = "reduceAcceptLanguage", default, skip_serializing_if = "WireOptional::is_missing")]
    pub reduce_accept_language: WireOptional<bool>,
    #[serde(rename = "timezone", default, skip_serializing_if = "WireOptional::is_missing")]
    pub timezone: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentMediaCapabilities {
    #[serde(rename = "formats", default, skip_serializing_if = "WireOptional::is_missing")]
    pub formats: WireOptional<EnvironmentMediaFormatCatalog>,
    #[serde(rename = "kinds", default, skip_serializing_if = "WireOptional::is_missing")]
    pub kinds: WireOptional<Vec<String>>,
    #[serde(rename = "rtp", default, skip_serializing_if = "WireOptional::is_missing")]
    pub rtp: WireOptional<std::collections::BTreeMap<String, EnvironmentRTPMediaCatalog>>,
    #[serde(rename = "supportedConstraints", default, skip_serializing_if = "WireOptional::is_missing")]
    pub supported_constraints: WireOptional<Vec<String>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentMediaContainerPolicy {
    #[serde(rename = "codecs", default, skip_serializing_if = "WireOptional::is_missing")]
    pub codecs: WireOptional<Vec<String>>,
    #[serde(rename = "defaultCodec", default, skip_serializing_if = "WireOptional::is_missing")]
    pub default_codec: WireOptional<String>,
    #[serde(rename = "mediaSource", default, skip_serializing_if = "WireOptional::is_missing")]
    pub media_source: WireOptional<bool>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentMediaFormatCatalog {
    #[serde(rename = "containers", default, skip_serializing_if = "WireOptional::is_missing")]
    pub containers: WireOptional<std::collections::BTreeMap<String, EnvironmentMediaContainerPolicy>>,
    #[serde(rename = "efficientVideo", default, skip_serializing_if = "WireOptional::is_missing")]
    pub efficient_video: WireOptional<Vec<String>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentNetwork {
    #[serde(rename = "cookiesEnabled", default, skip_serializing_if = "WireOptional::is_missing")]
    pub cookies_enabled: WireOptional<bool>,
    #[serde(rename = "downlinkMbps", default, skip_serializing_if = "WireOptional::is_missing")]
    pub downlink_mbps: WireOptional<f64>,
    #[serde(rename = "effectiveType", default, skip_serializing_if = "WireOptional::is_missing")]
    pub effective_type: WireOptional<String>,
    #[serde(rename = "ice", default, skip_serializing_if = "WireOptional::is_missing")]
    pub ice: WireOptional<EnvironmentICEProfile>,
    #[serde(rename = "online", default, skip_serializing_if = "WireOptional::is_missing")]
    pub online: WireOptional<bool>,
    #[serde(rename = "proxy", default, skip_serializing_if = "WireOptional::is_missing")]
    pub proxy: WireOptional<EnvironmentProxy>,
    #[serde(rename = "rttMillis", default, skip_serializing_if = "WireOptional::is_missing")]
    pub rtt_millis: WireOptional<f64>,
    #[serde(rename = "saveData", default, skip_serializing_if = "WireOptional::is_missing")]
    pub save_data: WireOptional<bool>,
    #[serde(rename = "wireProfile", default, skip_serializing_if = "WireOptional::is_missing")]
    pub wire_profile: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentPreferences {
    #[serde(rename = "colorScheme", default, skip_serializing_if = "WireOptional::is_missing")]
    pub color_scheme: WireOptional<String>,
    #[serde(rename = "doNotTrack", default, skip_serializing_if = "WireOptional::is_missing")]
    pub do_not_track: WireOptional<bool>,
    #[serde(rename = "reducedMotion", default, skip_serializing_if = "WireOptional::is_missing")]
    pub reduced_motion: WireOptional<bool>,
    #[serde(rename = "systemColors", default, skip_serializing_if = "WireOptional::is_missing")]
    pub system_colors: WireOptional<std::collections::BTreeMap<String, std::collections::BTreeMap<String, String>>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentProfile {
    #[serde(rename = "audio", default, skip_serializing_if = "WireOptional::is_missing")]
    pub audio: WireOptional<EnvironmentAudio>,
    #[serde(rename = "baseProfile", default, skip_serializing_if = "WireOptional::is_missing")]
    pub base_profile: WireOptional<String>,
    #[serde(rename = "capabilities", default, skip_serializing_if = "WireOptional::is_missing")]
    pub capabilities: WireOptional<EnvironmentCapabilities>,
    #[serde(rename = "display", default, skip_serializing_if = "WireOptional::is_missing")]
    pub display: WireOptional<EnvironmentDisplay>,
    #[serde(rename = "features", default, skip_serializing_if = "WireOptional::is_missing")]
    pub features: WireOptional<std::collections::BTreeMap<String, bool>>,
    #[serde(rename = "fonts", default, skip_serializing_if = "WireOptional::is_missing")]
    pub fonts: WireOptional<EnvironmentFonts>,
    #[serde(rename = "graphics", default, skip_serializing_if = "WireOptional::is_missing")]
    pub graphics: WireOptional<EnvironmentGraphics>,
    #[serde(rename = "hardware", default, skip_serializing_if = "WireOptional::is_missing")]
    pub hardware: WireOptional<EnvironmentHardware>,
    #[serde(rename = "identity", default, skip_serializing_if = "WireOptional::is_missing")]
    pub identity: WireOptional<EnvironmentIdentity>,
    #[serde(rename = "locale", default, skip_serializing_if = "WireOptional::is_missing")]
    pub locale: WireOptional<EnvironmentLocale>,
    #[serde(rename = "network", default, skip_serializing_if = "WireOptional::is_missing")]
    pub network: WireOptional<EnvironmentNetwork>,
    #[serde(rename = "permissions", default, skip_serializing_if = "WireOptional::is_missing")]
    pub permissions: WireOptional<std::collections::BTreeMap<String, String>>,
    #[serde(rename = "preferences", default, skip_serializing_if = "WireOptional::is_missing")]
    pub preferences: WireOptional<EnvironmentPreferences>,
    #[serde(rename = "schemaVersion", default, skip_serializing_if = "WireOptional::is_missing")]
    pub schema_version: WireOptional<i64>,
    #[serde(rename = "timing", default, skip_serializing_if = "WireOptional::is_missing")]
    pub timing: WireOptional<EnvironmentTiming>,
    #[serde(rename = "window", default, skip_serializing_if = "WireOptional::is_missing")]
    pub window: WireOptional<EnvironmentWindow>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentProxy {
    #[serde(rename = "password", default, skip_serializing_if = "WireOptional::is_missing")]
    pub password: WireOptional<String>,
    #[serde(rename = "server", default, skip_serializing_if = "WireOptional::is_missing")]
    pub server: WireOptional<String>,
    #[serde(rename = "username", default, skip_serializing_if = "WireOptional::is_missing")]
    pub username: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentRTPCodec {
    #[serde(rename = "channels", default, skip_serializing_if = "WireOptional::is_missing")]
    pub channels: WireOptional<i64>,
    #[serde(rename = "clockRate", default, skip_serializing_if = "WireOptional::is_missing")]
    pub clock_rate: WireOptional<i64>,
    #[serde(rename = "feedback", default, skip_serializing_if = "WireOptional::is_missing")]
    pub feedback: WireOptional<Vec<String>>,
    #[serde(rename = "name", default, skip_serializing_if = "WireOptional::is_missing")]
    pub name: WireOptional<String>,
    #[serde(rename = "parameters", default, skip_serializing_if = "WireOptional::is_missing")]
    pub parameters: WireOptional<String>,
    #[serde(rename = "payload", default, skip_serializing_if = "WireOptional::is_missing")]
    pub payload: WireOptional<i64>,
    #[serde(rename = "redundant", default, skip_serializing_if = "WireOptional::is_missing")]
    pub redundant: WireOptional<Vec<String>>,
    #[serde(rename = "rtxPayload", default, skip_serializing_if = "WireOptional::is_missing")]
    pub rtx_payload: WireOptional<i64>,
    #[serde(rename = "senderParameters", default, skip_serializing_if = "WireOptional::is_missing")]
    pub sender_parameters: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentRTPMediaCatalog {
    #[serde(rename = "codecs", default, skip_serializing_if = "WireOptional::is_missing")]
    pub codecs: WireOptional<std::collections::BTreeMap<String, EnvironmentRTPCodec>>,
    #[serde(rename = "headerExtensions", default, skip_serializing_if = "WireOptional::is_missing")]
    pub header_extensions: WireOptional<Vec<String>>,
    #[serde(rename = "offerOrder", default, skip_serializing_if = "WireOptional::is_missing")]
    pub offer_order: WireOptional<Vec<String>>,
    #[serde(rename = "receiverOrder", default, skip_serializing_if = "WireOptional::is_missing")]
    pub receiver_order: WireOptional<Vec<String>>,
    #[serde(rename = "receiverRTT", default, skip_serializing_if = "WireOptional::is_missing")]
    pub receiver_r_t_t: WireOptional<bool>,
    #[serde(rename = "senderOrder", default, skip_serializing_if = "WireOptional::is_missing")]
    pub sender_order: WireOptional<Vec<String>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentScreenOrientation {
    #[serde(rename = "angle", default, skip_serializing_if = "WireOptional::is_missing")]
    pub angle: WireOptional<i64>,
    #[serde(rename = "type", default, skip_serializing_if = "WireOptional::is_missing")]
    pub r#type: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentTiming {
    #[serde(rename = "executionScale", default, skip_serializing_if = "WireOptional::is_missing")]
    pub execution_scale: WireOptional<f64>,
    #[serde(rename = "navigationScale", default, skip_serializing_if = "WireOptional::is_missing")]
    pub navigation_scale: WireOptional<f64>,
    #[serde(rename = "networkScale", default, skip_serializing_if = "WireOptional::is_missing")]
    pub network_scale: WireOptional<f64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentUserAgentBrand {
    #[serde(rename = "brand", default, skip_serializing_if = "WireOptional::is_missing")]
    pub brand: WireOptional<String>,
    #[serde(rename = "fullVersion", default, skip_serializing_if = "WireOptional::is_missing")]
    pub full_version: WireOptional<String>,
    #[serde(rename = "version", default, skip_serializing_if = "WireOptional::is_missing")]
    pub version: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentUserAgentMetadata {
    #[serde(rename = "architecture", default, skip_serializing_if = "WireOptional::is_missing")]
    pub architecture: WireOptional<String>,
    #[serde(rename = "bitness", default, skip_serializing_if = "WireOptional::is_missing")]
    pub bitness: WireOptional<String>,
    #[serde(rename = "brands", default, skip_serializing_if = "WireOptional::is_missing")]
    pub brands: WireOptional<Vec<EnvironmentUserAgentBrand>>,
    #[serde(rename = "formFactors", default, skip_serializing_if = "WireOptional::is_missing")]
    pub form_factors: WireOptional<Vec<String>>,
    #[serde(rename = "fullVersion", default, skip_serializing_if = "WireOptional::is_missing")]
    pub full_version: WireOptional<String>,
    #[serde(rename = "fullVersionList", default, skip_serializing_if = "WireOptional::is_missing")]
    pub full_version_list: WireOptional<Vec<EnvironmentUserAgentBrand>>,
    #[serde(rename = "mobile", default, skip_serializing_if = "WireOptional::is_missing")]
    pub mobile: WireOptional<bool>,
    #[serde(rename = "model", default, skip_serializing_if = "WireOptional::is_missing")]
    pub model: WireOptional<String>,
    #[serde(rename = "platform", default, skip_serializing_if = "WireOptional::is_missing")]
    pub platform: WireOptional<String>,
    #[serde(rename = "platformVersion", default, skip_serializing_if = "WireOptional::is_missing")]
    pub platform_version: WireOptional<String>,
    #[serde(rename = "wow64", default, skip_serializing_if = "WireOptional::is_missing")]
    pub wow64: WireOptional<bool>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct EnvironmentWindow {
    #[serde(rename = "outerHeight", default, skip_serializing_if = "WireOptional::is_missing")]
    pub outer_height: WireOptional<i64>,
    #[serde(rename = "outerWidth", default, skip_serializing_if = "WireOptional::is_missing")]
    pub outer_width: WireOptional<i64>,
    #[serde(rename = "viewportHeight", default, skip_serializing_if = "WireOptional::is_missing")]
    pub viewport_height: WireOptional<i64>,
    #[serde(rename = "viewportWidth", default, skip_serializing_if = "WireOptional::is_missing")]
    pub viewport_width: WireOptional<i64>,
    #[serde(rename = "x", default, skip_serializing_if = "WireOptional::is_missing")]
    pub x: WireOptional<i64>,
    #[serde(rename = "y", default, skip_serializing_if = "WireOptional::is_missing")]
    pub y: WireOptional<i64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ExecutionStatus {
    #[serde(rename = "elapsedMs")]
    pub elapsed_ms: i64,
    #[serde(rename = "phase")]
    pub phase: String,
    #[serde(rename = "running")]
    pub running: bool,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "taskId")]
    pub task_id: i64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ExportProfileParams {
    #[serde(rename = "profile")]
    pub profile: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ExportProfileResult {
    #[serde(rename = "profile")]
    pub profile: ProfileDescriptor,
    #[serde(rename = "warnings")]
    pub warnings: Vec<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GenerateProfileOptions {
    #[serde(rename = "browser", default, skip_serializing_if = "WireOptional::is_missing")]
    pub browser: WireOptional<String>,
    #[serde(rename = "platform", default, skip_serializing_if = "WireOptional::is_missing")]
    pub platform: WireOptional<String>,
    #[serde(rename = "seed", default, skip_serializing_if = "WireOptional::is_missing")]
    pub seed: WireOptional<String>,
    #[serde(rename = "version", default, skip_serializing_if = "WireOptional::is_missing")]
    pub version: WireOptional<i64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GenerateProfileParams {
    #[serde(rename = "browser", default, skip_serializing_if = "WireOptional::is_missing")]
    pub browser: WireOptional<String>,
    #[serde(rename = "platform", default, skip_serializing_if = "WireOptional::is_missing")]
    pub platform: WireOptional<String>,
    #[serde(rename = "seed", default, skip_serializing_if = "WireOptional::is_missing")]
    pub seed: WireOptional<String>,
    #[serde(rename = "version", default, skip_serializing_if = "WireOptional::is_missing")]
    pub version: WireOptional<i64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GenerateProfileResult {
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "profile")]
    pub profile: String,
    #[serde(rename = "profileId")]
    pub profile_id: String,
    #[serde(rename = "warnings")]
    pub warnings: Vec<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GenerateProfileSelection {
    #[serde(rename = "generate")]
    pub generate: GenerateProfileOptions,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetCompatibilityMatrixParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetCompatibilityMatrixResult {
    #[serde(rename = "chromeVersion")]
    pub chrome_version: String,
    #[serde(rename = "extensions")]
    pub extensions: Vec<ProtocolCoverage>,
    #[serde(rename = "protocol")]
    pub protocol: Vec<ProtocolCoverage>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetDiagnosticsParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetDiagnosticsResult {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "costs", default, skip_serializing_if = "WireOptional::is_missing")]
    pub costs: WireOptional<std::collections::BTreeMap<String, DiagnosticCost>>,
    #[serde(rename = "cpu_profiles", default, skip_serializing_if = "WireOptional::is_missing")]
    pub cpu_profiles: WireOptional<std::collections::BTreeMap<String, serde_json::Value>>,
    #[serde(rename = "hostOnly", default, skip_serializing_if = "WireOptional::is_missing")]
    pub host_only: WireOptional<bool>,
    #[serde(rename = "realms", default, skip_serializing_if = "WireOptional::is_missing")]
    pub realms: WireOptional<Vec<RealmDiagnostics>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetMediaPresetsParams {
    #[serde(rename = "browserContextId", default, skip_serializing_if = "WireOptional::is_missing")]
    pub browser_context_id: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetMediaPresetsResult {
    #[serde(rename = "presets")]
    pub presets: Vec<MediaPreset>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetMediaProfileParams {
    #[serde(rename = "browserContextId", default, skip_serializing_if = "WireOptional::is_missing")]
    pub browser_context_id: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetMediaProfileResult {
    #[serde(rename = "diagnostics")]
    pub diagnostics: std::collections::BTreeMap<String, String>,
    #[serde(rename = "profile")]
    pub profile: Option<MediaProfile>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetMediaSourcesParams {
    #[serde(rename = "browserContextId", default, skip_serializing_if = "WireOptional::is_missing")]
    pub browser_context_id: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetMediaSourcesResult {
    #[serde(rename = "diagnostics")]
    pub diagnostics: std::collections::BTreeMap<String, String>,
    #[serde(rename = "sources")]
    pub sources: Vec<MediaSource>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetProfileParams {
    #[serde(rename = "browserContextId", default, skip_serializing_if = "WireOptional::is_missing")]
    pub browser_context_id: WireOptional<String>,
    #[serde(rename = "targetId", default, skip_serializing_if = "WireOptional::is_missing")]
    pub target_id: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetProfileResult {
    #[serde(rename = "limitations")]
    pub limitations: Vec<String>,
    #[serde(rename = "profile")]
    pub profile: EnvironmentProfile,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetProfileSchemaParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetProfileSchemaResult {
    #[serde(rename = "baseProfiles")]
    pub base_profiles: Vec<String>,
    #[serde(rename = "limitations")]
    pub limitations: Vec<String>,
    #[serde(rename = "schema")]
    pub schema: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetResourcePolicyParams {
    #[serde(rename = "browserContextId")]
    pub browser_context_id: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetResourcePolicyResult {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "generation")]
    pub generation: i64,
    #[serde(rename = "policy")]
    pub policy: ResourcePolicy,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetResourcePolicySchemaParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetResourcePolicySchemaResult {
    #[serde(rename = "schema")]
    pub schema: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetResourcePolicyStatsParams {
    #[serde(rename = "browserContextId")]
    pub browser_context_id: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetResourcePolicyStatsResult {
    #[serde(rename = "stats")]
    pub stats: ResourcePolicyStats,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetStatusParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetStatusResult {
    #[serde(rename = "execution")]
    pub execution: ExecutionStatus,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetTraceParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetTraceResult {
    #[serde(rename = "crashReports")]
    pub crash_reports: std::collections::BTreeMap<String, String>,
    #[serde(rename = "events")]
    pub events: Option<Vec<TraceEvent>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetVersionParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GetVersionResult {
    #[serde(rename = "baseProfile")]
    pub base_profile: String,
    #[serde(rename = "chromeVersion")]
    pub chrome_version: String,
    #[serde(rename = "version")]
    pub version: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ImportProfileParams {
    #[serde(rename = "profile")]
    pub profile: serde_json::Value,
    #[serde(rename = "mode", default, skip_serializing_if = "WireOptional::is_missing")]
    pub mode: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ImportProfileResult {
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "profile")]
    pub profile: String,
    #[serde(rename = "profileId")]
    pub profile_id: String,
    #[serde(rename = "warnings")]
    pub warnings: Vec<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ManualNetwork {
    #[serde(rename = "cookiesEnabled", default, skip_serializing_if = "WireOptional::is_missing")]
    pub cookies_enabled: WireOptional<bool>,
    #[serde(rename = "downlinkMbps", default, skip_serializing_if = "WireOptional::is_missing")]
    pub downlink_mbps: WireOptional<f64>,
    #[serde(rename = "effectiveType", default, skip_serializing_if = "WireOptional::is_missing")]
    pub effective_type: WireOptional<String>,
    #[serde(rename = "ice", default, skip_serializing_if = "WireOptional::is_missing")]
    pub ice: WireOptional<EnvironmentICEProfile>,
    #[serde(rename = "online", default, skip_serializing_if = "WireOptional::is_missing")]
    pub online: WireOptional<bool>,
    #[serde(rename = "rttMillis", default, skip_serializing_if = "WireOptional::is_missing")]
    pub rtt_millis: WireOptional<f64>,
    #[serde(rename = "saveData", default, skip_serializing_if = "WireOptional::is_missing")]
    pub save_data: WireOptional<bool>,
    #[serde(rename = "wireProfile", default, skip_serializing_if = "WireOptional::is_missing")]
    pub wire_profile: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ManualProfile {
    #[serde(rename = "audio", default, skip_serializing_if = "WireOptional::is_missing")]
    pub audio: WireOptional<EnvironmentAudio>,
    #[serde(rename = "capabilities", default, skip_serializing_if = "WireOptional::is_missing")]
    pub capabilities: WireOptional<EnvironmentCapabilities>,
    #[serde(rename = "display", default, skip_serializing_if = "WireOptional::is_missing")]
    pub display: WireOptional<EnvironmentDisplay>,
    #[serde(rename = "features", default, skip_serializing_if = "WireOptional::is_missing")]
    pub features: WireOptional<std::collections::BTreeMap<String, bool>>,
    #[serde(rename = "fonts", default, skip_serializing_if = "WireOptional::is_missing")]
    pub fonts: WireOptional<EnvironmentFonts>,
    #[serde(rename = "graphics", default, skip_serializing_if = "WireOptional::is_missing")]
    pub graphics: WireOptional<EnvironmentGraphics>,
    #[serde(rename = "hardware", default, skip_serializing_if = "WireOptional::is_missing")]
    pub hardware: WireOptional<EnvironmentHardware>,
    #[serde(rename = "identity", default, skip_serializing_if = "WireOptional::is_missing")]
    pub identity: WireOptional<EnvironmentIdentity>,
    #[serde(rename = "locale", default, skip_serializing_if = "WireOptional::is_missing")]
    pub locale: WireOptional<EnvironmentLocale>,
    #[serde(rename = "network", default, skip_serializing_if = "WireOptional::is_missing")]
    pub network: WireOptional<ManualNetwork>,
    #[serde(rename = "permissions", default, skip_serializing_if = "WireOptional::is_missing")]
    pub permissions: WireOptional<std::collections::BTreeMap<String, String>>,
    #[serde(rename = "preferences", default, skip_serializing_if = "WireOptional::is_missing")]
    pub preferences: WireOptional<EnvironmentPreferences>,
    #[serde(rename = "timing", default, skip_serializing_if = "WireOptional::is_missing")]
    pub timing: WireOptional<EnvironmentTiming>,
    #[serde(rename = "window", default, skip_serializing_if = "WireOptional::is_missing")]
    pub window: WireOptional<EnvironmentWindow>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MediaCameraRequest {
    #[serde(rename = "overrides", default, skip_serializing_if = "WireOptional::is_missing")]
    pub overrides: WireOptional<MediaDeviceOverride>,
    #[serde(rename = "profile", default, skip_serializing_if = "WireOptional::is_missing")]
    pub profile: WireOptional<String>,
    #[serde(rename = "source", default, skip_serializing_if = "WireOptional::is_missing")]
    pub source: WireOptional<MediaSourceSelector>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MediaConfiguration {
    #[serde(rename = "camera", default, skip_serializing_if = "WireOptional::is_missing")]
    pub camera: WireOptional<MediaCameraRequest>,
    #[serde(rename = "devices", default, skip_serializing_if = "WireOptional::is_missing")]
    pub devices: WireOptional<Vec<MediaDeviceProfile>>,
    #[serde(rename = "microphone", default, skip_serializing_if = "WireOptional::is_missing")]
    pub microphone: WireOptional<MediaMicrophoneRequest>,
    #[serde(rename = "seed", default, skip_serializing_if = "WireOptional::is_missing")]
    pub seed: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MediaDeviceOverride {
    #[serde(rename = "defaultMode", default, skip_serializing_if = "WireOptional::is_missing")]
    pub default_mode: WireOptional<CameraFormat>,
    #[serde(rename = "label", default, skip_serializing_if = "WireOptional::is_missing")]
    pub label: WireOptional<String>,
    #[serde(rename = "modes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub modes: WireOptional<Vec<CameraFormat>>,
    #[serde(rename = "processing", default, skip_serializing_if = "WireOptional::is_missing")]
    pub processing: WireOptional<MediaProcessing>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MediaDeviceProfile {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "source")]
    pub source: MediaSourceSelector,
    #[serde(rename = "defaultMode", default, skip_serializing_if = "WireOptional::is_missing")]
    pub default_mode: WireOptional<CameraFormat>,
    #[serde(rename = "group", default, skip_serializing_if = "WireOptional::is_missing")]
    pub group: WireOptional<String>,
    #[serde(rename = "modes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub modes: WireOptional<Vec<CameraFormat>>,
    #[serde(rename = "processing", default, skip_serializing_if = "WireOptional::is_missing")]
    pub processing: WireOptional<MediaProcessing>,
    #[serde(rename = "profile", default, skip_serializing_if = "WireOptional::is_missing")]
    pub profile: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MediaMicrophoneRequest {
    #[serde(rename = "profile", default, skip_serializing_if = "WireOptional::is_missing")]
    pub profile: WireOptional<String>,
    #[serde(rename = "source", default, skip_serializing_if = "WireOptional::is_missing")]
    pub source: WireOptional<MediaSourceSelector>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MediaPreset {
    #[serde(rename = "class")]
    pub class: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "variants")]
    pub variants: Vec<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MediaProcessing {
    #[serde(rename = "noise", default, skip_serializing_if = "WireOptional::is_missing")]
    pub noise: WireOptional<f64>,
    #[serde(rename = "resize", default, skip_serializing_if = "WireOptional::is_missing")]
    pub resize: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MediaProfile {
    #[serde(rename = "devices")]
    pub devices: Vec<MediaDeviceProfile>,
    #[serde(rename = "seed")]
    pub seed: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MediaSource {
    #[serde(rename = "default")]
    pub default: bool,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "sourceId")]
    pub source_id: String,
}
pub type MediaSourceSelector = serde_json::Value;
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct PauseParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct PauseResult {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProfileDescriptor {
    #[serde(rename = "baseProfile")]
    pub base_profile: String,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "profileId")]
    pub profile_id: String,
    #[serde(rename = "environment", default, skip_serializing_if = "WireOptional::is_missing")]
    pub environment: WireOptional<ManualProfile>,
    #[serde(rename = "seed", default, skip_serializing_if = "WireOptional::is_missing")]
    pub seed: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProfileErrorData {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "reason")]
    pub reason: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProfilePatch {
    #[serde(rename = "audio", default, skip_serializing_if = "WireOptional::is_missing")]
    pub audio: WireOptional<EnvironmentAudio>,
    #[serde(rename = "capabilities", default, skip_serializing_if = "WireOptional::is_missing")]
    pub capabilities: WireOptional<EnvironmentCapabilities>,
    #[serde(rename = "display", default, skip_serializing_if = "WireOptional::is_missing")]
    pub display: WireOptional<EnvironmentDisplay>,
    #[serde(rename = "features", default, skip_serializing_if = "WireOptional::is_missing")]
    pub features: WireOptional<std::collections::BTreeMap<String, bool>>,
    #[serde(rename = "fonts", default, skip_serializing_if = "WireOptional::is_missing")]
    pub fonts: WireOptional<EnvironmentFonts>,
    #[serde(rename = "graphics", default, skip_serializing_if = "WireOptional::is_missing")]
    pub graphics: WireOptional<EnvironmentGraphics>,
    #[serde(rename = "hardware", default, skip_serializing_if = "WireOptional::is_missing")]
    pub hardware: WireOptional<EnvironmentHardware>,
    #[serde(rename = "identity", default, skip_serializing_if = "WireOptional::is_missing")]
    pub identity: WireOptional<EnvironmentIdentity>,
    #[serde(rename = "locale", default, skip_serializing_if = "WireOptional::is_missing")]
    pub locale: WireOptional<EnvironmentLocale>,
    #[serde(rename = "network", default, skip_serializing_if = "WireOptional::is_missing")]
    pub network: WireOptional<ManualNetwork>,
    #[serde(rename = "permissions", default, skip_serializing_if = "WireOptional::is_missing")]
    pub permissions: WireOptional<std::collections::BTreeMap<String, String>>,
    #[serde(rename = "preferences", default, skip_serializing_if = "WireOptional::is_missing")]
    pub preferences: WireOptional<EnvironmentPreferences>,
    #[serde(rename = "timing", default, skip_serializing_if = "WireOptional::is_missing")]
    pub timing: WireOptional<EnvironmentTiming>,
    #[serde(rename = "window", default, skip_serializing_if = "WireOptional::is_missing")]
    pub window: WireOptional<EnvironmentWindow>,
}
pub type ProfileSelection = serde_json::Value;
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProtocolCoverage {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "semanticsImplemented")]
    pub semantics_implemented: bool,
    #[serde(rename = "semanticsVerified")]
    pub semantics_verified: bool,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "surfaceRegistered")]
    pub surface_registered: bool,
    #[serde(rename = "wireSchemaGenerated")]
    pub wire_schema_generated: bool,
    #[serde(rename = "notes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub notes: WireOptional<String>,
    #[serde(rename = "tests", default, skip_serializing_if = "WireOptional::is_missing")]
    pub tests: WireOptional<Vec<String>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ProtocolError {
    #[serde(rename = "code")]
    pub code: i64,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "data", default, skip_serializing_if = "WireOptional::is_missing")]
    pub data: WireOptional<serde_json::Value>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Proxy {
    #[serde(rename = "password", default, skip_serializing_if = "WireOptional::is_missing")]
    pub password: WireOptional<String>,
    #[serde(rename = "server", default, skip_serializing_if = "WireOptional::is_missing")]
    pub server: WireOptional<String>,
    #[serde(rename = "username", default, skip_serializing_if = "WireOptional::is_missing")]
    pub username: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct RealmDiagnostics {
    #[serde(rename = "diagnostics")]
    pub diagnostics: Diagnostics,
    #[serde(rename = "realm")]
    pub realm: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResetProfileOverridesParams {
    #[serde(rename = "targetId")]
    pub target_id: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResetProfileOverridesResult {
    #[serde(rename = "profile")]
    pub profile: EnvironmentProfile,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResourceBudgets {
    #[serde(rename = "maxBodyBytes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub max_body_bytes: WireOptional<i64>,
    #[serde(rename = "maxConcurrent", default, skip_serializing_if = "WireOptional::is_missing")]
    pub max_concurrent: WireOptional<i64>,
    #[serde(rename = "maxDecodedBytes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub max_decoded_bytes: WireOptional<i64>,
    #[serde(rename = "maxRequests", default, skip_serializing_if = "WireOptional::is_missing")]
    pub max_requests: WireOptional<i64>,
    #[serde(rename = "maxResponseBytes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub max_response_bytes: WireOptional<i64>,
    #[serde(rename = "maxRetainedBytes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub max_retained_bytes: WireOptional<i64>,
    #[serde(rename = "maxWireBytes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub max_wire_bytes: WireOptional<i64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResourceMatch {
    #[serde(rename = "hosts", default, skip_serializing_if = "WireOptional::is_missing")]
    pub hosts: WireOptional<Vec<String>>,
    #[serde(rename = "kinds", default, skip_serializing_if = "WireOptional::is_missing")]
    pub kinds: WireOptional<Vec<String>>,
    #[serde(rename = "mechanisms", default, skip_serializing_if = "WireOptional::is_missing")]
    pub mechanisms: WireOptional<Vec<String>>,
    #[serde(rename = "origins", default, skip_serializing_if = "WireOptional::is_missing")]
    pub origins: WireOptional<Vec<String>>,
    #[serde(rename = "owners", default, skip_serializing_if = "WireOptional::is_missing")]
    pub owners: WireOptional<Vec<String>>,
    #[serde(rename = "topLevelSite", default, skip_serializing_if = "WireOptional::is_missing")]
    pub top_level_site: WireOptional<String>,
    #[serde(rename = "urlGlob", default, skip_serializing_if = "WireOptional::is_missing")]
    pub url_glob: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResourcePolicy {
    #[serde(rename = "budgets", default, skip_serializing_if = "WireOptional::is_missing")]
    pub budgets: WireOptional<ResourceBudgets>,
    #[serde(rename = "presets", default, skip_serializing_if = "WireOptional::is_missing")]
    pub presets: WireOptional<Vec<String>>,
    #[serde(rename = "reportOnly", default, skip_serializing_if = "WireOptional::is_missing")]
    pub report_only: WireOptional<bool>,
    #[serde(rename = "rules", default, skip_serializing_if = "WireOptional::is_missing")]
    pub rules: WireOptional<Vec<ResourceRule>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResourcePolicyStats {
    #[serde(rename = "blocked")]
    pub blocked: i64,
    #[serde(rename = "bodyBytesConsumed")]
    pub body_bytes_consumed: i64,
    #[serde(rename = "budgetDenied")]
    pub budget_denied: i64,
    #[serde(rename = "byRule")]
    pub by_rule: std::collections::BTreeMap<String, i64>,
    #[serde(rename = "cacheHits")]
    pub cache_hits: i64,
    #[serde(rename = "decodedPixelWorkBytes")]
    pub decoded_pixel_work_bytes: i64,
    #[serde(rename = "encodedNetworkBodyBytes")]
    pub encoded_network_body_bytes: i64,
    #[serde(rename = "generation")]
    pub generation: i64,
    #[serde(rename = "headerOnly")]
    pub header_only: i64,
    #[serde(rename = "knownAvoidedBodyReadBytes")]
    pub known_avoided_body_read_bytes: i64,
    #[serde(rename = "networkAcquisitions")]
    pub network_acquisitions: i64,
    #[serde(rename = "prefixes")]
    pub prefixes: i64,
    #[serde(rename = "requests")]
    pub requests: i64,
    #[serde(rename = "retainedBodyBytes")]
    pub retained_body_bytes: i64,
    #[serde(rename = "unknownAvoidedBodyRequests")]
    pub unknown_avoided_body_requests: i64,
    #[serde(rename = "wireBytesKnown")]
    pub wire_bytes_known: i64,
    #[serde(rename = "wouldBlock")]
    pub would_block: i64,
    #[serde(rename = "wouldBypassCache")]
    pub would_bypass_cache: i64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResourceRule {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "match", default, skip_serializing_if = "WireOptional::is_missing")]
    pub r#match: WireOptional<ResourceMatch>,
    #[serde(rename = "work", default, skip_serializing_if = "WireOptional::is_missing")]
    pub work: WireOptional<ResourceWork>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResourceWork {
    #[serde(rename = "body", default, skip_serializing_if = "WireOptional::is_missing")]
    pub body: WireOptional<String>,
    #[serde(rename = "cacheRead", default, skip_serializing_if = "WireOptional::is_missing")]
    pub cache_read: WireOptional<bool>,
    #[serde(rename = "cacheRetain", default, skip_serializing_if = "WireOptional::is_missing")]
    pub cache_retain: WireOptional<bool>,
    #[serde(rename = "debugRetain", default, skip_serializing_if = "WireOptional::is_missing")]
    pub debug_retain: WireOptional<bool>,
    #[serde(rename = "decode", default, skip_serializing_if = "WireOptional::is_missing")]
    pub decode: WireOptional<bool>,
    #[serde(rename = "network", default, skip_serializing_if = "WireOptional::is_missing")]
    pub network: WireOptional<bool>,
    #[serde(rename = "prefixBytes", default, skip_serializing_if = "WireOptional::is_missing")]
    pub prefix_bytes: WireOptional<i64>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResumeParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ResumeResult {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct SetMediaProfileParams {
    #[serde(rename = "browserContextId", default, skip_serializing_if = "WireOptional::is_missing")]
    pub browser_context_id: WireOptional<String>,
    #[serde(rename = "camera", default, skip_serializing_if = "WireOptional::is_missing")]
    pub camera: WireOptional<MediaCameraRequest>,
    #[serde(rename = "devices", default, skip_serializing_if = "WireOptional::is_missing")]
    pub devices: WireOptional<Vec<MediaDeviceProfile>>,
    #[serde(rename = "microphone", default, skip_serializing_if = "WireOptional::is_missing")]
    pub microphone: WireOptional<MediaMicrophoneRequest>,
    #[serde(rename = "seed", default, skip_serializing_if = "WireOptional::is_missing")]
    pub seed: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct SetMediaProfileResult {
    #[serde(rename = "nativeModesVerified")]
    pub native_modes_verified: bool,
    #[serde(rename = "profile")]
    pub profile: MediaProfile,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct SetViewportParams {
    #[serde(rename = "height")]
    pub height: i64,
    #[serde(rename = "width")]
    pub width: i64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct SetViewportResult {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct StartTraceParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct StartTraceResult {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct StopTraceParams {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct StopTraceResult {
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TraceEvent {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "sequence")]
    pub sequence: i64,
    #[serde(rename = "time")]
    pub time: String,
    #[serde(rename = "data", default, skip_serializing_if = "WireOptional::is_missing")]
    pub data: WireOptional<std::collections::BTreeMap<String, serde_json::Value>>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct UpdateProfileParams {
    #[serde(rename = "patch")]
    pub patch: ProfilePatch,
    #[serde(rename = "targetId")]
    pub target_id: String,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct UpdateProfileResult {
    #[serde(rename = "profile")]
    pub profile: EnvironmentProfile,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct UpdateResourcePolicyParams {
    #[serde(rename = "browserContextId")]
    pub browser_context_id: String,
    #[serde(rename = "policy")]
    pub policy: ResourcePolicy,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct UpdateResourcePolicyResult {
    #[serde(rename = "generation")]
    pub generation: i64,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ValidateMediaProfileParams {
    #[serde(rename = "browserContextId", default, skip_serializing_if = "WireOptional::is_missing")]
    pub browser_context_id: WireOptional<String>,
    #[serde(rename = "camera", default, skip_serializing_if = "WireOptional::is_missing")]
    pub camera: WireOptional<MediaCameraRequest>,
    #[serde(rename = "devices", default, skip_serializing_if = "WireOptional::is_missing")]
    pub devices: WireOptional<Vec<MediaDeviceProfile>>,
    #[serde(rename = "microphone", default, skip_serializing_if = "WireOptional::is_missing")]
    pub microphone: WireOptional<MediaMicrophoneRequest>,
    #[serde(rename = "seed", default, skip_serializing_if = "WireOptional::is_missing")]
    pub seed: WireOptional<String>,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ValidateMediaProfileResult {
    #[serde(rename = "nativeModesVerified")]
    pub native_modes_verified: bool,
    #[serde(rename = "profile")]
    pub profile: MediaProfile,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ValidateResourcePolicyParams {
    #[serde(rename = "policy")]
    pub policy: ResourcePolicy,
}
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ValidateResourcePolicyResult {
    #[serde(rename = "policy")]
    pub policy: ResourcePolicy,
}
pub const METHODS: &[&str] = &["Mimic.cancelExecution", "Mimic.captureSnapshot", "Mimic.clearTrace", "Mimic.configureContext", "Mimic.createContext", "Mimic.exportProfile", "Mimic.generateProfile", "Mimic.getCompatibilityMatrix", "Mimic.getDiagnostics", "Mimic.getMediaPresets", "Mimic.getMediaProfile", "Mimic.getMediaSources", "Mimic.getProfile", "Mimic.getProfileSchema", "Mimic.getResourcePolicy", "Mimic.getResourcePolicySchema", "Mimic.getResourcePolicyStats", "Mimic.getStatus", "Mimic.getTrace", "Mimic.getVersion", "Mimic.importProfile", "Mimic.pause", "Mimic.resetProfileOverrides", "Mimic.resume", "Mimic.setMediaProfile", "Mimic.setViewport", "Mimic.startTrace", "Mimic.stopTrace", "Mimic.updateProfile", "Mimic.updateResourcePolicy", "Mimic.validateMediaProfile", "Mimic.validateResourcePolicy"];
impl crate::transport::Client {
    pub async fn cancel_execution(&self, params: CancelExecutionParams) -> crate::transport::Result<CancelExecutionResult> {
        Ok(serde_json::from_value(self.call("Mimic.cancelExecution", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn capture_snapshot(&self, params: CaptureSnapshotParams) -> crate::transport::Result<CaptureSnapshotResult> {
        Ok(serde_json::from_value(self.call("Mimic.captureSnapshot", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn clear_trace(&self, params: ClearTraceParams) -> crate::transport::Result<ClearTraceResult> {
        Ok(serde_json::from_value(self.call("Mimic.clearTrace", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn configure_context(&self, params: ConfigureContextParams) -> crate::transport::Result<ConfigureContextResult> {
        Ok(serde_json::from_value(self.call("Mimic.configureContext", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn create_context(&self, params: CreateContextParams) -> crate::transport::Result<CreateContextResult> {
        Ok(serde_json::from_value(self.call("Mimic.createContext", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn export_profile(&self, params: ExportProfileParams) -> crate::transport::Result<ExportProfileResult> {
        Ok(serde_json::from_value(self.call("Mimic.exportProfile", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn generate_profile(&self, params: GenerateProfileParams) -> crate::transport::Result<GenerateProfileResult> {
        Ok(serde_json::from_value(self.call("Mimic.generateProfile", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_compatibility_matrix(&self, params: GetCompatibilityMatrixParams) -> crate::transport::Result<GetCompatibilityMatrixResult> {
        Ok(serde_json::from_value(self.call("Mimic.getCompatibilityMatrix", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_diagnostics(&self, params: GetDiagnosticsParams) -> crate::transport::Result<GetDiagnosticsResult> {
        Ok(serde_json::from_value(self.call("Mimic.getDiagnostics", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_media_presets(&self, params: GetMediaPresetsParams) -> crate::transport::Result<GetMediaPresetsResult> {
        Ok(serde_json::from_value(self.call("Mimic.getMediaPresets", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_media_profile(&self, params: GetMediaProfileParams) -> crate::transport::Result<GetMediaProfileResult> {
        Ok(serde_json::from_value(self.call("Mimic.getMediaProfile", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_media_sources(&self, params: GetMediaSourcesParams) -> crate::transport::Result<GetMediaSourcesResult> {
        Ok(serde_json::from_value(self.call("Mimic.getMediaSources", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_profile(&self, params: GetProfileParams) -> crate::transport::Result<GetProfileResult> {
        Ok(serde_json::from_value(self.call("Mimic.getProfile", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_profile_schema(&self, params: GetProfileSchemaParams) -> crate::transport::Result<GetProfileSchemaResult> {
        Ok(serde_json::from_value(self.call("Mimic.getProfileSchema", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_resource_policy(&self, params: GetResourcePolicyParams) -> crate::transport::Result<GetResourcePolicyResult> {
        Ok(serde_json::from_value(self.call("Mimic.getResourcePolicy", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_resource_policy_schema(&self, params: GetResourcePolicySchemaParams) -> crate::transport::Result<GetResourcePolicySchemaResult> {
        Ok(serde_json::from_value(self.call("Mimic.getResourcePolicySchema", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_resource_policy_stats(&self, params: GetResourcePolicyStatsParams) -> crate::transport::Result<GetResourcePolicyStatsResult> {
        Ok(serde_json::from_value(self.call("Mimic.getResourcePolicyStats", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_status(&self, params: GetStatusParams) -> crate::transport::Result<GetStatusResult> {
        Ok(serde_json::from_value(self.call("Mimic.getStatus", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_trace(&self, params: GetTraceParams) -> crate::transport::Result<GetTraceResult> {
        Ok(serde_json::from_value(self.call("Mimic.getTrace", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn get_version(&self, params: GetVersionParams) -> crate::transport::Result<GetVersionResult> {
        Ok(serde_json::from_value(self.call("Mimic.getVersion", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn import_profile(&self, params: ImportProfileParams) -> crate::transport::Result<ImportProfileResult> {
        Ok(serde_json::from_value(self.call("Mimic.importProfile", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn pause(&self, params: PauseParams) -> crate::transport::Result<PauseResult> {
        Ok(serde_json::from_value(self.call("Mimic.pause", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn reset_profile_overrides(&self, params: ResetProfileOverridesParams) -> crate::transport::Result<ResetProfileOverridesResult> {
        Ok(serde_json::from_value(self.call("Mimic.resetProfileOverrides", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn resume(&self, params: ResumeParams) -> crate::transport::Result<ResumeResult> {
        Ok(serde_json::from_value(self.call("Mimic.resume", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn set_media_profile(&self, params: SetMediaProfileParams) -> crate::transport::Result<SetMediaProfileResult> {
        Ok(serde_json::from_value(self.call("Mimic.setMediaProfile", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn set_viewport(&self, params: SetViewportParams) -> crate::transport::Result<SetViewportResult> {
        Ok(serde_json::from_value(self.call("Mimic.setViewport", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn start_trace(&self, params: StartTraceParams) -> crate::transport::Result<StartTraceResult> {
        Ok(serde_json::from_value(self.call("Mimic.startTrace", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn stop_trace(&self, params: StopTraceParams) -> crate::transport::Result<StopTraceResult> {
        Ok(serde_json::from_value(self.call("Mimic.stopTrace", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn update_profile(&self, params: UpdateProfileParams) -> crate::transport::Result<UpdateProfileResult> {
        Ok(serde_json::from_value(self.call("Mimic.updateProfile", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn update_resource_policy(&self, params: UpdateResourcePolicyParams) -> crate::transport::Result<UpdateResourcePolicyResult> {
        Ok(serde_json::from_value(self.call("Mimic.updateResourcePolicy", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn validate_media_profile(&self, params: ValidateMediaProfileParams) -> crate::transport::Result<ValidateMediaProfileResult> {
        Ok(serde_json::from_value(self.call("Mimic.validateMediaProfile", Some(serde_json::to_value(params)?)).await?)?)
    }
    pub async fn validate_resource_policy(&self, params: ValidateResourcePolicyParams) -> crate::transport::Result<ValidateResourcePolicyResult> {
        Ok(serde_json::from_value(self.call("Mimic.validateResourcePolicy", Some(serde_json::to_value(params)?)).await?)?)
    }
}
