// Generated by generator/generate.py; DO NOT EDIT.
// Schema SHA-256: ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6

package io.mimicbrowser.sdk;
import com.google.gson.*;
import java.util.*;
import java.lang.reflect.*;
public final class Generated {
  public static final String SCHEMA_SHA256 = "ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6";

  public static final class OptionalValue<T> {
    public final T value;
    private OptionalValue(T value) { this.value = value; }
    public static <T> OptionalValue<T> of(T value) { return new OptionalValue<>(value); }
  }
  private static final Gson GSON = new GsonBuilder().serializeNulls().create();
  public static JsonElement toWire(Object value) {
    if (value == null) return JsonNull.INSTANCE;
    if (value instanceof OptionalValue<?>) return toWire(((OptionalValue<?>)value).value);
    if (value instanceof JsonElement) return ((JsonElement)value).deepCopy();
    if (value instanceof Map<?,?>) { JsonObject out = new JsonObject(); for (Map.Entry<?,?> e : ((Map<?,?>)value).entrySet()) out.add((String)e.getKey(), toWire(e.getValue())); return out; }
    if (value instanceof Iterable<?>) { JsonArray out = new JsonArray(); for (Object child : (Iterable<?>)value) out.add(toWire(child)); return out; }
    if (value.getClass().getEnclosingClass() != Generated.class) return GSON.toJsonTree(value);
    JsonObject out = new JsonObject();
    try { for (Field field : value.getClass().getFields()) { Object child = field.get(value); if (field.getType() == OptionalValue.class && child == null) continue; out.add(wireName(field), toWire(child)); } }
    catch (IllegalAccessException e) { throw new IllegalArgumentException(e); }
    return out;
  }
  @SuppressWarnings("unchecked")
  private static Object decode(Type type, JsonElement value) {
    if (type instanceof ParameterizedType) {
      ParameterizedType generic = (ParameterizedType)type; Type raw = generic.getRawType(); Type[] args = generic.getActualTypeArguments();
      if (raw == OptionalValue.class) return OptionalValue.of(decode(args[0], value));
      if (value.isJsonNull()) return null;
      if (raw == List.class) { List<Object> out = new ArrayList<>(); for (JsonElement child : value.getAsJsonArray()) out.add(decode(args[0], child)); return out; }
      if (raw == Map.class) { Map<String,Object> out = new LinkedHashMap<>(); for (Map.Entry<String,JsonElement> e : value.getAsJsonObject().entrySet()) out.put(e.getKey(), decode(args[1],e.getValue())); return out; }
    }
    if (value.isJsonNull()) return null;
    if (type instanceof Class<?> && ((Class<?>)type).getEnclosingClass() == Generated.class) {
      try { Object out = ((Class<?>)type).getDeclaredConstructor().newInstance(); for (Field field : ((Class<?>)type).getFields()) if (value.getAsJsonObject().has(wireName(field))) field.set(out,decode(field.getGenericType(),value.getAsJsonObject().get(wireName(field)))); return out; }
      catch (ReflectiveOperationException e) { throw new IllegalArgumentException(e); }
    }
    return GSON.fromJson(value,type);
  }
  public static <T> T fromWire(Class<T> type, JsonElement value) { return type.cast(decode(type,value)); }
  private static String wireName(Field field) { com.google.gson.annotations.SerializedName name = field.getAnnotation(com.google.gson.annotations.SerializedName.class); return name == null ? field.getName() : name.value(); }

  public static final class CameraFormat {
    public Double frameRate;
    public Long height;
    public Long width;
  }
  public static final class CancelExecutionParams {
  }
  public static final class CancelExecutionResult {
    public Boolean cancelled;
  }
  public static final class CaptureSnapshotParams {
    public OptionalValue<Boolean> interrupt;
  }
  public static final class CaptureSnapshotResult {
    public Map<String, String> files;
    public Map<String, Long> timingsMs;
    public String url;
    public List<String> warnings;
  }
  public static final class ClearTraceParams {
  }
  public static final class ClearTraceResult {
  }
  public static final class ConfigureContextParams {
    public String browserContextId;
    public OptionalValue<MediaConfiguration> media;
    public OptionalValue<JsonElement> profile;
    public OptionalValue<Proxy> proxy;
    public OptionalValue<ResourcePolicy> resourcePolicy;
  }
  public static final class ConfigureContextResult {
    public String browserContextId;
    public String mode;
    public String profile;
    public String profileId;
    public List<String> warnings;
    public OptionalValue<MediaProfile> media;
  }
  public static final class CreateContextParams {
    public OptionalValue<Boolean> disposeOnDetach;
    public OptionalValue<MediaConfiguration> media;
    public OptionalValue<JsonElement> profile;
    public OptionalValue<Proxy> proxy;
    public OptionalValue<ResourcePolicy> resourcePolicy;
  }
  public static final class CreateContextResult {
    public String browserContextId;
    public String mode;
    public String profile;
    public String profileId;
    public List<String> warnings;
    public OptionalValue<MediaProfile> media;
  }
  public static final class DiagnosticCost {
    public Long count;
    public Long ns;
  }
  public static final class Diagnostics {
    public Boolean enabled;
    public OptionalValue<Map<String, DiagnosticCost>> costs;
    public OptionalValue<Map<String, JsonElement>> cpu_profiles;
    public OptionalValue<Boolean> hostOnly;
    public OptionalValue<List<RealmDiagnostics>> realms;
  }
  public static final class Empty {
  }
  public static final class EnvironmentAudio {
    public OptionalValue<Double> bufferDuration;
    public OptionalValue<Long> channels;
    public OptionalValue<Long> maxBufferFrames;
    public OptionalValue<Double> sampleRate;
  }
  public static final class EnvironmentCapabilities {
    public OptionalValue<EnvironmentDeviceCapabilities> devices;
    public OptionalValue<Map<String, String>> keyboardLayout;
    public OptionalValue<EnvironmentMediaCapabilities> media;
    public OptionalValue<Long> storageQuotaBytes;
  }
  public static final class EnvironmentDeviceCapabilities {
    public OptionalValue<Boolean> bluetoothAvailable;
    public OptionalValue<String> posture;
  }
  public static final class EnvironmentDisplay {
    public OptionalValue<Long> availableHeight;
    public OptionalValue<Long> availableWidth;
    public OptionalValue<Long> colorDepth;
    public OptionalValue<Double> deviceScaleFactor;
    public OptionalValue<Long> height;
    public OptionalValue<EnvironmentScreenOrientation> orientation;
    public OptionalValue<Long> width;
  }
  public static final class EnvironmentFonts {
    public OptionalValue<List<String>> fallback;
    public OptionalValue<String> monospace;
    public OptionalValue<String> sansSerif;
    public OptionalValue<String> serif;
    public OptionalValue<Map<String, String>> system;
    public OptionalValue<String> systemUI;
  }
  public static final class EnvironmentGPUAdapter {
    public OptionalValue<String> architecture;
    public OptionalValue<String> description;
    public OptionalValue<String> device;
    public OptionalValue<List<String>> features;
    public OptionalValue<Double> initializationDelayMillis;
    public OptionalValue<Boolean> isFallbackAdapter;
    public OptionalValue<Map<String, Long>> limits;
    public OptionalValue<Long> subgroupMaxSize;
    public OptionalValue<Long> subgroupMinSize;
    public OptionalValue<String> vendor;
    public OptionalValue<List<String>> wgslLanguageFeatures;
  }
  public static final class EnvironmentGraphics {
    public OptionalValue<Long> maxTextureSize;
    public OptionalValue<String> renderer;
    public OptionalValue<String> vendor;
    public OptionalValue<String> webGLCapabilitiesJSON;
    public OptionalValue<EnvironmentGPUAdapter> webGPU;
    public OptionalValue<Map<String, EnvironmentGPUAdapter>> webGPUAdapters;
  }
  public static final class EnvironmentHardware {
    public OptionalValue<Long> cpuPerformance;
    public OptionalValue<Boolean> cpuPerformanceKnown;
    public OptionalValue<Double> deviceMemoryGB;
    public OptionalValue<Long> logicalProcessors;
  }
  public static final class EnvironmentICEProfile {
    public OptionalValue<Double> endDelayMillis;
    public OptionalValue<Long> hostCandidateCount;
    public OptionalValue<Double> hostDelayMillis;
    public OptionalValue<Long> networkCost;
    public OptionalValue<List<Long>> portOffsets;
    public OptionalValue<String> publicAddress;
    public OptionalValue<Long> reflexiveCandidateCount;
    public OptionalValue<Double> reflexiveDelayMillis;
    public OptionalValue<List<Long>> reflexivePortOffsets;
  }
  public static final class EnvironmentIdentity {
    public OptionalValue<EnvironmentUserAgentMetadata> metadata;
    public OptionalValue<String> platform;
    public OptionalValue<String> userAgent;
  }
  public static final class EnvironmentLocale {
    public OptionalValue<String> intlLocale;
    public OptionalValue<List<String>> languages;
    public OptionalValue<Boolean> reduceAcceptLanguage;
    public OptionalValue<String> timezone;
  }
  public static final class EnvironmentMediaCapabilities {
    public OptionalValue<EnvironmentMediaFormatCatalog> formats;
    public OptionalValue<List<String>> kinds;
    public OptionalValue<Map<String, EnvironmentRTPMediaCatalog>> rtp;
    public OptionalValue<List<String>> supportedConstraints;
  }
  public static final class EnvironmentMediaContainerPolicy {
    public OptionalValue<List<String>> codecs;
    public OptionalValue<String> defaultCodec;
    public OptionalValue<Boolean> mediaSource;
  }
  public static final class EnvironmentMediaFormatCatalog {
    public OptionalValue<Map<String, EnvironmentMediaContainerPolicy>> containers;
    public OptionalValue<List<String>> efficientVideo;
  }
  public static final class EnvironmentNetwork {
    public OptionalValue<Boolean> cookiesEnabled;
    public OptionalValue<Double> downlinkMbps;
    public OptionalValue<String> effectiveType;
    public OptionalValue<EnvironmentICEProfile> ice;
    public OptionalValue<Boolean> online;
    public OptionalValue<EnvironmentProxy> proxy;
    public OptionalValue<Double> rttMillis;
    public OptionalValue<Boolean> saveData;
    public OptionalValue<String> wireProfile;
  }
  public static final class EnvironmentPreferences {
    public OptionalValue<String> colorScheme;
    public OptionalValue<Boolean> doNotTrack;
    public OptionalValue<Boolean> reducedMotion;
    public OptionalValue<Map<String, Map<String, String>>> systemColors;
  }
  public static final class EnvironmentProfile {
    public OptionalValue<EnvironmentAudio> audio;
    public OptionalValue<String> baseProfile;
    public OptionalValue<EnvironmentCapabilities> capabilities;
    public OptionalValue<EnvironmentDisplay> display;
    public OptionalValue<Map<String, Boolean>> features;
    public OptionalValue<EnvironmentFonts> fonts;
    public OptionalValue<EnvironmentGraphics> graphics;
    public OptionalValue<EnvironmentHardware> hardware;
    public OptionalValue<EnvironmentIdentity> identity;
    public OptionalValue<EnvironmentLocale> locale;
    public OptionalValue<EnvironmentNetwork> network;
    public OptionalValue<Map<String, String>> permissions;
    public OptionalValue<EnvironmentPreferences> preferences;
    public OptionalValue<Long> schemaVersion;
    public OptionalValue<EnvironmentTiming> timing;
    public OptionalValue<EnvironmentWindow> window;
  }
  public static final class EnvironmentProxy {
    public OptionalValue<String> password;
    public OptionalValue<String> server;
    public OptionalValue<String> username;
  }
  public static final class EnvironmentRTPCodec {
    public OptionalValue<Long> channels;
    public OptionalValue<Long> clockRate;
    public OptionalValue<List<String>> feedback;
    public OptionalValue<String> name;
    public OptionalValue<String> parameters;
    public OptionalValue<Long> payload;
    public OptionalValue<List<String>> redundant;
    public OptionalValue<Long> rtxPayload;
    public OptionalValue<String> senderParameters;
  }
  public static final class EnvironmentRTPMediaCatalog {
    public OptionalValue<Map<String, EnvironmentRTPCodec>> codecs;
    public OptionalValue<List<String>> headerExtensions;
    public OptionalValue<List<String>> offerOrder;
    public OptionalValue<List<String>> receiverOrder;
    public OptionalValue<Boolean> receiverRTT;
    public OptionalValue<List<String>> senderOrder;
  }
  public static final class EnvironmentScreenOrientation {
    public OptionalValue<Long> angle;
    public OptionalValue<String> type;
  }
  public static final class EnvironmentTiming {
    public OptionalValue<Double> executionScale;
    public OptionalValue<Double> navigationScale;
    public OptionalValue<Double> networkScale;
  }
  public static final class EnvironmentUserAgentBrand {
    public OptionalValue<String> brand;
    public OptionalValue<String> fullVersion;
    public OptionalValue<String> version;
  }
  public static final class EnvironmentUserAgentMetadata {
    public OptionalValue<String> architecture;
    public OptionalValue<String> bitness;
    public OptionalValue<List<EnvironmentUserAgentBrand>> brands;
    public OptionalValue<List<String>> formFactors;
    public OptionalValue<String> fullVersion;
    public OptionalValue<List<EnvironmentUserAgentBrand>> fullVersionList;
    public OptionalValue<Boolean> mobile;
    public OptionalValue<String> model;
    public OptionalValue<String> platform;
    public OptionalValue<String> platformVersion;
    public OptionalValue<Boolean> wow64;
  }
  public static final class EnvironmentWindow {
    public OptionalValue<Long> outerHeight;
    public OptionalValue<Long> outerWidth;
    public OptionalValue<Long> viewportHeight;
    public OptionalValue<Long> viewportWidth;
    public OptionalValue<Long> x;
    public OptionalValue<Long> y;
  }
  public static final class ExecutionStatus {
    public Long elapsedMs;
    public String phase;
    public Boolean running;
    public String source;
    public Long taskId;
  }
  public static final class ExportProfileParams {
    public String profile;
  }
  public static final class ExportProfileResult {
    public ProfileDescriptor profile;
    public List<String> warnings;
  }
  public static final class GenerateProfileOptions {
    public OptionalValue<String> browser;
    public OptionalValue<String> platform;
    public OptionalValue<String> seed;
    public OptionalValue<Long> version;
  }
  public static final class GenerateProfileParams {
    public OptionalValue<String> browser;
    public OptionalValue<String> platform;
    public OptionalValue<String> seed;
    public OptionalValue<Long> version;
  }
  public static final class GenerateProfileResult {
    public String mode;
    public String profile;
    public String profileId;
    public List<String> warnings;
  }
  public static final class GenerateProfileSelection {
    public GenerateProfileOptions generate;
  }
  public static final class GetCompatibilityMatrixParams {
  }
  public static final class GetCompatibilityMatrixResult {
    public String chromeVersion;
    public List<ProtocolCoverage> extensions;
    public List<ProtocolCoverage> protocol;
  }
  public static final class GetDiagnosticsParams {
  }
  public static final class GetDiagnosticsResult {
    public Boolean enabled;
    public OptionalValue<Map<String, DiagnosticCost>> costs;
    public OptionalValue<Map<String, JsonElement>> cpu_profiles;
    public OptionalValue<Boolean> hostOnly;
    public OptionalValue<List<RealmDiagnostics>> realms;
  }
  public static final class GetMediaPresetsParams {
    public OptionalValue<String> browserContextId;
  }
  public static final class GetMediaPresetsResult {
    public List<MediaPreset> presets;
  }
  public static final class GetMediaProfileParams {
    public OptionalValue<String> browserContextId;
  }
  public static final class GetMediaProfileResult {
    public Map<String, String> diagnostics;
    public MediaProfile profile;
  }
  public static final class GetMediaSourcesParams {
    public OptionalValue<String> browserContextId;
  }
  public static final class GetMediaSourcesResult {
    public Map<String, String> diagnostics;
    public List<MediaSource> sources;
  }
  public static final class GetProfileParams {
    public OptionalValue<String> browserContextId;
    public OptionalValue<String> targetId;
  }
  public static final class GetProfileResult {
    public List<String> limitations;
    public EnvironmentProfile profile;
  }
  public static final class GetProfileSchemaParams {
  }
  public static final class GetProfileSchemaResult {
    public List<String> baseProfiles;
    public List<String> limitations;
    public Map<String, JsonElement> schema;
  }
  public static final class GetResourcePolicyParams {
    public String browserContextId;
  }
  public static final class GetResourcePolicyResult {
    public Boolean enabled;
    public Long generation;
    public ResourcePolicy policy;
  }
  public static final class GetResourcePolicySchemaParams {
  }
  public static final class GetResourcePolicySchemaResult {
    public Map<String, JsonElement> schema;
  }
  public static final class GetResourcePolicyStatsParams {
    public String browserContextId;
  }
  public static final class GetResourcePolicyStatsResult {
    public ResourcePolicyStats stats;
  }
  public static final class GetStatusParams {
  }
  public static final class GetStatusResult {
    public ExecutionStatus execution;
  }
  public static final class GetTraceParams {
  }
  public static final class GetTraceResult {
    public Map<String, String> crashReports;
    public List<TraceEvent> events;
  }
  public static final class GetVersionParams {
  }
  public static final class GetVersionResult {
    public String baseProfile;
    public String chromeVersion;
    public String version;
  }
  public static final class ImportProfileParams {
    public JsonElement profile;
    public OptionalValue<String> mode;
  }
  public static final class ImportProfileResult {
    public String mode;
    public String profile;
    public String profileId;
    public List<String> warnings;
  }
  public static final class ManualNetwork {
    public OptionalValue<Boolean> cookiesEnabled;
    public OptionalValue<Double> downlinkMbps;
    public OptionalValue<String> effectiveType;
    public OptionalValue<EnvironmentICEProfile> ice;
    public OptionalValue<Boolean> online;
    public OptionalValue<Double> rttMillis;
    public OptionalValue<Boolean> saveData;
    public OptionalValue<String> wireProfile;
  }
  public static final class ManualProfile {
    public OptionalValue<EnvironmentAudio> audio;
    public OptionalValue<EnvironmentCapabilities> capabilities;
    public OptionalValue<EnvironmentDisplay> display;
    public OptionalValue<Map<String, Boolean>> features;
    public OptionalValue<EnvironmentFonts> fonts;
    public OptionalValue<EnvironmentGraphics> graphics;
    public OptionalValue<EnvironmentHardware> hardware;
    public OptionalValue<EnvironmentIdentity> identity;
    public OptionalValue<EnvironmentLocale> locale;
    public OptionalValue<ManualNetwork> network;
    public OptionalValue<Map<String, String>> permissions;
    public OptionalValue<EnvironmentPreferences> preferences;
    public OptionalValue<EnvironmentTiming> timing;
    public OptionalValue<EnvironmentWindow> window;
  }
  public static final class MediaCameraRequest {
    public OptionalValue<MediaDeviceOverride> overrides;
    public OptionalValue<String> profile;
    public OptionalValue<JsonElement> source;
  }
  public static final class MediaConfiguration {
    public OptionalValue<MediaCameraRequest> camera;
    public OptionalValue<List<MediaDeviceProfile>> devices;
    public OptionalValue<MediaMicrophoneRequest> microphone;
    public OptionalValue<String> seed;
  }
  public static final class MediaDeviceOverride {
    public OptionalValue<CameraFormat> defaultMode;
    public OptionalValue<String> label;
    public OptionalValue<List<CameraFormat>> modes;
    public OptionalValue<MediaProcessing> processing;
  }
  public static final class MediaDeviceProfile {
    public String key;
    public String kind;
    public String label;
    public JsonElement source;
    public OptionalValue<CameraFormat> defaultMode;
    public OptionalValue<String> group;
    public OptionalValue<List<CameraFormat>> modes;
    public OptionalValue<MediaProcessing> processing;
    public OptionalValue<String> profile;
  }
  public static final class MediaMicrophoneRequest {
    public OptionalValue<String> profile;
    public OptionalValue<JsonElement> source;
  }
  public static final class MediaPreset {
    @com.google.gson.annotations.SerializedName("class")
    public String class_;
    public String id;
    public String label;
    public List<String> variants;
  }
  public static final class MediaProcessing {
    public OptionalValue<Double> noise;
    public OptionalValue<String> resize;
  }
  public static final class MediaProfile {
    public List<MediaDeviceProfile> devices;
    public String seed;
  }
  public static final class MediaSource {
    @com.google.gson.annotations.SerializedName("default")
    public Boolean default_;
    public String kind;
    public String label;
    public String sourceId;
  }
  public static final class PauseParams {
  }
  public static final class PauseResult {
  }
  public static final class ProfileDescriptor {
    public String baseProfile;
    public String mode;
    public String profileId;
    public OptionalValue<ManualProfile> environment;
    public OptionalValue<String> seed;
  }
  public static final class ProfileErrorData {
    public String message;
    public String path;
    public String reason;
  }
  public static final class ProfilePatch {
    public OptionalValue<EnvironmentAudio> audio;
    public OptionalValue<EnvironmentCapabilities> capabilities;
    public OptionalValue<EnvironmentDisplay> display;
    public OptionalValue<Map<String, Boolean>> features;
    public OptionalValue<EnvironmentFonts> fonts;
    public OptionalValue<EnvironmentGraphics> graphics;
    public OptionalValue<EnvironmentHardware> hardware;
    public OptionalValue<EnvironmentIdentity> identity;
    public OptionalValue<EnvironmentLocale> locale;
    public OptionalValue<ManualNetwork> network;
    public OptionalValue<Map<String, String>> permissions;
    public OptionalValue<EnvironmentPreferences> preferences;
    public OptionalValue<EnvironmentTiming> timing;
    public OptionalValue<EnvironmentWindow> window;
  }
  public static final class ProtocolCoverage {
    public String kind;
    public String name;
    public Boolean semanticsImplemented;
    public Boolean semanticsVerified;
    public String status;
    public Boolean surfaceRegistered;
    public Boolean wireSchemaGenerated;
    public OptionalValue<String> notes;
    public OptionalValue<List<String>> tests;
  }
  public static final class ProtocolError {
    public Long code;
    public String message;
    public OptionalValue<JsonElement> data;
  }
  public static final class Proxy {
    public OptionalValue<String> password;
    public OptionalValue<String> server;
    public OptionalValue<String> username;
  }
  public static final class RealmDiagnostics {
    public Diagnostics diagnostics;
    public String realm;
  }
  public static final class ResetProfileOverridesParams {
    public String targetId;
  }
  public static final class ResetProfileOverridesResult {
    public EnvironmentProfile profile;
  }
  public static final class ResourceBudgets {
    public OptionalValue<Long> maxBodyBytes;
    public OptionalValue<Long> maxConcurrent;
    public OptionalValue<Long> maxDecodedBytes;
    public OptionalValue<Long> maxRequests;
    public OptionalValue<Long> maxResponseBytes;
    public OptionalValue<Long> maxRetainedBytes;
    public OptionalValue<Long> maxWireBytes;
  }
  public static final class ResourceMatch {
    public OptionalValue<List<String>> hosts;
    public OptionalValue<List<String>> kinds;
    public OptionalValue<List<String>> mechanisms;
    public OptionalValue<List<String>> origins;
    public OptionalValue<List<String>> owners;
    public OptionalValue<String> topLevelSite;
    public OptionalValue<String> urlGlob;
  }
  public static final class ResourcePolicy {
    public OptionalValue<ResourceBudgets> budgets;
    public OptionalValue<List<String>> presets;
    public OptionalValue<Boolean> reportOnly;
    public OptionalValue<List<ResourceRule>> rules;
  }
  public static final class ResourcePolicyStats {
    public Long blocked;
    public Long bodyBytesConsumed;
    public Long budgetDenied;
    public Map<String, Long> byRule;
    public Long cacheHits;
    public Long decodedPixelWorkBytes;
    public Long encodedNetworkBodyBytes;
    public Long generation;
    public Long headerOnly;
    public Long knownAvoidedBodyReadBytes;
    public Long networkAcquisitions;
    public Long prefixes;
    public Long requests;
    public Long retainedBodyBytes;
    public Long unknownAvoidedBodyRequests;
    public Long wireBytesKnown;
    public Long wouldBlock;
    public Long wouldBypassCache;
  }
  public static final class ResourceRule {
    public String id;
    public OptionalValue<ResourceMatch> match;
    public OptionalValue<ResourceWork> work;
  }
  public static final class ResourceWork {
    public OptionalValue<String> body;
    public OptionalValue<Boolean> cacheRead;
    public OptionalValue<Boolean> cacheRetain;
    public OptionalValue<Boolean> debugRetain;
    public OptionalValue<Boolean> decode;
    public OptionalValue<Boolean> network;
    public OptionalValue<Long> prefixBytes;
  }
  public static final class ResumeParams {
  }
  public static final class ResumeResult {
  }
  public static final class SetMediaProfileParams {
    public OptionalValue<String> browserContextId;
    public OptionalValue<MediaCameraRequest> camera;
    public OptionalValue<List<MediaDeviceProfile>> devices;
    public OptionalValue<MediaMicrophoneRequest> microphone;
    public OptionalValue<String> seed;
  }
  public static final class SetMediaProfileResult {
    public Boolean nativeModesVerified;
    public MediaProfile profile;
  }
  public static final class SetViewportParams {
    public Long height;
    public Long width;
  }
  public static final class SetViewportResult {
  }
  public static final class StartTraceParams {
  }
  public static final class StartTraceResult {
  }
  public static final class StopTraceParams {
  }
  public static final class StopTraceResult {
  }
  public static final class TraceEvent {
    public String kind;
    public String name;
    public Long sequence;
    public String time;
    public OptionalValue<Map<String, JsonElement>> data;
  }
  public static final class UpdateProfileParams {
    public ProfilePatch patch;
    public String targetId;
  }
  public static final class UpdateProfileResult {
    public EnvironmentProfile profile;
  }
  public static final class UpdateResourcePolicyParams {
    public String browserContextId;
    public ResourcePolicy policy;
  }
  public static final class UpdateResourcePolicyResult {
    public Long generation;
  }
  public static final class ValidateMediaProfileParams {
    public OptionalValue<String> browserContextId;
    public OptionalValue<MediaCameraRequest> camera;
    public OptionalValue<List<MediaDeviceProfile>> devices;
    public OptionalValue<MediaMicrophoneRequest> microphone;
    public OptionalValue<String> seed;
  }
  public static final class ValidateMediaProfileResult {
    public Boolean nativeModesVerified;
    public MediaProfile profile;
  }
  public static final class ValidateResourcePolicyParams {
    public ResourcePolicy policy;
  }
  public static final class ValidateResourcePolicyResult {
    public ResourcePolicy policy;
  }
  public static final class MimicCommands {
    private final ProtocolTransport transport;
    public MimicCommands(ProtocolTransport transport) { this.transport = transport; }
    public CancelExecutionResult cancelExecution(CancelExecutionParams parameters) { return fromWire(CancelExecutionResult.class, transport.send("Mimic.cancelExecution", toWire(parameters).getAsJsonObject())); }
    public CancelExecutionResult cancelExecution() { return cancelExecution(new CancelExecutionParams()); }
    public CaptureSnapshotResult captureSnapshot(CaptureSnapshotParams parameters) { return fromWire(CaptureSnapshotResult.class, transport.send("Mimic.captureSnapshot", toWire(parameters).getAsJsonObject())); }
    public CaptureSnapshotResult captureSnapshot() { return captureSnapshot(new CaptureSnapshotParams()); }
    public ClearTraceResult clearTrace(ClearTraceParams parameters) { return fromWire(ClearTraceResult.class, transport.send("Mimic.clearTrace", toWire(parameters).getAsJsonObject())); }
    public ClearTraceResult clearTrace() { return clearTrace(new ClearTraceParams()); }
    public ConfigureContextResult configureContext(ConfigureContextParams parameters) { return fromWire(ConfigureContextResult.class, transport.send("Mimic.configureContext", toWire(parameters).getAsJsonObject())); }
    public CreateContextResult createContext(CreateContextParams parameters) { return fromWire(CreateContextResult.class, transport.send("Mimic.createContext", toWire(parameters).getAsJsonObject())); }
    public CreateContextResult createContext() { return createContext(new CreateContextParams()); }
    public ExportProfileResult exportProfile(ExportProfileParams parameters) { return fromWire(ExportProfileResult.class, transport.send("Mimic.exportProfile", toWire(parameters).getAsJsonObject())); }
    public GenerateProfileResult generateProfile(GenerateProfileParams parameters) { return fromWire(GenerateProfileResult.class, transport.send("Mimic.generateProfile", toWire(parameters).getAsJsonObject())); }
    public GenerateProfileResult generateProfile() { return generateProfile(new GenerateProfileParams()); }
    public GetCompatibilityMatrixResult getCompatibilityMatrix(GetCompatibilityMatrixParams parameters) { return fromWire(GetCompatibilityMatrixResult.class, transport.send("Mimic.getCompatibilityMatrix", toWire(parameters).getAsJsonObject())); }
    public GetCompatibilityMatrixResult getCompatibilityMatrix() { return getCompatibilityMatrix(new GetCompatibilityMatrixParams()); }
    public GetDiagnosticsResult getDiagnostics(GetDiagnosticsParams parameters) { return fromWire(GetDiagnosticsResult.class, transport.send("Mimic.getDiagnostics", toWire(parameters).getAsJsonObject())); }
    public GetDiagnosticsResult getDiagnostics() { return getDiagnostics(new GetDiagnosticsParams()); }
    public GetMediaPresetsResult getMediaPresets(GetMediaPresetsParams parameters) { return fromWire(GetMediaPresetsResult.class, transport.send("Mimic.getMediaPresets", toWire(parameters).getAsJsonObject())); }
    public GetMediaPresetsResult getMediaPresets() { return getMediaPresets(new GetMediaPresetsParams()); }
    public GetMediaProfileResult getMediaProfile(GetMediaProfileParams parameters) { return fromWire(GetMediaProfileResult.class, transport.send("Mimic.getMediaProfile", toWire(parameters).getAsJsonObject())); }
    public GetMediaProfileResult getMediaProfile() { return getMediaProfile(new GetMediaProfileParams()); }
    public GetMediaSourcesResult getMediaSources(GetMediaSourcesParams parameters) { return fromWire(GetMediaSourcesResult.class, transport.send("Mimic.getMediaSources", toWire(parameters).getAsJsonObject())); }
    public GetMediaSourcesResult getMediaSources() { return getMediaSources(new GetMediaSourcesParams()); }
    public GetProfileResult getProfile(GetProfileParams parameters) { return fromWire(GetProfileResult.class, transport.send("Mimic.getProfile", toWire(parameters).getAsJsonObject())); }
    public GetProfileSchemaResult getProfileSchema(GetProfileSchemaParams parameters) { return fromWire(GetProfileSchemaResult.class, transport.send("Mimic.getProfileSchema", toWire(parameters).getAsJsonObject())); }
    public GetProfileSchemaResult getProfileSchema() { return getProfileSchema(new GetProfileSchemaParams()); }
    public GetResourcePolicyResult getResourcePolicy(GetResourcePolicyParams parameters) { return fromWire(GetResourcePolicyResult.class, transport.send("Mimic.getResourcePolicy", toWire(parameters).getAsJsonObject())); }
    public GetResourcePolicySchemaResult getResourcePolicySchema(GetResourcePolicySchemaParams parameters) { return fromWire(GetResourcePolicySchemaResult.class, transport.send("Mimic.getResourcePolicySchema", toWire(parameters).getAsJsonObject())); }
    public GetResourcePolicySchemaResult getResourcePolicySchema() { return getResourcePolicySchema(new GetResourcePolicySchemaParams()); }
    public GetResourcePolicyStatsResult getResourcePolicyStats(GetResourcePolicyStatsParams parameters) { return fromWire(GetResourcePolicyStatsResult.class, transport.send("Mimic.getResourcePolicyStats", toWire(parameters).getAsJsonObject())); }
    public GetStatusResult getStatus(GetStatusParams parameters) { return fromWire(GetStatusResult.class, transport.send("Mimic.getStatus", toWire(parameters).getAsJsonObject())); }
    public GetStatusResult getStatus() { return getStatus(new GetStatusParams()); }
    public GetTraceResult getTrace(GetTraceParams parameters) { return fromWire(GetTraceResult.class, transport.send("Mimic.getTrace", toWire(parameters).getAsJsonObject())); }
    public GetTraceResult getTrace() { return getTrace(new GetTraceParams()); }
    public GetVersionResult getVersion(GetVersionParams parameters) { return fromWire(GetVersionResult.class, transport.send("Mimic.getVersion", toWire(parameters).getAsJsonObject())); }
    public GetVersionResult getVersion() { return getVersion(new GetVersionParams()); }
    public ImportProfileResult importProfile(ImportProfileParams parameters) { return fromWire(ImportProfileResult.class, transport.send("Mimic.importProfile", toWire(parameters).getAsJsonObject())); }
    public PauseResult pause(PauseParams parameters) { return fromWire(PauseResult.class, transport.send("Mimic.pause", toWire(parameters).getAsJsonObject())); }
    public PauseResult pause() { return pause(new PauseParams()); }
    public ResetProfileOverridesResult resetProfileOverrides(ResetProfileOverridesParams parameters) { return fromWire(ResetProfileOverridesResult.class, transport.send("Mimic.resetProfileOverrides", toWire(parameters).getAsJsonObject())); }
    public ResumeResult resume(ResumeParams parameters) { return fromWire(ResumeResult.class, transport.send("Mimic.resume", toWire(parameters).getAsJsonObject())); }
    public ResumeResult resume() { return resume(new ResumeParams()); }
    public SetMediaProfileResult setMediaProfile(SetMediaProfileParams parameters) { return fromWire(SetMediaProfileResult.class, transport.send("Mimic.setMediaProfile", toWire(parameters).getAsJsonObject())); }
    public SetViewportResult setViewport(SetViewportParams parameters) { return fromWire(SetViewportResult.class, transport.send("Mimic.setViewport", toWire(parameters).getAsJsonObject())); }
    public StartTraceResult startTrace(StartTraceParams parameters) { return fromWire(StartTraceResult.class, transport.send("Mimic.startTrace", toWire(parameters).getAsJsonObject())); }
    public StartTraceResult startTrace() { return startTrace(new StartTraceParams()); }
    public StopTraceResult stopTrace(StopTraceParams parameters) { return fromWire(StopTraceResult.class, transport.send("Mimic.stopTrace", toWire(parameters).getAsJsonObject())); }
    public StopTraceResult stopTrace() { return stopTrace(new StopTraceParams()); }
    public UpdateProfileResult updateProfile(UpdateProfileParams parameters) { return fromWire(UpdateProfileResult.class, transport.send("Mimic.updateProfile", toWire(parameters).getAsJsonObject())); }
    public UpdateResourcePolicyResult updateResourcePolicy(UpdateResourcePolicyParams parameters) { return fromWire(UpdateResourcePolicyResult.class, transport.send("Mimic.updateResourcePolicy", toWire(parameters).getAsJsonObject())); }
    public ValidateMediaProfileResult validateMediaProfile(ValidateMediaProfileParams parameters) { return fromWire(ValidateMediaProfileResult.class, transport.send("Mimic.validateMediaProfile", toWire(parameters).getAsJsonObject())); }
    public ValidateResourcePolicyResult validateResourcePolicy(ValidateResourcePolicyParams parameters) { return fromWire(ValidateResourcePolicyResult.class, transport.send("Mimic.validateResourcePolicy", toWire(parameters).getAsJsonObject())); }
  }
}
