import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../", import.meta.url));

/** Keep Git installation metadata a projection of the native Node package. */
export async function gitPackageFiles() {
  const native = JSON.parse(
    await readFile(resolve(root, "node/package.json"), "utf8"),
  );
  const manifest = {
    "//": "Generated by node node/scripts/git-package.mjs. Edit node/package.json instead.",
    ...native,
    private: true,
    scripts: {
      prepare: "node node/scripts/prepare-git.mjs",
      build: "node node/scripts/prepare-git.mjs",
    },
  };
  return {
    "package.json": `${JSON.stringify(manifest, null, 2)}\n`,
    "package-lock.json": await readFile(
      resolve(root, "node/package-lock.json"),
      "utf8",
    ),
  };
}

export async function checkGitPackage() {
  for (const [name, expected] of Object.entries(await gitPackageFiles())) {
    const actual = await readFile(resolve(root, name), "utf8");
    assert.equal(
      actual.replaceAll("\r\n", "\n"),
      expected.replaceAll("\r\n", "\n"),
      `${name} is stale; run node node/scripts/git-package.mjs`,
    );
  }
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  if (process.argv.includes("--check")) {
    await checkGitPackage();
  } else {
    for (const [name, content] of Object.entries(await gitPackageFiles())) {
      await writeFile(resolve(root, name), content);
    }
  }
}
