"""Mirror the qualified Playwright signature without hand-copying native options.

Run with the Playwright extra installed. Published wheels contain the generated
types; consumers do not run this tool or install a framework they do not use.
"""
from __future__ import annotations

import argparse
import importlib.metadata
import inspect
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def annotation(value):
    from playwright import sync_api
    if isinstance(value, type) and value.__module__ == "builtins":
        return value.__name__
    text = str(value).replace("typing.", "").replace("pathlib.", "").replace("NoneType", "None")
    return re.sub(r"playwright\._impl\._api_structures\.(\w+)",
                  lambda match: "pw." + match[1] if hasattr(sync_api, match[1]) else match[1], text)


def render():
    from playwright.sync_api import Browser
    from playwright import sync_api, async_api
    from playwright._impl import _api_structures
    pin = re.search(r'playwright==([^"\]]+)', (ROOT / "pyproject.toml").read_text())[1]
    if importlib.metadata.version("playwright") != pin:
        raise SystemExit(f"Install the qualified playwright=={pin} before generating types")
    parameters = list(inspect.signature(Browser.new_context).parameters.values())[1:]
    if any(item.kind != inspect.Parameter.KEYWORD_ONLY for item in parameters):
        raise SystemExit("Playwright context signature changed shape; review the forwarding contract")
    if parameters != list(inspect.signature(async_api.Browser.new_context).parameters.values())[1:]:
        raise SystemExit("Sync/async Playwright context options differ; review generated signatures")
    header = f'''# Generated by tools/generate_api_typing.py from Playwright {pin}; do not edit.
from __future__ import annotations
from pathlib import Path
from typing import Callable, Awaitable, Dict, List, Literal, Optional, Pattern, Sequence, TypedDict, Union
from playwright import sync_api as pw
'''
    # Some new native TypedDicts are absent from Playwright's public re-exports.
    # Mirror their structural fields automatically instead of importing private
    # framework modules in the distributed declarations.
    native_names = set(re.findall(r"playwright\._impl\._api_structures\.(\w+)",
                                 " ".join(str(item.annotation) for item in parameters)))
    missing = sorted(name for name in native_names if not hasattr(sync_api, name))
    structures = ""
    for name in missing:
        shape = getattr(_api_structures, name)
        if shape.__required_keys__:
            raise SystemExit(f"Review required fields of newly mirrored Playwright type: {name}")
        structures += f"\nclass {name}(TypedDict, total=False):\n"
        structures += "\n".join(f"    {key}: {annotation(value)}" for key, value in shape.__annotations__.items()) + "\n"
    options = header + structures + "\nclass BrowserContextOptions(TypedDict, total=False):\n"
    options += "\n".join(f"    {item.name}: {annotation(item.annotation)}" for item in parameters) + "\n"
    result = {"mimic/playwright/_options.py": options}
    for mode in ("sync", "async"):
        asynchronous = mode == "async"
        prefix = "async " if asynchronous else ""
        commands = "AsyncMimicExtensions" if asynchronous else "MimicExtensions"
        page_handle = "AsyncPageMimic" if asynchronous else "PageMimic"
        imports = header + f'''from playwright.{mode}_api import Browser, BrowserContext, Page, Playwright
from ..generated import JsonValue, MediaConfiguration, ProfileSelection, Proxy, ResourcePolicy
from .._page import {commands}, {page_handle}
from ..protocol import CDPConnection
from ..runtime import Engine, PathValue, RuntimeIdentity, RuntimeProcess
from ._options import BrowserContextOptions{''.join(', ' + name for name in missing)}

MediaValue = MediaConfiguration | dict[str, JsonValue]
'''
        factory_return = "MediaValue | Awaitable[MediaValue]" if asynchronous else "MediaValue"
        code = imports + f'''MediaFactory = Callable[[ContextSetup], {factory_return}]
class ContextSetup:
    browser_context_id: str
    mimic: {commands}
    def __init__(self, browser_context_id: str, mimic: {commands}) -> None: ...

class IntegrationSession:
    browser: Browser
    connection: CDPConnection
    mimic: {commands}
    runtime: RuntimeProcess | None
    identity: RuntimeIdentity
    close_errors: list[Exception]
'''
        if asynchronous:
            code += "    def __init__(self) -> None: ...\n    @classmethod\n    async def open(cls, endpoint: str, *, runtime: RuntimeProcess | None = ..., playwright: Playwright | None = ..., timeout: float = ...) -> IntegrationSession: ...\n"
        else:
            code += "    def __init__(self, endpoint: str, *, runtime: RuntimeProcess | None = ..., playwright: Playwright | None = ..., timeout: float = ...) -> None: ...\n"
        code += f'''
    {prefix}def new_context(
        self, *,
        media: MediaValue | MediaFactory | None = ...,
        resource_policy: ResourcePolicy | dict[str, JsonValue] | None = ...,
        profile: ProfileSelection | dict[str, JsonValue] | None = ...,
        proxy: Proxy | dict[str, JsonValue] | None = ...,
        framework: BrowserContextOptions | None = ...,
'''
        # The existing SDK proxy keyword belongs to Mimic; framework.proxy is
        # the explicit way to pass Playwright's native proxy unchanged.
        code += "\n".join(f"        {item.name}: {annotation(item.annotation)} = ...,"
                          for item in parameters if item.name != "proxy")
        code += f'''\n    ) -> BrowserContext: ...
    {prefix}def for_page(self, page: Page) -> {page_handle}: ...
    {prefix}def close(self) -> None: ...
'''
        if asynchronous:
            code += "    async def __aenter__(self) -> IntegrationSession: ...\n    async def __aexit__(self, *args: object) -> None: ...\n"
        else:
            code += "    def __enter__(self) -> IntegrationSession: ...\n    def __exit__(self, *args: object) -> None: ...\n"
        code += f'''
{prefix}def launch(*, playwright: Playwright | None = ..., engine: Engine = ..., runtime_version: str | None = ..., lock: dict[str, JsonValue] | str | Path | None = ..., executable_path: PathValue | None = ..., runtime_dir: PathValue | None = ..., allow_download: bool | None = ..., timeout: float = ...) -> IntegrationSession: ...
{prefix}def connect(endpoint: str, *, playwright: Playwright | None = ..., timeout: float = ...) -> IntegrationSession: ...
'''
        result[f"mimic/playwright/{mode}_api.pyi"] = code
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for relative, content in render().items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Stale native API typing: {relative}")
        else:
            path.write_text(content, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
