from .generated import AsyncMimicCommands, MimicCommands
from .protocol import AsyncExperimental, Experimental

class MimicExtensions(MimicCommands):
    experimental: Experimental
class AsyncMimicExtensions(AsyncMimicCommands):
    experimental: AsyncExperimental
class PageMimic(MimicExtensions):
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def detach(self) -> None: ...
    def __enter__(self) -> PageMimic: ...
    def __exit__(self, *args: object) -> None: ...
class AsyncPageMimic(AsyncMimicExtensions):
    @property
    def closed(self) -> bool: ...
    async def close(self) -> None: ...
    async def detach(self) -> None: ...
    async def __aenter__(self) -> AsyncPageMimic: ...
    async def __aexit__(self, *args: object) -> None: ...
