# Generated by generator/generate.py; DO NOT EDIT.
# Schema SHA-256: ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6

from __future__ import annotations
from dataclasses import dataclass, field, fields, is_dataclass
from typing import Any, TypeAlias, Union, Literal, get_args, get_origin, get_type_hints
import types
SCHEMA_SHA256 = "ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6"

class Unset:
    """An absent field, distinct from explicit JSON null."""
    __slots__ = ()

UNSET = Unset()
JsonValue: TypeAlias = Union[None, bool, int, float, str, list["JsonValue"], dict[str, "JsonValue"]]

def to_wire(value: Any) -> Any:
    if isinstance(value, Unset):
        raise TypeError("UNSET is only valid as an omitted object field")
    if is_dataclass(value):
        return {field.metadata["wire"]: to_wire(getattr(value, field.name)) for field in fields(value) if not isinstance(getattr(value, field.name), Unset)}
    if isinstance(value, dict):
        return {key: to_wire(child) for key, child in value.items() if not isinstance(child, Unset)}
    if isinstance(value, (list, tuple)):
        return [to_wire(child) for child in value]
    return value

def from_wire(model: Any, value: Any) -> Any:
    if value is None:
        return None
    origin, args = get_origin(model), get_args(model)
    if origin in (Union, types.UnionType):
        for choice in args:
            if choice in (Unset, type(None)):
                continue
            try:
                return from_wire(choice, value)
            except (TypeError, ValueError, KeyError):
                pass
        raise TypeError("No wire union branch matched")
    if origin is Literal:
        if value not in args:
            raise ValueError("Unknown enum value")
        return value
    if origin is list:
        if not isinstance(value, list): raise TypeError("Expected array")
        return [from_wire(args[0], child) for child in value]
    if origin is dict:
        if not isinstance(value, dict): raise TypeError("Expected object")
        return {key: from_wire(args[1], child) for key, child in value.items()}
    if isinstance(model, type) and is_dataclass(model):
        if not isinstance(value, dict): raise TypeError("Expected object")
        hints = get_type_hints(model)
        options = {}
        for field in fields(model):
            key = field.metadata["wire"]
            if key in value: options[field.name] = from_wire(hints[field.name], value[key])
        return model(**options)
    if model in (str, bool, int, float):
        if model is float and isinstance(value, (int, float)) and not isinstance(value, bool): return value
        if not isinstance(value, model) or model is int and isinstance(value, bool): raise TypeError("Invalid primitive")
    return value

@dataclass(kw_only=True)
class CameraFormat:
    frame_rate: float = field(metadata={"wire": "frameRate"})
    height: int = field(metadata={"wire": "height"})
    width: int = field(metadata={"wire": "width"})
@dataclass(kw_only=True)
class CancelExecutionParams:
    pass
@dataclass(kw_only=True)
class CancelExecutionResult:
    cancelled: bool = field(metadata={"wire": "cancelled"})
@dataclass(kw_only=True)
class CaptureSnapshotParams:
    interrupt: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "interrupt"})
@dataclass(kw_only=True)
class CaptureSnapshotResult:
    files: dict[str, str] = field(metadata={"wire": "files"})
    timings_ms: dict[str, int] = field(metadata={"wire": "timingsMs"})
    url: str = field(metadata={"wire": "url"})
    warnings: list[str] = field(metadata={"wire": "warnings"})
@dataclass(kw_only=True)
class ClearTraceParams:
    pass
@dataclass(kw_only=True)
class ClearTraceResult:
    pass
@dataclass(kw_only=True)
class ConfigureContextParams:
    browser_context_id: str = field(metadata={"wire": "browserContextId"})
    media: Union[MediaConfiguration, Unset] = field(default=UNSET, metadata={"wire": "media"})
    profile: Union[ProfileSelection, Unset] = field(default=UNSET, metadata={"wire": "profile"})
    proxy: Union[Proxy, Unset] = field(default=UNSET, metadata={"wire": "proxy"})
    resource_policy: Union[ResourcePolicy, Unset] = field(default=UNSET, metadata={"wire": "resourcePolicy"})
@dataclass(kw_only=True)
class ConfigureContextResult:
    browser_context_id: str = field(metadata={"wire": "browserContextId"})
    mode: Literal['generated', 'manual'] = field(metadata={"wire": "mode"})
    profile: str = field(metadata={"wire": "profile"})
    profile_id: str = field(metadata={"wire": "profileId"})
    warnings: list[str] = field(metadata={"wire": "warnings"})
    media: Union[MediaProfile, Unset] = field(default=UNSET, metadata={"wire": "media"})
@dataclass(kw_only=True)
class CreateContextParams:
    dispose_on_detach: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "disposeOnDetach"})
    media: Union[MediaConfiguration, Unset] = field(default=UNSET, metadata={"wire": "media"})
    profile: Union[ProfileSelection, Unset] = field(default=UNSET, metadata={"wire": "profile"})
    proxy: Union[Proxy, Unset] = field(default=UNSET, metadata={"wire": "proxy"})
    resource_policy: Union[ResourcePolicy, Unset] = field(default=UNSET, metadata={"wire": "resourcePolicy"})
@dataclass(kw_only=True)
class CreateContextResult:
    browser_context_id: str = field(metadata={"wire": "browserContextId"})
    mode: Literal['generated', 'manual'] = field(metadata={"wire": "mode"})
    profile: str = field(metadata={"wire": "profile"})
    profile_id: str = field(metadata={"wire": "profileId"})
    warnings: list[str] = field(metadata={"wire": "warnings"})
    media: Union[MediaProfile, Unset] = field(default=UNSET, metadata={"wire": "media"})
@dataclass(kw_only=True)
class DiagnosticCost:
    count: int = field(metadata={"wire": "count"})
    ns: int = field(metadata={"wire": "ns"})
@dataclass(kw_only=True)
class Diagnostics:
    enabled: bool = field(metadata={"wire": "enabled"})
    costs: Union[dict[str, DiagnosticCost], Unset] = field(default=UNSET, metadata={"wire": "costs"})
    cpu_profiles: Union[dict[str, JsonValue], Unset] = field(default=UNSET, metadata={"wire": "cpu_profiles"})
    host_only: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "hostOnly"})
    realms: Union[list[RealmDiagnostics], Unset] = field(default=UNSET, metadata={"wire": "realms"})
@dataclass(kw_only=True)
class Empty:
    pass
@dataclass(kw_only=True)
class EnvironmentAudio:
    buffer_duration: Union[float, Unset] = field(default=UNSET, metadata={"wire": "bufferDuration"})
    channels: Union[int, Unset] = field(default=UNSET, metadata={"wire": "channels"})
    max_buffer_frames: Union[int, Unset] = field(default=UNSET, metadata={"wire": "maxBufferFrames"})
    sample_rate: Union[float, Unset] = field(default=UNSET, metadata={"wire": "sampleRate"})
@dataclass(kw_only=True)
class EnvironmentCapabilities:
    devices: Union[EnvironmentDeviceCapabilities, Unset] = field(default=UNSET, metadata={"wire": "devices"})
    keyboard_layout: Union[dict[str, str], Unset] = field(default=UNSET, metadata={"wire": "keyboardLayout"})
    media: Union[EnvironmentMediaCapabilities, Unset] = field(default=UNSET, metadata={"wire": "media"})
    storage_quota_bytes: Union[int, Unset] = field(default=UNSET, metadata={"wire": "storageQuotaBytes"})
@dataclass(kw_only=True)
class EnvironmentDeviceCapabilities:
    bluetooth_available: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "bluetoothAvailable"})
    posture: Union[str, Unset] = field(default=UNSET, metadata={"wire": "posture"})
@dataclass(kw_only=True)
class EnvironmentDisplay:
    available_height: Union[int, Unset] = field(default=UNSET, metadata={"wire": "availableHeight"})
    available_width: Union[int, Unset] = field(default=UNSET, metadata={"wire": "availableWidth"})
    color_depth: Union[int, Unset] = field(default=UNSET, metadata={"wire": "colorDepth"})
    device_scale_factor: Union[float, Unset] = field(default=UNSET, metadata={"wire": "deviceScaleFactor"})
    height: Union[int, Unset] = field(default=UNSET, metadata={"wire": "height"})
    orientation: Union[EnvironmentScreenOrientation, Unset] = field(default=UNSET, metadata={"wire": "orientation"})
    width: Union[int, Unset] = field(default=UNSET, metadata={"wire": "width"})
@dataclass(kw_only=True)
class EnvironmentFonts:
    fallback: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "fallback"})
    monospace: Union[str, Unset] = field(default=UNSET, metadata={"wire": "monospace"})
    sans_serif: Union[str, Unset] = field(default=UNSET, metadata={"wire": "sansSerif"})
    serif: Union[str, Unset] = field(default=UNSET, metadata={"wire": "serif"})
    system: Union[dict[str, str], Unset] = field(default=UNSET, metadata={"wire": "system"})
    system_u_i: Union[str, Unset] = field(default=UNSET, metadata={"wire": "systemUI"})
@dataclass(kw_only=True)
class EnvironmentGPUAdapter:
    architecture: Union[str, Unset] = field(default=UNSET, metadata={"wire": "architecture"})
    description: Union[str, Unset] = field(default=UNSET, metadata={"wire": "description"})
    device: Union[str, Unset] = field(default=UNSET, metadata={"wire": "device"})
    features: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "features"})
    initialization_delay_millis: Union[float, Unset] = field(default=UNSET, metadata={"wire": "initializationDelayMillis"})
    is_fallback_adapter: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "isFallbackAdapter"})
    limits: Union[dict[str, int], Unset] = field(default=UNSET, metadata={"wire": "limits"})
    subgroup_max_size: Union[int, Unset] = field(default=UNSET, metadata={"wire": "subgroupMaxSize"})
    subgroup_min_size: Union[int, Unset] = field(default=UNSET, metadata={"wire": "subgroupMinSize"})
    vendor: Union[str, Unset] = field(default=UNSET, metadata={"wire": "vendor"})
    wgsl_language_features: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "wgslLanguageFeatures"})
@dataclass(kw_only=True)
class EnvironmentGraphics:
    max_texture_size: Union[int, Unset] = field(default=UNSET, metadata={"wire": "maxTextureSize"})
    renderer: Union[str, Unset] = field(default=UNSET, metadata={"wire": "renderer"})
    vendor: Union[str, Unset] = field(default=UNSET, metadata={"wire": "vendor"})
    web_g_l_capabilities_j_s_o_n: Union[str, Unset] = field(default=UNSET, metadata={"wire": "webGLCapabilitiesJSON"})
    web_g_p_u: Union[EnvironmentGPUAdapter, Unset] = field(default=UNSET, metadata={"wire": "webGPU"})
    web_g_p_u_adapters: Union[dict[str, EnvironmentGPUAdapter], Unset] = field(default=UNSET, metadata={"wire": "webGPUAdapters"})
@dataclass(kw_only=True)
class EnvironmentHardware:
    cpu_performance: Union[int, Unset] = field(default=UNSET, metadata={"wire": "cpuPerformance"})
    cpu_performance_known: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "cpuPerformanceKnown"})
    device_memory_g_b: Union[float, Unset] = field(default=UNSET, metadata={"wire": "deviceMemoryGB"})
    logical_processors: Union[int, Unset] = field(default=UNSET, metadata={"wire": "logicalProcessors"})
@dataclass(kw_only=True)
class EnvironmentICEProfile:
    end_delay_millis: Union[float, Unset] = field(default=UNSET, metadata={"wire": "endDelayMillis"})
    host_candidate_count: Union[int, Unset] = field(default=UNSET, metadata={"wire": "hostCandidateCount"})
    host_delay_millis: Union[float, Unset] = field(default=UNSET, metadata={"wire": "hostDelayMillis"})
    network_cost: Union[int, Unset] = field(default=UNSET, metadata={"wire": "networkCost"})
    port_offsets: Union[list[int], Unset] = field(default=UNSET, metadata={"wire": "portOffsets"})
    public_address: Union[str, Unset] = field(default=UNSET, metadata={"wire": "publicAddress"})
    reflexive_candidate_count: Union[int, Unset] = field(default=UNSET, metadata={"wire": "reflexiveCandidateCount"})
    reflexive_delay_millis: Union[float, Unset] = field(default=UNSET, metadata={"wire": "reflexiveDelayMillis"})
    reflexive_port_offsets: Union[list[int], Unset] = field(default=UNSET, metadata={"wire": "reflexivePortOffsets"})
@dataclass(kw_only=True)
class EnvironmentIdentity:
    metadata: Union[EnvironmentUserAgentMetadata, Unset] = field(default=UNSET, metadata={"wire": "metadata"})
    platform: Union[str, Unset] = field(default=UNSET, metadata={"wire": "platform"})
    user_agent: Union[str, Unset] = field(default=UNSET, metadata={"wire": "userAgent"})
@dataclass(kw_only=True)
class EnvironmentLocale:
    intl_locale: Union[str, Unset] = field(default=UNSET, metadata={"wire": "intlLocale"})
    languages: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "languages"})
    reduce_accept_language: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "reduceAcceptLanguage"})
    timezone: Union[str, Unset] = field(default=UNSET, metadata={"wire": "timezone"})
@dataclass(kw_only=True)
class EnvironmentMediaCapabilities:
    formats: Union[EnvironmentMediaFormatCatalog, Unset] = field(default=UNSET, metadata={"wire": "formats"})
    kinds: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "kinds"})
    rtp: Union[dict[str, EnvironmentRTPMediaCatalog], Unset] = field(default=UNSET, metadata={"wire": "rtp"})
    supported_constraints: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "supportedConstraints"})
@dataclass(kw_only=True)
class EnvironmentMediaContainerPolicy:
    codecs: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "codecs"})
    default_codec: Union[str, Unset] = field(default=UNSET, metadata={"wire": "defaultCodec"})
    media_source: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "mediaSource"})
@dataclass(kw_only=True)
class EnvironmentMediaFormatCatalog:
    containers: Union[dict[str, EnvironmentMediaContainerPolicy], Unset] = field(default=UNSET, metadata={"wire": "containers"})
    efficient_video: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "efficientVideo"})
@dataclass(kw_only=True)
class EnvironmentNetwork:
    cookies_enabled: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "cookiesEnabled"})
    downlink_mbps: Union[float, Unset] = field(default=UNSET, metadata={"wire": "downlinkMbps"})
    effective_type: Union[str, Unset] = field(default=UNSET, metadata={"wire": "effectiveType"})
    ice: Union[EnvironmentICEProfile, Unset] = field(default=UNSET, metadata={"wire": "ice"})
    online: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "online"})
    proxy: Union[EnvironmentProxy, Unset] = field(default=UNSET, metadata={"wire": "proxy"})
    rtt_millis: Union[float, Unset] = field(default=UNSET, metadata={"wire": "rttMillis"})
    save_data: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "saveData"})
    wire_profile: Union[str, Unset] = field(default=UNSET, metadata={"wire": "wireProfile"})
@dataclass(kw_only=True)
class EnvironmentPreferences:
    color_scheme: Union[str, Unset] = field(default=UNSET, metadata={"wire": "colorScheme"})
    do_not_track: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "doNotTrack"})
    reduced_motion: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "reducedMotion"})
    system_colors: Union[dict[str, dict[str, str]], Unset] = field(default=UNSET, metadata={"wire": "systemColors"})
@dataclass(kw_only=True)
class EnvironmentProfile:
    audio: Union[EnvironmentAudio, Unset] = field(default=UNSET, metadata={"wire": "audio"})
    base_profile: Union[str, Unset] = field(default=UNSET, metadata={"wire": "baseProfile"})
    capabilities: Union[EnvironmentCapabilities, Unset] = field(default=UNSET, metadata={"wire": "capabilities"})
    display: Union[EnvironmentDisplay, Unset] = field(default=UNSET, metadata={"wire": "display"})
    features: Union[dict[str, bool], Unset] = field(default=UNSET, metadata={"wire": "features"})
    fonts: Union[EnvironmentFonts, Unset] = field(default=UNSET, metadata={"wire": "fonts"})
    graphics: Union[EnvironmentGraphics, Unset] = field(default=UNSET, metadata={"wire": "graphics"})
    hardware: Union[EnvironmentHardware, Unset] = field(default=UNSET, metadata={"wire": "hardware"})
    identity: Union[EnvironmentIdentity, Unset] = field(default=UNSET, metadata={"wire": "identity"})
    locale: Union[EnvironmentLocale, Unset] = field(default=UNSET, metadata={"wire": "locale"})
    network: Union[EnvironmentNetwork, Unset] = field(default=UNSET, metadata={"wire": "network"})
    permissions: Union[dict[str, str], Unset] = field(default=UNSET, metadata={"wire": "permissions"})
    preferences: Union[EnvironmentPreferences, Unset] = field(default=UNSET, metadata={"wire": "preferences"})
    schema_version: Union[int, Unset] = field(default=UNSET, metadata={"wire": "schemaVersion"})
    timing: Union[EnvironmentTiming, Unset] = field(default=UNSET, metadata={"wire": "timing"})
    window: Union[EnvironmentWindow, Unset] = field(default=UNSET, metadata={"wire": "window"})
@dataclass(kw_only=True)
class EnvironmentProxy:
    password: Union[str, Unset] = field(default=UNSET, metadata={"wire": "password"})
    server: Union[str, Unset] = field(default=UNSET, metadata={"wire": "server"})
    username: Union[str, Unset] = field(default=UNSET, metadata={"wire": "username"})
@dataclass(kw_only=True)
class EnvironmentRTPCodec:
    channels: Union[int, Unset] = field(default=UNSET, metadata={"wire": "channels"})
    clock_rate: Union[int, Unset] = field(default=UNSET, metadata={"wire": "clockRate"})
    feedback: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "feedback"})
    name: Union[str, Unset] = field(default=UNSET, metadata={"wire": "name"})
    parameters: Union[str, Unset] = field(default=UNSET, metadata={"wire": "parameters"})
    payload: Union[int, Unset] = field(default=UNSET, metadata={"wire": "payload"})
    redundant: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "redundant"})
    rtx_payload: Union[int, Unset] = field(default=UNSET, metadata={"wire": "rtxPayload"})
    sender_parameters: Union[str, Unset] = field(default=UNSET, metadata={"wire": "senderParameters"})
@dataclass(kw_only=True)
class EnvironmentRTPMediaCatalog:
    codecs: Union[dict[str, EnvironmentRTPCodec], Unset] = field(default=UNSET, metadata={"wire": "codecs"})
    header_extensions: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "headerExtensions"})
    offer_order: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "offerOrder"})
    receiver_order: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "receiverOrder"})
    receiver_r_t_t: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "receiverRTT"})
    sender_order: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "senderOrder"})
@dataclass(kw_only=True)
class EnvironmentScreenOrientation:
    angle: Union[int, Unset] = field(default=UNSET, metadata={"wire": "angle"})
    type: Union[str, Unset] = field(default=UNSET, metadata={"wire": "type"})
@dataclass(kw_only=True)
class EnvironmentTiming:
    execution_scale: Union[float, Unset] = field(default=UNSET, metadata={"wire": "executionScale"})
    navigation_scale: Union[float, Unset] = field(default=UNSET, metadata={"wire": "navigationScale"})
    network_scale: Union[float, Unset] = field(default=UNSET, metadata={"wire": "networkScale"})
@dataclass(kw_only=True)
class EnvironmentUserAgentBrand:
    brand: Union[str, Unset] = field(default=UNSET, metadata={"wire": "brand"})
    full_version: Union[str, Unset] = field(default=UNSET, metadata={"wire": "fullVersion"})
    version: Union[str, Unset] = field(default=UNSET, metadata={"wire": "version"})
@dataclass(kw_only=True)
class EnvironmentUserAgentMetadata:
    architecture: Union[str, Unset] = field(default=UNSET, metadata={"wire": "architecture"})
    bitness: Union[str, Unset] = field(default=UNSET, metadata={"wire": "bitness"})
    brands: Union[list[EnvironmentUserAgentBrand], Unset] = field(default=UNSET, metadata={"wire": "brands"})
    form_factors: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "formFactors"})
    full_version: Union[str, Unset] = field(default=UNSET, metadata={"wire": "fullVersion"})
    full_version_list: Union[list[EnvironmentUserAgentBrand], Unset] = field(default=UNSET, metadata={"wire": "fullVersionList"})
    mobile: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "mobile"})
    model: Union[str, Unset] = field(default=UNSET, metadata={"wire": "model"})
    platform: Union[str, Unset] = field(default=UNSET, metadata={"wire": "platform"})
    platform_version: Union[str, Unset] = field(default=UNSET, metadata={"wire": "platformVersion"})
    wow64: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "wow64"})
@dataclass(kw_only=True)
class EnvironmentWindow:
    outer_height: Union[int, Unset] = field(default=UNSET, metadata={"wire": "outerHeight"})
    outer_width: Union[int, Unset] = field(default=UNSET, metadata={"wire": "outerWidth"})
    viewport_height: Union[int, Unset] = field(default=UNSET, metadata={"wire": "viewportHeight"})
    viewport_width: Union[int, Unset] = field(default=UNSET, metadata={"wire": "viewportWidth"})
    x: Union[int, Unset] = field(default=UNSET, metadata={"wire": "x"})
    y: Union[int, Unset] = field(default=UNSET, metadata={"wire": "y"})
@dataclass(kw_only=True)
class ExecutionStatus:
    elapsed_ms: int = field(metadata={"wire": "elapsedMs"})
    phase: str = field(metadata={"wire": "phase"})
    running: bool = field(metadata={"wire": "running"})
    source: str = field(metadata={"wire": "source"})
    task_id: int = field(metadata={"wire": "taskId"})
@dataclass(kw_only=True)
class ExportProfileParams:
    profile: str = field(metadata={"wire": "profile"})
@dataclass(kw_only=True)
class ExportProfileResult:
    profile: ProfileDescriptor = field(metadata={"wire": "profile"})
    warnings: list[str] = field(metadata={"wire": "warnings"})
@dataclass(kw_only=True)
class GenerateProfileOptions:
    browser: Union[Literal['chrome'], Unset] = field(default=UNSET, metadata={"wire": "browser"})
    platform: Union[Literal['windows'], Unset] = field(default=UNSET, metadata={"wire": "platform"})
    seed: Union[str, Unset] = field(default=UNSET, metadata={"wire": "seed"})
    version: Union[int, Unset] = field(default=UNSET, metadata={"wire": "version"})
@dataclass(kw_only=True)
class GenerateProfileParams:
    browser: Union[Literal['chrome'], Unset] = field(default=UNSET, metadata={"wire": "browser"})
    platform: Union[Literal['windows'], Unset] = field(default=UNSET, metadata={"wire": "platform"})
    seed: Union[str, Unset] = field(default=UNSET, metadata={"wire": "seed"})
    version: Union[int, Unset] = field(default=UNSET, metadata={"wire": "version"})
@dataclass(kw_only=True)
class GenerateProfileResult:
    mode: Literal['generated', 'manual'] = field(metadata={"wire": "mode"})
    profile: str = field(metadata={"wire": "profile"})
    profile_id: str = field(metadata={"wire": "profileId"})
    warnings: list[str] = field(metadata={"wire": "warnings"})
@dataclass(kw_only=True)
class GenerateProfileSelection:
    generate: GenerateProfileOptions = field(metadata={"wire": "generate"})
@dataclass(kw_only=True)
class GetCompatibilityMatrixParams:
    pass
@dataclass(kw_only=True)
class GetCompatibilityMatrixResult:
    chrome_version: str = field(metadata={"wire": "chromeVersion"})
    extensions: list[ProtocolCoverage] = field(metadata={"wire": "extensions"})
    protocol: list[ProtocolCoverage] = field(metadata={"wire": "protocol"})
@dataclass(kw_only=True)
class GetDiagnosticsParams:
    pass
@dataclass(kw_only=True)
class GetDiagnosticsResult:
    enabled: bool = field(metadata={"wire": "enabled"})
    costs: Union[dict[str, DiagnosticCost], Unset] = field(default=UNSET, metadata={"wire": "costs"})
    cpu_profiles: Union[dict[str, JsonValue], Unset] = field(default=UNSET, metadata={"wire": "cpu_profiles"})
    host_only: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "hostOnly"})
    realms: Union[list[RealmDiagnostics], Unset] = field(default=UNSET, metadata={"wire": "realms"})
@dataclass(kw_only=True)
class GetMediaPresetsParams:
    browser_context_id: Union[str, Unset] = field(default=UNSET, metadata={"wire": "browserContextId"})
@dataclass(kw_only=True)
class GetMediaPresetsResult:
    presets: list[MediaPreset] = field(metadata={"wire": "presets"})
@dataclass(kw_only=True)
class GetMediaProfileParams:
    browser_context_id: Union[str, Unset] = field(default=UNSET, metadata={"wire": "browserContextId"})
@dataclass(kw_only=True)
class GetMediaProfileResult:
    diagnostics: dict[str, str] = field(metadata={"wire": "diagnostics"})
    profile: Union[MediaProfile, None] = field(metadata={"wire": "profile"})
@dataclass(kw_only=True)
class GetMediaSourcesParams:
    browser_context_id: Union[str, Unset] = field(default=UNSET, metadata={"wire": "browserContextId"})
@dataclass(kw_only=True)
class GetMediaSourcesResult:
    diagnostics: dict[str, str] = field(metadata={"wire": "diagnostics"})
    sources: list[MediaSource] = field(metadata={"wire": "sources"})
@dataclass(kw_only=True)
class GetProfileParams:
    browser_context_id: Union[str, Unset] = field(default=UNSET, metadata={"wire": "browserContextId"})
    target_id: Union[str, Unset] = field(default=UNSET, metadata={"wire": "targetId"})
@dataclass(kw_only=True)
class GetProfileResult:
    limitations: list[str] = field(metadata={"wire": "limitations"})
    profile: EnvironmentProfile = field(metadata={"wire": "profile"})
@dataclass(kw_only=True)
class GetProfileSchemaParams:
    pass
@dataclass(kw_only=True)
class GetProfileSchemaResult:
    base_profiles: list[str] = field(metadata={"wire": "baseProfiles"})
    limitations: list[str] = field(metadata={"wire": "limitations"})
    schema: dict[str, JsonValue] = field(metadata={"wire": "schema"})
@dataclass(kw_only=True)
class GetResourcePolicyParams:
    browser_context_id: str = field(metadata={"wire": "browserContextId"})
@dataclass(kw_only=True)
class GetResourcePolicyResult:
    enabled: bool = field(metadata={"wire": "enabled"})
    generation: int = field(metadata={"wire": "generation"})
    policy: ResourcePolicy = field(metadata={"wire": "policy"})
@dataclass(kw_only=True)
class GetResourcePolicySchemaParams:
    pass
@dataclass(kw_only=True)
class GetResourcePolicySchemaResult:
    schema: dict[str, JsonValue] = field(metadata={"wire": "schema"})
@dataclass(kw_only=True)
class GetResourcePolicyStatsParams:
    browser_context_id: str = field(metadata={"wire": "browserContextId"})
@dataclass(kw_only=True)
class GetResourcePolicyStatsResult:
    stats: ResourcePolicyStats = field(metadata={"wire": "stats"})
@dataclass(kw_only=True)
class GetStatusParams:
    pass
@dataclass(kw_only=True)
class GetStatusResult:
    execution: ExecutionStatus = field(metadata={"wire": "execution"})
@dataclass(kw_only=True)
class GetTraceParams:
    pass
@dataclass(kw_only=True)
class GetTraceResult:
    crash_reports: dict[str, str] = field(metadata={"wire": "crashReports"})
    events: Union[list[TraceEvent], None] = field(metadata={"wire": "events"})
@dataclass(kw_only=True)
class GetVersionParams:
    pass
@dataclass(kw_only=True)
class GetVersionResult:
    base_profile: str = field(metadata={"wire": "baseProfile"})
    chrome_version: str = field(metadata={"wire": "chromeVersion"})
    version: str = field(metadata={"wire": "version"})
@dataclass(kw_only=True)
class ImportProfileParams:
    profile: Union[ProfileDescriptor, ManualProfile] = field(metadata={"wire": "profile"})
    mode: Union[Literal['manual'], Unset] = field(default=UNSET, metadata={"wire": "mode"})
@dataclass(kw_only=True)
class ImportProfileResult:
    mode: Literal['generated', 'manual'] = field(metadata={"wire": "mode"})
    profile: str = field(metadata={"wire": "profile"})
    profile_id: str = field(metadata={"wire": "profileId"})
    warnings: list[str] = field(metadata={"wire": "warnings"})
@dataclass(kw_only=True)
class ManualNetwork:
    cookies_enabled: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "cookiesEnabled"})
    downlink_mbps: Union[float, Unset] = field(default=UNSET, metadata={"wire": "downlinkMbps"})
    effective_type: Union[str, Unset] = field(default=UNSET, metadata={"wire": "effectiveType"})
    ice: Union[EnvironmentICEProfile, Unset] = field(default=UNSET, metadata={"wire": "ice"})
    online: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "online"})
    rtt_millis: Union[float, Unset] = field(default=UNSET, metadata={"wire": "rttMillis"})
    save_data: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "saveData"})
    wire_profile: Union[str, Unset] = field(default=UNSET, metadata={"wire": "wireProfile"})
@dataclass(kw_only=True)
class ManualProfile:
    audio: Union[EnvironmentAudio, Unset] = field(default=UNSET, metadata={"wire": "audio"})
    capabilities: Union[EnvironmentCapabilities, Unset] = field(default=UNSET, metadata={"wire": "capabilities"})
    display: Union[EnvironmentDisplay, Unset] = field(default=UNSET, metadata={"wire": "display"})
    features: Union[dict[str, bool], Unset] = field(default=UNSET, metadata={"wire": "features"})
    fonts: Union[EnvironmentFonts, Unset] = field(default=UNSET, metadata={"wire": "fonts"})
    graphics: Union[EnvironmentGraphics, Unset] = field(default=UNSET, metadata={"wire": "graphics"})
    hardware: Union[EnvironmentHardware, Unset] = field(default=UNSET, metadata={"wire": "hardware"})
    identity: Union[EnvironmentIdentity, Unset] = field(default=UNSET, metadata={"wire": "identity"})
    locale: Union[EnvironmentLocale, Unset] = field(default=UNSET, metadata={"wire": "locale"})
    network: Union[ManualNetwork, Unset] = field(default=UNSET, metadata={"wire": "network"})
    permissions: Union[dict[str, str], Unset] = field(default=UNSET, metadata={"wire": "permissions"})
    preferences: Union[EnvironmentPreferences, Unset] = field(default=UNSET, metadata={"wire": "preferences"})
    timing: Union[EnvironmentTiming, Unset] = field(default=UNSET, metadata={"wire": "timing"})
    window: Union[EnvironmentWindow, Unset] = field(default=UNSET, metadata={"wire": "window"})
@dataclass(kw_only=True)
class MediaCameraRequest:
    overrides: Union[MediaDeviceOverride, Unset] = field(default=UNSET, metadata={"wire": "overrides"})
    profile: Union[Literal['auto', 'integrated-webcam', 'usb-webcam', 'integrated-webcam-hd', 'integrated-webcam-fhd', 'usb-webcam-hd', 'usb-webcam-fhd'], Unset] = field(default=UNSET, metadata={"wire": "profile"})
    source: Union[MediaSourceSelector, Unset] = field(default=UNSET, metadata={"wire": "source"})
@dataclass(kw_only=True)
class MediaConfiguration:
    camera: Union[MediaCameraRequest, Unset] = field(default=UNSET, metadata={"wire": "camera"})
    devices: Union[list[MediaDeviceProfile], Unset] = field(default=UNSET, metadata={"wire": "devices"})
    microphone: Union[MediaMicrophoneRequest, Unset] = field(default=UNSET, metadata={"wire": "microphone"})
    seed: Union[str, Unset] = field(default=UNSET, metadata={"wire": "seed"})
@dataclass(kw_only=True)
class MediaDeviceOverride:
    default_mode: Union[CameraFormat, Unset] = field(default=UNSET, metadata={"wire": "defaultMode"})
    label: Union[str, Unset] = field(default=UNSET, metadata={"wire": "label"})
    modes: Union[list[CameraFormat], Unset] = field(default=UNSET, metadata={"wire": "modes"})
    processing: Union[MediaProcessing, Unset] = field(default=UNSET, metadata={"wire": "processing"})
@dataclass(kw_only=True)
class MediaDeviceProfile:
    key: str = field(metadata={"wire": "key"})
    kind: Literal['videoinput', 'audioinput'] = field(metadata={"wire": "kind"})
    label: str = field(metadata={"wire": "label"})
    source: MediaSourceSelector = field(metadata={"wire": "source"})
    default_mode: Union[CameraFormat, Unset] = field(default=UNSET, metadata={"wire": "defaultMode"})
    group: Union[str, Unset] = field(default=UNSET, metadata={"wire": "group"})
    modes: Union[list[CameraFormat], Unset] = field(default=UNSET, metadata={"wire": "modes"})
    processing: Union[MediaProcessing, Unset] = field(default=UNSET, metadata={"wire": "processing"})
    profile: Union[str, Unset] = field(default=UNSET, metadata={"wire": "profile"})
@dataclass(kw_only=True)
class MediaMicrophoneRequest:
    profile: Union[Literal['webcam'], Unset] = field(default=UNSET, metadata={"wire": "profile"})
    source: Union[MediaSourceSelector, Unset] = field(default=UNSET, metadata={"wire": "source"})
@dataclass(kw_only=True)
class MediaPreset:
    class_: str = field(metadata={"wire": "class"})
    id: str = field(metadata={"wire": "id"})
    label: str = field(metadata={"wire": "label"})
    variants: list[str] = field(metadata={"wire": "variants"})
@dataclass(kw_only=True)
class MediaProcessing:
    noise: Union[float, Unset] = field(default=UNSET, metadata={"wire": "noise"})
    resize: Union[Literal['none', 'crop-and-scale'], Unset] = field(default=UNSET, metadata={"wire": "resize"})
@dataclass(kw_only=True)
class MediaProfile:
    devices: list[MediaDeviceProfile] = field(metadata={"wire": "devices"})
    seed: str = field(metadata={"wire": "seed"})
@dataclass(kw_only=True)
class MediaSource:
    default: bool = field(metadata={"wire": "default"})
    kind: Literal['videoinput', 'audioinput'] = field(metadata={"wire": "kind"})
    label: str = field(metadata={"wire": "label"})
    source_id: str = field(metadata={"wire": "sourceId"})
@dataclass(kw_only=True)
class PauseParams:
    pass
@dataclass(kw_only=True)
class PauseResult:
    pass
@dataclass(kw_only=True)
class ProfileDescriptor:
    base_profile: str = field(metadata={"wire": "baseProfile"})
    mode: Literal['generated', 'manual'] = field(metadata={"wire": "mode"})
    profile_id: str = field(metadata={"wire": "profileId"})
    environment: Union[ManualProfile, Unset] = field(default=UNSET, metadata={"wire": "environment"})
    seed: Union[str, Unset] = field(default=UNSET, metadata={"wire": "seed"})
@dataclass(kw_only=True)
class ProfileErrorData:
    message: str = field(metadata={"wire": "message"})
    path: str = field(metadata={"wire": "path"})
    reason: str = field(metadata={"wire": "reason"})
@dataclass(kw_only=True)
class ProfilePatch:
    audio: Union[EnvironmentAudio, Unset] = field(default=UNSET, metadata={"wire": "audio"})
    capabilities: Union[EnvironmentCapabilities, Unset] = field(default=UNSET, metadata={"wire": "capabilities"})
    display: Union[EnvironmentDisplay, Unset] = field(default=UNSET, metadata={"wire": "display"})
    features: Union[dict[str, bool], Unset] = field(default=UNSET, metadata={"wire": "features"})
    fonts: Union[EnvironmentFonts, Unset] = field(default=UNSET, metadata={"wire": "fonts"})
    graphics: Union[EnvironmentGraphics, Unset] = field(default=UNSET, metadata={"wire": "graphics"})
    hardware: Union[EnvironmentHardware, Unset] = field(default=UNSET, metadata={"wire": "hardware"})
    identity: Union[EnvironmentIdentity, Unset] = field(default=UNSET, metadata={"wire": "identity"})
    locale: Union[EnvironmentLocale, Unset] = field(default=UNSET, metadata={"wire": "locale"})
    network: Union[ManualNetwork, Unset] = field(default=UNSET, metadata={"wire": "network"})
    permissions: Union[dict[str, str], Unset] = field(default=UNSET, metadata={"wire": "permissions"})
    preferences: Union[EnvironmentPreferences, Unset] = field(default=UNSET, metadata={"wire": "preferences"})
    timing: Union[EnvironmentTiming, Unset] = field(default=UNSET, metadata={"wire": "timing"})
    window: Union[EnvironmentWindow, Unset] = field(default=UNSET, metadata={"wire": "window"})
@dataclass(kw_only=True)
class ProtocolCoverage:
    kind: str = field(metadata={"wire": "kind"})
    name: str = field(metadata={"wire": "name"})
    semantics_implemented: bool = field(metadata={"wire": "semanticsImplemented"})
    semantics_verified: bool = field(metadata={"wire": "semanticsVerified"})
    status: Literal['unsupported', 'partial', 'implemented'] = field(metadata={"wire": "status"})
    surface_registered: bool = field(metadata={"wire": "surfaceRegistered"})
    wire_schema_generated: bool = field(metadata={"wire": "wireSchemaGenerated"})
    notes: Union[str, Unset] = field(default=UNSET, metadata={"wire": "notes"})
    tests: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "tests"})
@dataclass(kw_only=True)
class ProtocolError:
    code: int = field(metadata={"wire": "code"})
    message: str = field(metadata={"wire": "message"})
    data: Union[JsonValue, Unset] = field(default=UNSET, metadata={"wire": "data"})
@dataclass(kw_only=True)
class Proxy:
    password: Union[str, Unset] = field(default=UNSET, metadata={"wire": "password"})
    server: Union[str, Unset] = field(default=UNSET, metadata={"wire": "server"})
    username: Union[str, Unset] = field(default=UNSET, metadata={"wire": "username"})
@dataclass(kw_only=True)
class RealmDiagnostics:
    diagnostics: Diagnostics = field(metadata={"wire": "diagnostics"})
    realm: str = field(metadata={"wire": "realm"})
@dataclass(kw_only=True)
class ResetProfileOverridesParams:
    target_id: str = field(metadata={"wire": "targetId"})
@dataclass(kw_only=True)
class ResetProfileOverridesResult:
    profile: EnvironmentProfile = field(metadata={"wire": "profile"})
@dataclass(kw_only=True)
class ResourceBudgets:
    max_body_bytes: Union[int, Unset] = field(default=UNSET, metadata={"wire": "maxBodyBytes"})
    max_concurrent: Union[int, Unset] = field(default=UNSET, metadata={"wire": "maxConcurrent"})
    max_decoded_bytes: Union[int, Unset] = field(default=UNSET, metadata={"wire": "maxDecodedBytes"})
    max_requests: Union[int, Unset] = field(default=UNSET, metadata={"wire": "maxRequests"})
    max_response_bytes: Union[int, Unset] = field(default=UNSET, metadata={"wire": "maxResponseBytes"})
    max_retained_bytes: Union[int, Unset] = field(default=UNSET, metadata={"wire": "maxRetainedBytes"})
    max_wire_bytes: Union[int, Unset] = field(default=UNSET, metadata={"wire": "maxWireBytes"})
@dataclass(kw_only=True)
class ResourceMatch:
    hosts: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "hosts"})
    kinds: Union[list[Literal['document', 'iframe', 'script', 'stylesheet', 'image', 'font', 'media', 'favicon', 'preload', 'fetch', 'xhr', 'worker', 'websocket', 'other']], Unset] = field(default=UNSET, metadata={"wire": "kinds"})
    mechanisms: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "mechanisms"})
    origins: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "origins"})
    owners: Union[list[str], Unset] = field(default=UNSET, metadata={"wire": "owners"})
    top_level_site: Union[str, Unset] = field(default=UNSET, metadata={"wire": "topLevelSite"})
    url_glob: Union[str, Unset] = field(default=UNSET, metadata={"wire": "urlGlob"})
@dataclass(kw_only=True)
class ResourcePolicy:
    budgets: Union[ResourceBudgets, Unset] = field(default=UNSET, metadata={"wire": "budgets"})
    presets: Union[list[Literal['noVisualAssets', 'headersOnly', 'dataExtraction', 'noSpeculativeLoads']], Unset] = field(default=UNSET, metadata={"wire": "presets"})
    report_only: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "reportOnly"})
    rules: Union[list[ResourceRule], Unset] = field(default=UNSET, metadata={"wire": "rules"})
@dataclass(kw_only=True)
class ResourcePolicyStats:
    blocked: int = field(metadata={"wire": "blocked"})
    body_bytes_consumed: int = field(metadata={"wire": "bodyBytesConsumed"})
    budget_denied: int = field(metadata={"wire": "budgetDenied"})
    by_rule: dict[str, int] = field(metadata={"wire": "byRule"})
    cache_hits: int = field(metadata={"wire": "cacheHits"})
    decoded_pixel_work_bytes: int = field(metadata={"wire": "decodedPixelWorkBytes"})
    encoded_network_body_bytes: int = field(metadata={"wire": "encodedNetworkBodyBytes"})
    generation: int = field(metadata={"wire": "generation"})
    header_only: int = field(metadata={"wire": "headerOnly"})
    known_avoided_body_read_bytes: int = field(metadata={"wire": "knownAvoidedBodyReadBytes"})
    network_acquisitions: int = field(metadata={"wire": "networkAcquisitions"})
    prefixes: int = field(metadata={"wire": "prefixes"})
    requests: int = field(metadata={"wire": "requests"})
    retained_body_bytes: int = field(metadata={"wire": "retainedBodyBytes"})
    unknown_avoided_body_requests: int = field(metadata={"wire": "unknownAvoidedBodyRequests"})
    wire_bytes_known: int = field(metadata={"wire": "wireBytesKnown"})
    would_block: int = field(metadata={"wire": "wouldBlock"})
    would_bypass_cache: int = field(metadata={"wire": "wouldBypassCache"})
@dataclass(kw_only=True)
class ResourceRule:
    id: str = field(metadata={"wire": "id"})
    match: Union[ResourceMatch, Unset] = field(default=UNSET, metadata={"wire": "match"})
    work: Union[ResourceWork, Unset] = field(default=UNSET, metadata={"wire": "work"})
@dataclass(kw_only=True)
class ResourceWork:
    body: Union[Literal['full', 'none', 'prefix'], Unset] = field(default=UNSET, metadata={"wire": "body"})
    cache_read: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "cacheRead"})
    cache_retain: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "cacheRetain"})
    debug_retain: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "debugRetain"})
    decode: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "decode"})
    network: Union[bool, Unset] = field(default=UNSET, metadata={"wire": "network"})
    prefix_bytes: Union[int, Unset] = field(default=UNSET, metadata={"wire": "prefixBytes"})
@dataclass(kw_only=True)
class ResumeParams:
    pass
@dataclass(kw_only=True)
class ResumeResult:
    pass
@dataclass(kw_only=True)
class SetMediaProfileParams:
    browser_context_id: Union[str, Unset] = field(default=UNSET, metadata={"wire": "browserContextId"})
    camera: Union[MediaCameraRequest, Unset] = field(default=UNSET, metadata={"wire": "camera"})
    devices: Union[list[MediaDeviceProfile], Unset] = field(default=UNSET, metadata={"wire": "devices"})
    microphone: Union[MediaMicrophoneRequest, Unset] = field(default=UNSET, metadata={"wire": "microphone"})
    seed: Union[str, Unset] = field(default=UNSET, metadata={"wire": "seed"})
@dataclass(kw_only=True)
class SetMediaProfileResult:
    native_modes_verified: bool = field(metadata={"wire": "nativeModesVerified"})
    profile: MediaProfile = field(metadata={"wire": "profile"})
@dataclass(kw_only=True)
class SetViewportParams:
    height: int = field(metadata={"wire": "height"})
    width: int = field(metadata={"wire": "width"})
@dataclass(kw_only=True)
class SetViewportResult:
    pass
@dataclass(kw_only=True)
class StartTraceParams:
    pass
@dataclass(kw_only=True)
class StartTraceResult:
    pass
@dataclass(kw_only=True)
class StopTraceParams:
    pass
@dataclass(kw_only=True)
class StopTraceResult:
    pass
@dataclass(kw_only=True)
class TraceEvent:
    kind: str = field(metadata={"wire": "kind"})
    name: str = field(metadata={"wire": "name"})
    sequence: int = field(metadata={"wire": "sequence"})
    time: str = field(metadata={"wire": "time"})
    data: Union[dict[str, JsonValue], Unset] = field(default=UNSET, metadata={"wire": "data"})
@dataclass(kw_only=True)
class UpdateProfileParams:
    patch: ProfilePatch = field(metadata={"wire": "patch"})
    target_id: str = field(metadata={"wire": "targetId"})
@dataclass(kw_only=True)
class UpdateProfileResult:
    profile: EnvironmentProfile = field(metadata={"wire": "profile"})
@dataclass(kw_only=True)
class UpdateResourcePolicyParams:
    browser_context_id: str = field(metadata={"wire": "browserContextId"})
    policy: ResourcePolicy = field(metadata={"wire": "policy"})
@dataclass(kw_only=True)
class UpdateResourcePolicyResult:
    generation: int = field(metadata={"wire": "generation"})
@dataclass(kw_only=True)
class ValidateMediaProfileParams:
    browser_context_id: Union[str, Unset] = field(default=UNSET, metadata={"wire": "browserContextId"})
    camera: Union[MediaCameraRequest, Unset] = field(default=UNSET, metadata={"wire": "camera"})
    devices: Union[list[MediaDeviceProfile], Unset] = field(default=UNSET, metadata={"wire": "devices"})
    microphone: Union[MediaMicrophoneRequest, Unset] = field(default=UNSET, metadata={"wire": "microphone"})
    seed: Union[str, Unset] = field(default=UNSET, metadata={"wire": "seed"})
@dataclass(kw_only=True)
class ValidateMediaProfileResult:
    native_modes_verified: bool = field(metadata={"wire": "nativeModesVerified"})
    profile: MediaProfile = field(metadata={"wire": "profile"})
@dataclass(kw_only=True)
class ValidateResourcePolicyParams:
    policy: ResourcePolicy = field(metadata={"wire": "policy"})
@dataclass(kw_only=True)
class ValidateResourcePolicyResult:
    policy: ResourcePolicy = field(metadata={"wire": "policy"})
MediaSourceSelector: TypeAlias = Union[Literal['default', 'obs'], dict[str, JsonValue], dict[str, JsonValue]]
ProfileSelection: TypeAlias = Union[str, GenerateProfileSelection]
class MimicCommands:
    def __init__(self, sender):
        self._sender = sender
    def cancel_execution(self, params: CancelExecutionParams | dict[str, JsonValue] | None = None) -> CancelExecutionResult:
        value = self._sender("Mimic.cancelExecution", to_wire(params) if params is not None else {})
        return from_wire(CancelExecutionResult, value)
    def capture_snapshot(self, params: CaptureSnapshotParams | dict[str, JsonValue] | None = None) -> CaptureSnapshotResult:
        value = self._sender("Mimic.captureSnapshot", to_wire(params) if params is not None else {})
        return from_wire(CaptureSnapshotResult, value)
    def clear_trace(self, params: ClearTraceParams | dict[str, JsonValue] | None = None) -> ClearTraceResult:
        value = self._sender("Mimic.clearTrace", to_wire(params) if params is not None else {})
        return from_wire(ClearTraceResult, value)
    def configure_context(self, params: ConfigureContextParams | dict[str, JsonValue]) -> ConfigureContextResult:
        value = self._sender("Mimic.configureContext", to_wire(params) if params is not None else {})
        return from_wire(ConfigureContextResult, value)
    def create_context(self, params: CreateContextParams | dict[str, JsonValue] | None = None) -> CreateContextResult:
        value = self._sender("Mimic.createContext", to_wire(params) if params is not None else {})
        return from_wire(CreateContextResult, value)
    def export_profile(self, params: ExportProfileParams | dict[str, JsonValue]) -> ExportProfileResult:
        value = self._sender("Mimic.exportProfile", to_wire(params) if params is not None else {})
        return from_wire(ExportProfileResult, value)
    def generate_profile(self, params: GenerateProfileParams | dict[str, JsonValue] | None = None) -> GenerateProfileResult:
        value = self._sender("Mimic.generateProfile", to_wire(params) if params is not None else {})
        return from_wire(GenerateProfileResult, value)
    def get_compatibility_matrix(self, params: GetCompatibilityMatrixParams | dict[str, JsonValue] | None = None) -> GetCompatibilityMatrixResult:
        value = self._sender("Mimic.getCompatibilityMatrix", to_wire(params) if params is not None else {})
        return from_wire(GetCompatibilityMatrixResult, value)
    def get_diagnostics(self, params: GetDiagnosticsParams | dict[str, JsonValue] | None = None) -> GetDiagnosticsResult:
        value = self._sender("Mimic.getDiagnostics", to_wire(params) if params is not None else {})
        return from_wire(GetDiagnosticsResult, value)
    def get_media_presets(self, params: GetMediaPresetsParams | dict[str, JsonValue] | None = None) -> GetMediaPresetsResult:
        value = self._sender("Mimic.getMediaPresets", to_wire(params) if params is not None else {})
        return from_wire(GetMediaPresetsResult, value)
    def get_media_profile(self, params: GetMediaProfileParams | dict[str, JsonValue] | None = None) -> GetMediaProfileResult:
        value = self._sender("Mimic.getMediaProfile", to_wire(params) if params is not None else {})
        return from_wire(GetMediaProfileResult, value)
    def get_media_sources(self, params: GetMediaSourcesParams | dict[str, JsonValue] | None = None) -> GetMediaSourcesResult:
        value = self._sender("Mimic.getMediaSources", to_wire(params) if params is not None else {})
        return from_wire(GetMediaSourcesResult, value)
    def get_profile(self, params: GetProfileParams | dict[str, JsonValue]) -> GetProfileResult:
        value = self._sender("Mimic.getProfile", to_wire(params) if params is not None else {})
        return from_wire(GetProfileResult, value)
    def get_profile_schema(self, params: GetProfileSchemaParams | dict[str, JsonValue] | None = None) -> GetProfileSchemaResult:
        value = self._sender("Mimic.getProfileSchema", to_wire(params) if params is not None else {})
        return from_wire(GetProfileSchemaResult, value)
    def get_resource_policy(self, params: GetResourcePolicyParams | dict[str, JsonValue]) -> GetResourcePolicyResult:
        value = self._sender("Mimic.getResourcePolicy", to_wire(params) if params is not None else {})
        return from_wire(GetResourcePolicyResult, value)
    def get_resource_policy_schema(self, params: GetResourcePolicySchemaParams | dict[str, JsonValue] | None = None) -> GetResourcePolicySchemaResult:
        value = self._sender("Mimic.getResourcePolicySchema", to_wire(params) if params is not None else {})
        return from_wire(GetResourcePolicySchemaResult, value)
    def get_resource_policy_stats(self, params: GetResourcePolicyStatsParams | dict[str, JsonValue]) -> GetResourcePolicyStatsResult:
        value = self._sender("Mimic.getResourcePolicyStats", to_wire(params) if params is not None else {})
        return from_wire(GetResourcePolicyStatsResult, value)
    def get_status(self, params: GetStatusParams | dict[str, JsonValue] | None = None) -> GetStatusResult:
        value = self._sender("Mimic.getStatus", to_wire(params) if params is not None else {})
        return from_wire(GetStatusResult, value)
    def get_trace(self, params: GetTraceParams | dict[str, JsonValue] | None = None) -> GetTraceResult:
        value = self._sender("Mimic.getTrace", to_wire(params) if params is not None else {})
        return from_wire(GetTraceResult, value)
    def get_version(self, params: GetVersionParams | dict[str, JsonValue] | None = None) -> GetVersionResult:
        value = self._sender("Mimic.getVersion", to_wire(params) if params is not None else {})
        return from_wire(GetVersionResult, value)
    def import_profile(self, params: ImportProfileParams | dict[str, JsonValue]) -> ImportProfileResult:
        value = self._sender("Mimic.importProfile", to_wire(params) if params is not None else {})
        return from_wire(ImportProfileResult, value)
    def pause(self, params: PauseParams | dict[str, JsonValue] | None = None) -> PauseResult:
        value = self._sender("Mimic.pause", to_wire(params) if params is not None else {})
        return from_wire(PauseResult, value)
    def reset_profile_overrides(self, params: ResetProfileOverridesParams | dict[str, JsonValue]) -> ResetProfileOverridesResult:
        value = self._sender("Mimic.resetProfileOverrides", to_wire(params) if params is not None else {})
        return from_wire(ResetProfileOverridesResult, value)
    def resume(self, params: ResumeParams | dict[str, JsonValue] | None = None) -> ResumeResult:
        value = self._sender("Mimic.resume", to_wire(params) if params is not None else {})
        return from_wire(ResumeResult, value)
    def set_media_profile(self, params: SetMediaProfileParams | dict[str, JsonValue]) -> SetMediaProfileResult:
        value = self._sender("Mimic.setMediaProfile", to_wire(params) if params is not None else {})
        return from_wire(SetMediaProfileResult, value)
    def set_viewport(self, params: SetViewportParams | dict[str, JsonValue]) -> SetViewportResult:
        value = self._sender("Mimic.setViewport", to_wire(params) if params is not None else {})
        return from_wire(SetViewportResult, value)
    def start_trace(self, params: StartTraceParams | dict[str, JsonValue] | None = None) -> StartTraceResult:
        value = self._sender("Mimic.startTrace", to_wire(params) if params is not None else {})
        return from_wire(StartTraceResult, value)
    def stop_trace(self, params: StopTraceParams | dict[str, JsonValue] | None = None) -> StopTraceResult:
        value = self._sender("Mimic.stopTrace", to_wire(params) if params is not None else {})
        return from_wire(StopTraceResult, value)
    def update_profile(self, params: UpdateProfileParams | dict[str, JsonValue]) -> UpdateProfileResult:
        value = self._sender("Mimic.updateProfile", to_wire(params) if params is not None else {})
        return from_wire(UpdateProfileResult, value)
    def update_resource_policy(self, params: UpdateResourcePolicyParams | dict[str, JsonValue]) -> UpdateResourcePolicyResult:
        value = self._sender("Mimic.updateResourcePolicy", to_wire(params) if params is not None else {})
        return from_wire(UpdateResourcePolicyResult, value)
    def validate_media_profile(self, params: ValidateMediaProfileParams | dict[str, JsonValue]) -> ValidateMediaProfileResult:
        value = self._sender("Mimic.validateMediaProfile", to_wire(params) if params is not None else {})
        return from_wire(ValidateMediaProfileResult, value)
    def validate_resource_policy(self, params: ValidateResourcePolicyParams | dict[str, JsonValue]) -> ValidateResourcePolicyResult:
        value = self._sender("Mimic.validateResourcePolicy", to_wire(params) if params is not None else {})
        return from_wire(ValidateResourcePolicyResult, value)
class AsyncMimicCommands:
    def __init__(self, sender):
        self._sender = sender
    async def cancel_execution(self, params: CancelExecutionParams | dict[str, JsonValue] | None = None) -> CancelExecutionResult:
        value = await self._sender("Mimic.cancelExecution", to_wire(params) if params is not None else {})
        return from_wire(CancelExecutionResult, value)
    async def capture_snapshot(self, params: CaptureSnapshotParams | dict[str, JsonValue] | None = None) -> CaptureSnapshotResult:
        value = await self._sender("Mimic.captureSnapshot", to_wire(params) if params is not None else {})
        return from_wire(CaptureSnapshotResult, value)
    async def clear_trace(self, params: ClearTraceParams | dict[str, JsonValue] | None = None) -> ClearTraceResult:
        value = await self._sender("Mimic.clearTrace", to_wire(params) if params is not None else {})
        return from_wire(ClearTraceResult, value)
    async def configure_context(self, params: ConfigureContextParams | dict[str, JsonValue]) -> ConfigureContextResult:
        value = await self._sender("Mimic.configureContext", to_wire(params) if params is not None else {})
        return from_wire(ConfigureContextResult, value)
    async def create_context(self, params: CreateContextParams | dict[str, JsonValue] | None = None) -> CreateContextResult:
        value = await self._sender("Mimic.createContext", to_wire(params) if params is not None else {})
        return from_wire(CreateContextResult, value)
    async def export_profile(self, params: ExportProfileParams | dict[str, JsonValue]) -> ExportProfileResult:
        value = await self._sender("Mimic.exportProfile", to_wire(params) if params is not None else {})
        return from_wire(ExportProfileResult, value)
    async def generate_profile(self, params: GenerateProfileParams | dict[str, JsonValue] | None = None) -> GenerateProfileResult:
        value = await self._sender("Mimic.generateProfile", to_wire(params) if params is not None else {})
        return from_wire(GenerateProfileResult, value)
    async def get_compatibility_matrix(self, params: GetCompatibilityMatrixParams | dict[str, JsonValue] | None = None) -> GetCompatibilityMatrixResult:
        value = await self._sender("Mimic.getCompatibilityMatrix", to_wire(params) if params is not None else {})
        return from_wire(GetCompatibilityMatrixResult, value)
    async def get_diagnostics(self, params: GetDiagnosticsParams | dict[str, JsonValue] | None = None) -> GetDiagnosticsResult:
        value = await self._sender("Mimic.getDiagnostics", to_wire(params) if params is not None else {})
        return from_wire(GetDiagnosticsResult, value)
    async def get_media_presets(self, params: GetMediaPresetsParams | dict[str, JsonValue] | None = None) -> GetMediaPresetsResult:
        value = await self._sender("Mimic.getMediaPresets", to_wire(params) if params is not None else {})
        return from_wire(GetMediaPresetsResult, value)
    async def get_media_profile(self, params: GetMediaProfileParams | dict[str, JsonValue] | None = None) -> GetMediaProfileResult:
        value = await self._sender("Mimic.getMediaProfile", to_wire(params) if params is not None else {})
        return from_wire(GetMediaProfileResult, value)
    async def get_media_sources(self, params: GetMediaSourcesParams | dict[str, JsonValue] | None = None) -> GetMediaSourcesResult:
        value = await self._sender("Mimic.getMediaSources", to_wire(params) if params is not None else {})
        return from_wire(GetMediaSourcesResult, value)
    async def get_profile(self, params: GetProfileParams | dict[str, JsonValue]) -> GetProfileResult:
        value = await self._sender("Mimic.getProfile", to_wire(params) if params is not None else {})
        return from_wire(GetProfileResult, value)
    async def get_profile_schema(self, params: GetProfileSchemaParams | dict[str, JsonValue] | None = None) -> GetProfileSchemaResult:
        value = await self._sender("Mimic.getProfileSchema", to_wire(params) if params is not None else {})
        return from_wire(GetProfileSchemaResult, value)
    async def get_resource_policy(self, params: GetResourcePolicyParams | dict[str, JsonValue]) -> GetResourcePolicyResult:
        value = await self._sender("Mimic.getResourcePolicy", to_wire(params) if params is not None else {})
        return from_wire(GetResourcePolicyResult, value)
    async def get_resource_policy_schema(self, params: GetResourcePolicySchemaParams | dict[str, JsonValue] | None = None) -> GetResourcePolicySchemaResult:
        value = await self._sender("Mimic.getResourcePolicySchema", to_wire(params) if params is not None else {})
        return from_wire(GetResourcePolicySchemaResult, value)
    async def get_resource_policy_stats(self, params: GetResourcePolicyStatsParams | dict[str, JsonValue]) -> GetResourcePolicyStatsResult:
        value = await self._sender("Mimic.getResourcePolicyStats", to_wire(params) if params is not None else {})
        return from_wire(GetResourcePolicyStatsResult, value)
    async def get_status(self, params: GetStatusParams | dict[str, JsonValue] | None = None) -> GetStatusResult:
        value = await self._sender("Mimic.getStatus", to_wire(params) if params is not None else {})
        return from_wire(GetStatusResult, value)
    async def get_trace(self, params: GetTraceParams | dict[str, JsonValue] | None = None) -> GetTraceResult:
        value = await self._sender("Mimic.getTrace", to_wire(params) if params is not None else {})
        return from_wire(GetTraceResult, value)
    async def get_version(self, params: GetVersionParams | dict[str, JsonValue] | None = None) -> GetVersionResult:
        value = await self._sender("Mimic.getVersion", to_wire(params) if params is not None else {})
        return from_wire(GetVersionResult, value)
    async def import_profile(self, params: ImportProfileParams | dict[str, JsonValue]) -> ImportProfileResult:
        value = await self._sender("Mimic.importProfile", to_wire(params) if params is not None else {})
        return from_wire(ImportProfileResult, value)
    async def pause(self, params: PauseParams | dict[str, JsonValue] | None = None) -> PauseResult:
        value = await self._sender("Mimic.pause", to_wire(params) if params is not None else {})
        return from_wire(PauseResult, value)
    async def reset_profile_overrides(self, params: ResetProfileOverridesParams | dict[str, JsonValue]) -> ResetProfileOverridesResult:
        value = await self._sender("Mimic.resetProfileOverrides", to_wire(params) if params is not None else {})
        return from_wire(ResetProfileOverridesResult, value)
    async def resume(self, params: ResumeParams | dict[str, JsonValue] | None = None) -> ResumeResult:
        value = await self._sender("Mimic.resume", to_wire(params) if params is not None else {})
        return from_wire(ResumeResult, value)
    async def set_media_profile(self, params: SetMediaProfileParams | dict[str, JsonValue]) -> SetMediaProfileResult:
        value = await self._sender("Mimic.setMediaProfile", to_wire(params) if params is not None else {})
        return from_wire(SetMediaProfileResult, value)
    async def set_viewport(self, params: SetViewportParams | dict[str, JsonValue]) -> SetViewportResult:
        value = await self._sender("Mimic.setViewport", to_wire(params) if params is not None else {})
        return from_wire(SetViewportResult, value)
    async def start_trace(self, params: StartTraceParams | dict[str, JsonValue] | None = None) -> StartTraceResult:
        value = await self._sender("Mimic.startTrace", to_wire(params) if params is not None else {})
        return from_wire(StartTraceResult, value)
    async def stop_trace(self, params: StopTraceParams | dict[str, JsonValue] | None = None) -> StopTraceResult:
        value = await self._sender("Mimic.stopTrace", to_wire(params) if params is not None else {})
        return from_wire(StopTraceResult, value)
    async def update_profile(self, params: UpdateProfileParams | dict[str, JsonValue]) -> UpdateProfileResult:
        value = await self._sender("Mimic.updateProfile", to_wire(params) if params is not None else {})
        return from_wire(UpdateProfileResult, value)
    async def update_resource_policy(self, params: UpdateResourcePolicyParams | dict[str, JsonValue]) -> UpdateResourcePolicyResult:
        value = await self._sender("Mimic.updateResourcePolicy", to_wire(params) if params is not None else {})
        return from_wire(UpdateResourcePolicyResult, value)
    async def validate_media_profile(self, params: ValidateMediaProfileParams | dict[str, JsonValue]) -> ValidateMediaProfileResult:
        value = await self._sender("Mimic.validateMediaProfile", to_wire(params) if params is not None else {})
        return from_wire(ValidateMediaProfileResult, value)
    async def validate_resource_policy(self, params: ValidateResourcePolicyParams | dict[str, JsonValue]) -> ValidateResourcePolicyResult:
        value = await self._sender("Mimic.validateResourcePolicy", to_wire(params) if params is not None else {})
        return from_wire(ValidateResourcePolicyResult, value)
