from os import PathLike
from pathlib import Path
from subprocess import Popen
from typing import Literal, TypedDict
from .generated import JsonValue
from .protocol import CDPConnection

PathValue = str | PathLike[str]
Engine = Literal["v8", "quickjs", "goja"]
class RuntimeIdentity(TypedDict):
    version: str
    chromeVersion: str
    baseProfile: str

class RuntimeError(Exception): ...
class RuntimeManager:
    version: str
    def __init__(self, *, runtime_version: str | None = ..., lock: dict[str, JsonValue] | str | Path | None = ..., executable_path: PathValue | None = ..., runtime_dir: PathValue | None = ..., allow_download: bool | None = ..., timeout: float = ...) -> None: ...
    def resolve_lock(self) -> dict[str, JsonValue]: ...
    def install(self, *, archive_path: PathValue | None = ...) -> Path: ...
    def inspect(self) -> list[dict[str, JsonValue]]: ...
    def verify(self) -> Path: ...
    def launch(self, *, engine: Engine = ..., timeout: float | None = ...) -> RuntimeProcess: ...
    def prune(self) -> str: ...
class RuntimeProcess:
    endpoint: str
    identity: RuntimeIdentity
    process: Popen[str]
    connection: CDPConnection
    def __init__(self, binary: PathValue, version: str | None, *, engine: Engine = ..., timeout: float = ...) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> RuntimeProcess: ...
    def __exit__(self, *args: object) -> None: ...
def normalize_version(value: str) -> str: ...
def current_platform() -> str: ...
def validate_lock(lock: dict[str, JsonValue]) -> dict[str, JsonValue]: ...
