// Generated by generator/generate.py; DO NOT EDIT.
// Schema SHA-256: ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export const schemaSha256 = "ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6";
export interface CameraFormat {
  "frameRate": number;
  "height": number;
  "width": number;
}
export interface CancelExecutionParams {
}
export interface CancelExecutionResult {
  "cancelled": boolean;
}
export interface CaptureSnapshotParams {
  "interrupt"?: boolean;
}
export interface CaptureSnapshotResult {
  "files": Record<string, string>;
  "timingsMs": Record<string, number>;
  "url": string;
  "warnings": Array<string>;
}
export interface ClearTraceParams {
}
export interface ClearTraceResult {
}
export interface ConfigureContextParams {
  "browserContextId": string;
  "media"?: MediaConfiguration;
  "profile"?: ProfileSelection;
  "proxy"?: Proxy;
  "resourcePolicy"?: ResourcePolicy;
}
export interface ConfigureContextResult {
  "browserContextId": string;
  "mode": "generated" | "manual";
  "profile": string;
  "profileId": string;
  "warnings": Array<string>;
  "media"?: MediaProfile;
}
export interface CreateContextParams {
  "disposeOnDetach"?: boolean;
  "media"?: MediaConfiguration;
  "profile"?: ProfileSelection;
  "proxy"?: Proxy;
  "resourcePolicy"?: ResourcePolicy;
}
export interface CreateContextResult {
  "browserContextId": string;
  "mode": "generated" | "manual";
  "profile": string;
  "profileId": string;
  "warnings": Array<string>;
  "media"?: MediaProfile;
}
export interface DiagnosticCost {
  "count": number;
  "ns": number;
}
export interface Diagnostics {
  "enabled": boolean;
  "costs"?: Record<string, DiagnosticCost>;
  "cpu_profiles"?: Record<string, JsonValue>;
  "hostOnly"?: boolean;
  "realms"?: Array<RealmDiagnostics>;
}
export interface Empty {
}
export interface EnvironmentAudio {
  "bufferDuration"?: number;
  "channels"?: number;
  "maxBufferFrames"?: number;
  "sampleRate"?: number;
}
export interface EnvironmentCapabilities {
  "devices"?: EnvironmentDeviceCapabilities;
  "keyboardLayout"?: Record<string, string>;
  "media"?: EnvironmentMediaCapabilities;
  "storageQuotaBytes"?: number;
}
export interface EnvironmentDeviceCapabilities {
  "bluetoothAvailable"?: boolean;
  "posture"?: string;
}
export interface EnvironmentDisplay {
  "availableHeight"?: number;
  "availableWidth"?: number;
  "colorDepth"?: number;
  "deviceScaleFactor"?: number;
  "height"?: number;
  "orientation"?: EnvironmentScreenOrientation;
  "width"?: number;
}
export interface EnvironmentFonts {
  "fallback"?: Array<string>;
  "monospace"?: string;
  "sansSerif"?: string;
  "serif"?: string;
  "system"?: Record<string, string>;
  "systemUI"?: string;
}
export interface EnvironmentGPUAdapter {
  "architecture"?: string;
  "description"?: string;
  "device"?: string;
  "features"?: Array<string>;
  "initializationDelayMillis"?: number;
  "isFallbackAdapter"?: boolean;
  "limits"?: Record<string, number>;
  "subgroupMaxSize"?: number;
  "subgroupMinSize"?: number;
  "vendor"?: string;
  "wgslLanguageFeatures"?: Array<string>;
}
export interface EnvironmentGraphics {
  "maxTextureSize"?: number;
  "renderer"?: string;
  "vendor"?: string;
  "webGLCapabilitiesJSON"?: string;
  "webGPU"?: EnvironmentGPUAdapter;
  "webGPUAdapters"?: Record<string, EnvironmentGPUAdapter>;
}
export interface EnvironmentHardware {
  "cpuPerformance"?: number;
  "cpuPerformanceKnown"?: boolean;
  "deviceMemoryGB"?: number;
  "logicalProcessors"?: number;
}
export interface EnvironmentICEProfile {
  "endDelayMillis"?: number;
  "hostCandidateCount"?: number;
  "hostDelayMillis"?: number;
  "networkCost"?: number;
  "portOffsets"?: Array<number>;
  "publicAddress"?: string;
  "reflexiveCandidateCount"?: number;
  "reflexiveDelayMillis"?: number;
  "reflexivePortOffsets"?: Array<number>;
}
export interface EnvironmentIdentity {
  "metadata"?: EnvironmentUserAgentMetadata;
  "platform"?: string;
  "userAgent"?: string;
}
export interface EnvironmentLocale {
  "intlLocale"?: string;
  "languages"?: Array<string>;
  "reduceAcceptLanguage"?: boolean;
  "timezone"?: string;
}
export interface EnvironmentMediaCapabilities {
  "formats"?: EnvironmentMediaFormatCatalog;
  "kinds"?: Array<string>;
  "rtp"?: Record<string, EnvironmentRTPMediaCatalog>;
  "supportedConstraints"?: Array<string>;
}
export interface EnvironmentMediaContainerPolicy {
  "codecs"?: Array<string>;
  "defaultCodec"?: string;
  "mediaSource"?: boolean;
}
export interface EnvironmentMediaFormatCatalog {
  "containers"?: Record<string, EnvironmentMediaContainerPolicy>;
  "efficientVideo"?: Array<string>;
}
export interface EnvironmentNetwork {
  "cookiesEnabled"?: boolean;
  "downlinkMbps"?: number;
  "effectiveType"?: string;
  "ice"?: EnvironmentICEProfile;
  "online"?: boolean;
  "proxy"?: EnvironmentProxy;
  "rttMillis"?: number;
  "saveData"?: boolean;
  "wireProfile"?: string;
}
export interface EnvironmentPreferences {
  "colorScheme"?: string;
  "doNotTrack"?: boolean;
  "reducedMotion"?: boolean;
  "systemColors"?: Record<string, Record<string, string>>;
}
export interface EnvironmentProfile {
  "audio"?: EnvironmentAudio;
  "baseProfile"?: string;
  "capabilities"?: EnvironmentCapabilities;
  "display"?: EnvironmentDisplay;
  "features"?: Record<string, boolean>;
  "fonts"?: EnvironmentFonts;
  "graphics"?: EnvironmentGraphics;
  "hardware"?: EnvironmentHardware;
  "identity"?: EnvironmentIdentity;
  "locale"?: EnvironmentLocale;
  "network"?: EnvironmentNetwork;
  "permissions"?: Record<string, string>;
  "preferences"?: EnvironmentPreferences;
  "schemaVersion"?: number;
  "timing"?: EnvironmentTiming;
  "window"?: EnvironmentWindow;
}
export interface EnvironmentProxy {
  "password"?: string;
  "server"?: string;
  "username"?: string;
}
export interface EnvironmentRTPCodec {
  "channels"?: number;
  "clockRate"?: number;
  "feedback"?: Array<string>;
  "name"?: string;
  "parameters"?: string;
  "payload"?: number;
  "redundant"?: Array<string>;
  "rtxPayload"?: number;
  "senderParameters"?: string;
}
export interface EnvironmentRTPMediaCatalog {
  "codecs"?: Record<string, EnvironmentRTPCodec>;
  "headerExtensions"?: Array<string>;
  "offerOrder"?: Array<string>;
  "receiverOrder"?: Array<string>;
  "receiverRTT"?: boolean;
  "senderOrder"?: Array<string>;
}
export interface EnvironmentScreenOrientation {
  "angle"?: number;
  "type"?: string;
}
export interface EnvironmentTiming {
  "executionScale"?: number;
  "navigationScale"?: number;
  "networkScale"?: number;
}
export interface EnvironmentUserAgentBrand {
  "brand"?: string;
  "fullVersion"?: string;
  "version"?: string;
}
export interface EnvironmentUserAgentMetadata {
  "architecture"?: string;
  "bitness"?: string;
  "brands"?: Array<EnvironmentUserAgentBrand>;
  "formFactors"?: Array<string>;
  "fullVersion"?: string;
  "fullVersionList"?: Array<EnvironmentUserAgentBrand>;
  "mobile"?: boolean;
  "model"?: string;
  "platform"?: string;
  "platformVersion"?: string;
  "wow64"?: boolean;
}
export interface EnvironmentWindow {
  "outerHeight"?: number;
  "outerWidth"?: number;
  "viewportHeight"?: number;
  "viewportWidth"?: number;
  "x"?: number;
  "y"?: number;
}
export interface ExecutionStatus {
  "elapsedMs": number;
  "phase": string;
  "running": boolean;
  "source": string;
  "taskId": number;
}
export interface ExportProfileParams {
  "profile": string;
}
export interface ExportProfileResult {
  "profile": ProfileDescriptor;
  "warnings": Array<string>;
}
export interface GenerateProfileOptions {
  "browser"?: "chrome";
  "platform"?: "windows";
  "seed"?: string;
  "version"?: number;
}
export interface GenerateProfileParams {
  "browser"?: "chrome";
  "platform"?: "windows";
  "seed"?: string;
  "version"?: number;
}
export interface GenerateProfileResult {
  "mode": "generated" | "manual";
  "profile": string;
  "profileId": string;
  "warnings": Array<string>;
}
export interface GenerateProfileSelection {
  "generate": GenerateProfileOptions;
}
export interface GetCompatibilityMatrixParams {
}
export interface GetCompatibilityMatrixResult {
  "chromeVersion": string;
  "extensions": Array<ProtocolCoverage>;
  "protocol": Array<ProtocolCoverage>;
}
export interface GetDiagnosticsParams {
}
export interface GetDiagnosticsResult {
  "enabled": boolean;
  "costs"?: Record<string, DiagnosticCost>;
  "cpu_profiles"?: Record<string, JsonValue>;
  "hostOnly"?: boolean;
  "realms"?: Array<RealmDiagnostics>;
}
export interface GetMediaPresetsParams {
  "browserContextId"?: string;
}
export interface GetMediaPresetsResult {
  "presets": Array<MediaPreset>;
}
export interface GetMediaProfileParams {
  "browserContextId"?: string;
}
export interface GetMediaProfileResult {
  "diagnostics": Record<string, string>;
  "profile": MediaProfile | null;
}
export interface GetMediaSourcesParams {
  "browserContextId"?: string;
}
export interface GetMediaSourcesResult {
  "diagnostics": Record<string, string>;
  "sources": Array<MediaSource>;
}
export interface GetProfileParams {
  "browserContextId"?: string;
  "targetId"?: string;
}
export interface GetProfileResult {
  "limitations": Array<string>;
  "profile": EnvironmentProfile;
}
export interface GetProfileSchemaParams {
}
export interface GetProfileSchemaResult {
  "baseProfiles": Array<string>;
  "limitations": Array<string>;
  "schema": Record<string, JsonValue>;
}
export interface GetResourcePolicyParams {
  "browserContextId": string;
}
export interface GetResourcePolicyResult {
  "enabled": boolean;
  "generation": number;
  "policy": ResourcePolicy;
}
export interface GetResourcePolicySchemaParams {
}
export interface GetResourcePolicySchemaResult {
  "schema": Record<string, JsonValue>;
}
export interface GetResourcePolicyStatsParams {
  "browserContextId": string;
}
export interface GetResourcePolicyStatsResult {
  "stats": ResourcePolicyStats;
}
export interface GetStatusParams {
}
export interface GetStatusResult {
  "execution": ExecutionStatus;
}
export interface GetTraceParams {
}
export interface GetTraceResult {
  "crashReports": Record<string, string>;
  "events": Array<TraceEvent> | null;
}
export interface GetVersionParams {
}
export interface GetVersionResult {
  "baseProfile": string;
  "chromeVersion": string;
  "version": string;
}
export interface ImportProfileParams {
  "profile": ProfileDescriptor | ManualProfile;
  "mode"?: "manual";
}
export interface ImportProfileResult {
  "mode": "generated" | "manual";
  "profile": string;
  "profileId": string;
  "warnings": Array<string>;
}
export interface ManualNetwork {
  "cookiesEnabled"?: boolean;
  "downlinkMbps"?: number;
  "effectiveType"?: string;
  "ice"?: EnvironmentICEProfile;
  "online"?: boolean;
  "rttMillis"?: number;
  "saveData"?: boolean;
  "wireProfile"?: string;
}
export interface ManualProfile {
  "audio"?: EnvironmentAudio;
  "capabilities"?: EnvironmentCapabilities;
  "display"?: EnvironmentDisplay;
  "features"?: Record<string, boolean>;
  "fonts"?: EnvironmentFonts;
  "graphics"?: EnvironmentGraphics;
  "hardware"?: EnvironmentHardware;
  "identity"?: EnvironmentIdentity;
  "locale"?: EnvironmentLocale;
  "network"?: ManualNetwork;
  "permissions"?: Record<string, string>;
  "preferences"?: EnvironmentPreferences;
  "timing"?: EnvironmentTiming;
  "window"?: EnvironmentWindow;
}
export interface MediaCameraRequest {
  "overrides"?: MediaDeviceOverride;
  "profile"?: "auto" | "integrated-webcam" | "usb-webcam" | "integrated-webcam-hd" | "integrated-webcam-fhd" | "usb-webcam-hd" | "usb-webcam-fhd";
  "source"?: MediaSourceSelector;
}
export interface MediaConfiguration {
  "camera"?: MediaCameraRequest;
  "devices"?: Array<MediaDeviceProfile>;
  "microphone"?: MediaMicrophoneRequest;
  "seed"?: string;
}
export interface MediaDeviceOverride {
  "defaultMode"?: CameraFormat;
  "label"?: string;
  "modes"?: Array<CameraFormat>;
  "processing"?: MediaProcessing;
}
export interface MediaDeviceProfile {
  "key": string;
  "kind": "videoinput" | "audioinput";
  "label": string;
  "source": MediaSourceSelector;
  "defaultMode"?: CameraFormat;
  "group"?: string;
  "modes"?: Array<CameraFormat>;
  "processing"?: MediaProcessing;
  "profile"?: string;
}
export interface MediaMicrophoneRequest {
  "profile"?: "webcam";
  "source"?: MediaSourceSelector;
}
export interface MediaPreset {
  "class": string;
  "id": string;
  "label": string;
  "variants": Array<string>;
}
export interface MediaProcessing {
  "noise"?: number;
  "resize"?: "none" | "crop-and-scale";
}
export interface MediaProfile {
  "devices": Array<MediaDeviceProfile>;
  "seed": string;
}
export interface MediaSource {
  "default": boolean;
  "kind": "videoinput" | "audioinput";
  "label": string;
  "sourceId": string;
}
export type MediaSourceSelector = "default" | "obs" | { "sourceId": string } | { "label": string };
export interface PauseParams {
}
export interface PauseResult {
}
export interface ProfileDescriptor {
  "baseProfile": string;
  "mode": "generated" | "manual";
  "profileId": string;
  "environment"?: ManualProfile;
  "seed"?: string;
}
export interface ProfileErrorData {
  "message": string;
  "path": string;
  "reason": string;
}
export interface ProfilePatch {
  "audio"?: EnvironmentAudio;
  "capabilities"?: EnvironmentCapabilities;
  "display"?: EnvironmentDisplay;
  "features"?: Record<string, boolean>;
  "fonts"?: EnvironmentFonts;
  "graphics"?: EnvironmentGraphics;
  "hardware"?: EnvironmentHardware;
  "identity"?: EnvironmentIdentity;
  "locale"?: EnvironmentLocale;
  "network"?: ManualNetwork;
  "permissions"?: Record<string, string>;
  "preferences"?: EnvironmentPreferences;
  "timing"?: EnvironmentTiming;
  "window"?: EnvironmentWindow;
}
export type ProfileSelection = string | GenerateProfileSelection;
export interface ProtocolCoverage {
  "kind": string;
  "name": string;
  "semanticsImplemented": boolean;
  "semanticsVerified": boolean;
  "status": "unsupported" | "partial" | "implemented";
  "surfaceRegistered": boolean;
  "wireSchemaGenerated": boolean;
  "notes"?: string;
  "tests"?: Array<string>;
}
export interface ProtocolError {
  "code": number;
  "message": string;
  "data"?: JsonValue;
}
export interface Proxy {
  "password"?: string;
  "server"?: string;
  "username"?: string;
}
export interface RealmDiagnostics {
  "diagnostics": Diagnostics;
  "realm": string;
}
export interface ResetProfileOverridesParams {
  "targetId": string;
}
export interface ResetProfileOverridesResult {
  "profile": EnvironmentProfile;
}
export interface ResourceBudgets {
  "maxBodyBytes"?: number;
  "maxConcurrent"?: number;
  "maxDecodedBytes"?: number;
  "maxRequests"?: number;
  "maxResponseBytes"?: number;
  "maxRetainedBytes"?: number;
  "maxWireBytes"?: number;
}
export interface ResourceMatch {
  "hosts"?: Array<string>;
  "kinds"?: Array<"document" | "iframe" | "script" | "stylesheet" | "image" | "font" | "media" | "favicon" | "preload" | "fetch" | "xhr" | "worker" | "websocket" | "other">;
  "mechanisms"?: Array<string>;
  "origins"?: Array<string>;
  "owners"?: Array<string>;
  "topLevelSite"?: string;
  "urlGlob"?: string;
}
export interface ResourcePolicy {
  "budgets"?: ResourceBudgets;
  "presets"?: Array<"noVisualAssets" | "headersOnly" | "dataExtraction" | "noSpeculativeLoads">;
  "reportOnly"?: boolean;
  "rules"?: Array<ResourceRule>;
}
export interface ResourcePolicyStats {
  "blocked": number;
  "bodyBytesConsumed": number;
  "budgetDenied": number;
  "byRule": Record<string, number>;
  "cacheHits": number;
  "decodedPixelWorkBytes": number;
  "encodedNetworkBodyBytes": number;
  "generation": number;
  "headerOnly": number;
  "knownAvoidedBodyReadBytes": number;
  "networkAcquisitions": number;
  "prefixes": number;
  "requests": number;
  "retainedBodyBytes": number;
  "unknownAvoidedBodyRequests": number;
  "wireBytesKnown": number;
  "wouldBlock": number;
  "wouldBypassCache": number;
}
export interface ResourceRule {
  "id": string;
  "match"?: ResourceMatch;
  "work"?: ResourceWork;
}
export interface ResourceWork {
  "body"?: "full" | "none" | "prefix";
  "cacheRead"?: boolean;
  "cacheRetain"?: boolean;
  "debugRetain"?: boolean;
  "decode"?: boolean;
  "network"?: boolean;
  "prefixBytes"?: number;
}
export interface ResumeParams {
}
export interface ResumeResult {
}
export interface SetMediaProfileParams {
  "browserContextId"?: string;
  "camera"?: MediaCameraRequest;
  "devices"?: Array<MediaDeviceProfile>;
  "microphone"?: MediaMicrophoneRequest;
  "seed"?: string;
}
export interface SetMediaProfileResult {
  "nativeModesVerified": boolean;
  "profile": MediaProfile;
}
export interface SetViewportParams {
  "height": number;
  "width": number;
}
export interface SetViewportResult {
}
export interface StartTraceParams {
}
export interface StartTraceResult {
}
export interface StopTraceParams {
}
export interface StopTraceResult {
}
export interface TraceEvent {
  "kind": string;
  "name": string;
  "sequence": number;
  "time": string;
  "data"?: Record<string, JsonValue>;
}
export interface UpdateProfileParams {
  "patch": ProfilePatch;
  "targetId": string;
}
export interface UpdateProfileResult {
  "profile": EnvironmentProfile;
}
export interface UpdateResourcePolicyParams {
  "browserContextId": string;
  "policy": ResourcePolicy;
}
export interface UpdateResourcePolicyResult {
  "generation": number;
}
export interface ValidateMediaProfileParams {
  "browserContextId"?: string;
  "camera"?: MediaCameraRequest;
  "devices"?: Array<MediaDeviceProfile>;
  "microphone"?: MediaMicrophoneRequest;
  "seed"?: string;
}
export interface ValidateMediaProfileResult {
  "nativeModesVerified": boolean;
  "profile": MediaProfile;
}
export interface ValidateResourcePolicyParams {
  "policy": ResourcePolicy;
}
export interface ValidateResourcePolicyResult {
  "policy": ResourcePolicy;
}
export interface CommandMap {
  "Mimic.cancelExecution": { params: CancelExecutionParams; result: CancelExecutionResult };
  "Mimic.captureSnapshot": { params: CaptureSnapshotParams; result: CaptureSnapshotResult };
  "Mimic.clearTrace": { params: ClearTraceParams; result: ClearTraceResult };
  "Mimic.configureContext": { params: ConfigureContextParams; result: ConfigureContextResult };
  "Mimic.createContext": { params: CreateContextParams; result: CreateContextResult };
  "Mimic.exportProfile": { params: ExportProfileParams; result: ExportProfileResult };
  "Mimic.generateProfile": { params: GenerateProfileParams; result: GenerateProfileResult };
  "Mimic.getCompatibilityMatrix": { params: GetCompatibilityMatrixParams; result: GetCompatibilityMatrixResult };
  "Mimic.getDiagnostics": { params: GetDiagnosticsParams; result: GetDiagnosticsResult };
  "Mimic.getMediaPresets": { params: GetMediaPresetsParams; result: GetMediaPresetsResult };
  "Mimic.getMediaProfile": { params: GetMediaProfileParams; result: GetMediaProfileResult };
  "Mimic.getMediaSources": { params: GetMediaSourcesParams; result: GetMediaSourcesResult };
  "Mimic.getProfile": { params: GetProfileParams; result: GetProfileResult };
  "Mimic.getProfileSchema": { params: GetProfileSchemaParams; result: GetProfileSchemaResult };
  "Mimic.getResourcePolicy": { params: GetResourcePolicyParams; result: GetResourcePolicyResult };
  "Mimic.getResourcePolicySchema": { params: GetResourcePolicySchemaParams; result: GetResourcePolicySchemaResult };
  "Mimic.getResourcePolicyStats": { params: GetResourcePolicyStatsParams; result: GetResourcePolicyStatsResult };
  "Mimic.getStatus": { params: GetStatusParams; result: GetStatusResult };
  "Mimic.getTrace": { params: GetTraceParams; result: GetTraceResult };
  "Mimic.getVersion": { params: GetVersionParams; result: GetVersionResult };
  "Mimic.importProfile": { params: ImportProfileParams; result: ImportProfileResult };
  "Mimic.pause": { params: PauseParams; result: PauseResult };
  "Mimic.resetProfileOverrides": { params: ResetProfileOverridesParams; result: ResetProfileOverridesResult };
  "Mimic.resume": { params: ResumeParams; result: ResumeResult };
  "Mimic.setMediaProfile": { params: SetMediaProfileParams; result: SetMediaProfileResult };
  "Mimic.setViewport": { params: SetViewportParams; result: SetViewportResult };
  "Mimic.startTrace": { params: StartTraceParams; result: StartTraceResult };
  "Mimic.stopTrace": { params: StopTraceParams; result: StopTraceResult };
  "Mimic.updateProfile": { params: UpdateProfileParams; result: UpdateProfileResult };
  "Mimic.updateResourcePolicy": { params: UpdateResourcePolicyParams; result: UpdateResourcePolicyResult };
  "Mimic.validateMediaProfile": { params: ValidateMediaProfileParams; result: ValidateMediaProfileResult };
  "Mimic.validateResourcePolicy": { params: ValidateResourcePolicyParams; result: ValidateResourcePolicyResult };
}
export class MimicClient {
  constructor(private readonly sender: (method: string, params?: unknown) => Promise<any>) {}
  cancelExecution(params: CancelExecutionParams = {}): Promise<CancelExecutionResult> {
    return this.sender("Mimic.cancelExecution", params);
  }
  captureSnapshot(params: CaptureSnapshotParams = {}): Promise<CaptureSnapshotResult> {
    return this.sender("Mimic.captureSnapshot", params);
  }
  clearTrace(params: ClearTraceParams = {}): Promise<ClearTraceResult> {
    return this.sender("Mimic.clearTrace", params);
  }
  configureContext(params: ConfigureContextParams): Promise<ConfigureContextResult> {
    return this.sender("Mimic.configureContext", params);
  }
  createContext(params: CreateContextParams = {}): Promise<CreateContextResult> {
    return this.sender("Mimic.createContext", params);
  }
  exportProfile(params: ExportProfileParams): Promise<ExportProfileResult> {
    return this.sender("Mimic.exportProfile", params);
  }
  generateProfile(params: GenerateProfileParams = {}): Promise<GenerateProfileResult> {
    return this.sender("Mimic.generateProfile", params);
  }
  getCompatibilityMatrix(params: GetCompatibilityMatrixParams = {}): Promise<GetCompatibilityMatrixResult> {
    return this.sender("Mimic.getCompatibilityMatrix", params);
  }
  getDiagnostics(params: GetDiagnosticsParams = {}): Promise<GetDiagnosticsResult> {
    return this.sender("Mimic.getDiagnostics", params);
  }
  getMediaPresets(params: GetMediaPresetsParams = {}): Promise<GetMediaPresetsResult> {
    return this.sender("Mimic.getMediaPresets", params);
  }
  getMediaProfile(params: GetMediaProfileParams = {}): Promise<GetMediaProfileResult> {
    return this.sender("Mimic.getMediaProfile", params);
  }
  getMediaSources(params: GetMediaSourcesParams = {}): Promise<GetMediaSourcesResult> {
    return this.sender("Mimic.getMediaSources", params);
  }
  getProfile(params: GetProfileParams): Promise<GetProfileResult> {
    return this.sender("Mimic.getProfile", params);
  }
  getProfileSchema(params: GetProfileSchemaParams = {}): Promise<GetProfileSchemaResult> {
    return this.sender("Mimic.getProfileSchema", params);
  }
  getResourcePolicy(params: GetResourcePolicyParams): Promise<GetResourcePolicyResult> {
    return this.sender("Mimic.getResourcePolicy", params);
  }
  getResourcePolicySchema(params: GetResourcePolicySchemaParams = {}): Promise<GetResourcePolicySchemaResult> {
    return this.sender("Mimic.getResourcePolicySchema", params);
  }
  getResourcePolicyStats(params: GetResourcePolicyStatsParams): Promise<GetResourcePolicyStatsResult> {
    return this.sender("Mimic.getResourcePolicyStats", params);
  }
  getStatus(params: GetStatusParams = {}): Promise<GetStatusResult> {
    return this.sender("Mimic.getStatus", params);
  }
  getTrace(params: GetTraceParams = {}): Promise<GetTraceResult> {
    return this.sender("Mimic.getTrace", params);
  }
  getVersion(params: GetVersionParams = {}): Promise<GetVersionResult> {
    return this.sender("Mimic.getVersion", params);
  }
  importProfile(params: ImportProfileParams): Promise<ImportProfileResult> {
    return this.sender("Mimic.importProfile", params);
  }
  pause(params: PauseParams = {}): Promise<PauseResult> {
    return this.sender("Mimic.pause", params);
  }
  resetProfileOverrides(params: ResetProfileOverridesParams): Promise<ResetProfileOverridesResult> {
    return this.sender("Mimic.resetProfileOverrides", params);
  }
  resume(params: ResumeParams = {}): Promise<ResumeResult> {
    return this.sender("Mimic.resume", params);
  }
  setMediaProfile(params: SetMediaProfileParams): Promise<SetMediaProfileResult> {
    return this.sender("Mimic.setMediaProfile", params);
  }
  setViewport(params: SetViewportParams): Promise<SetViewportResult> {
    return this.sender("Mimic.setViewport", params);
  }
  startTrace(params: StartTraceParams = {}): Promise<StartTraceResult> {
    return this.sender("Mimic.startTrace", params);
  }
  stopTrace(params: StopTraceParams = {}): Promise<StopTraceResult> {
    return this.sender("Mimic.stopTrace", params);
  }
  updateProfile(params: UpdateProfileParams): Promise<UpdateProfileResult> {
    return this.sender("Mimic.updateProfile", params);
  }
  updateResourcePolicy(params: UpdateResourcePolicyParams): Promise<UpdateResourcePolicyResult> {
    return this.sender("Mimic.updateResourcePolicy", params);
  }
  validateMediaProfile(params: ValidateMediaProfileParams): Promise<ValidateMediaProfileResult> {
    return this.sender("Mimic.validateMediaProfile", params);
  }
  validateResourcePolicy(params: ValidateResourcePolicyParams): Promise<ValidateResourcePolicyResult> {
    return this.sender("Mimic.validateResourcePolicy", params);
  }
}
