// Generated by generator/generate.py; DO NOT EDIT.
// Schema SHA-256: ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6

package mimic

import (
	"context"
	"encoding/json"
	"fmt"
)

const SchemaSHA256 = "ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6"

// Optional preserves omission and explicit null. Go 1.24's omitzero calls IsZero.
type Optional[T any] struct {
	Value T
	Set   bool
	Null  bool
}

func Some[T any](value T) Optional[T] { return Optional[T]{Value: value, Set: true} }
func Null[T any]() Optional[T]        { return Optional[T]{Set: true, Null: true} }
func (o Optional[T]) IsZero() bool    { return !o.Set }
func (o Optional[T]) MarshalJSON() ([]byte, error) {
	if o.Null {
		return []byte("null"), nil
	}
	if !o.Set {
		return nil, fmt.Errorf("unset field outside an object")
	}
	return json.Marshal(o.Value)
}
func (o *Optional[T]) UnmarshalJSON(data []byte) error {
	o.Set = true
	o.Null = string(data) == "null"
	if o.Null {
		var zero T
		o.Value = zero
		return nil
	}
	return json.Unmarshal(data, &o.Value)
}

type ProtocolSender interface {
	Call(context.Context, string, any, any) error
}
type MimicCommands struct{ Sender ProtocolSender }

type CameraFormat struct {
	FrameRate float64 `json:"frameRate"`
	Height    int64   `json:"height"`
	Width     int64   `json:"width"`
}
type CancelExecutionParams struct {
}
type CancelExecutionResult struct {
	Cancelled bool `json:"cancelled"`
}
type CaptureSnapshotParams struct {
	Interrupt Optional[bool] `json:"interrupt,omitzero"`
}
type CaptureSnapshotResult struct {
	Files     map[string]string `json:"files"`
	TimingsMs map[string]int64  `json:"timingsMs"`
	Url       string            `json:"url"`
	Warnings  []string          `json:"warnings"`
}
type ClearTraceParams struct {
}
type ClearTraceResult struct {
}
type ConfigureContextParams struct {
	BrowserContextId string                       `json:"browserContextId"`
	Media            Optional[MediaConfiguration] `json:"media,omitzero"`
	Profile          Optional[ProfileSelection]   `json:"profile,omitzero"`
	Proxy            Optional[Proxy]              `json:"proxy,omitzero"`
	ResourcePolicy   Optional[ResourcePolicy]     `json:"resourcePolicy,omitzero"`
}
type ConfigureContextResult struct {
	BrowserContextId string                 `json:"browserContextId"`
	Mode             string                 `json:"mode"`
	Profile          string                 `json:"profile"`
	ProfileId        string                 `json:"profileId"`
	Warnings         []string               `json:"warnings"`
	Media            Optional[MediaProfile] `json:"media,omitzero"`
}
type CreateContextParams struct {
	DisposeOnDetach Optional[bool]               `json:"disposeOnDetach,omitzero"`
	Media           Optional[MediaConfiguration] `json:"media,omitzero"`
	Profile         Optional[ProfileSelection]   `json:"profile,omitzero"`
	Proxy           Optional[Proxy]              `json:"proxy,omitzero"`
	ResourcePolicy  Optional[ResourcePolicy]     `json:"resourcePolicy,omitzero"`
}
type CreateContextResult struct {
	BrowserContextId string                 `json:"browserContextId"`
	Mode             string                 `json:"mode"`
	Profile          string                 `json:"profile"`
	ProfileId        string                 `json:"profileId"`
	Warnings         []string               `json:"warnings"`
	Media            Optional[MediaProfile] `json:"media,omitzero"`
}
type DiagnosticCost struct {
	Count int64 `json:"count"`
	Ns    int64 `json:"ns"`
}
type Diagnostics struct {
	Enabled     bool                                 `json:"enabled"`
	Costs       Optional[map[string]DiagnosticCost]  `json:"costs,omitzero"`
	CpuProfiles Optional[map[string]json.RawMessage] `json:"cpu_profiles,omitzero"`
	HostOnly    Optional[bool]                       `json:"hostOnly,omitzero"`
	Realms      Optional[[]RealmDiagnostics]         `json:"realms,omitzero"`
}
type Empty struct {
}
type EnvironmentAudio struct {
	BufferDuration  Optional[float64] `json:"bufferDuration,omitzero"`
	Channels        Optional[int64]   `json:"channels,omitzero"`
	MaxBufferFrames Optional[int64]   `json:"maxBufferFrames,omitzero"`
	SampleRate      Optional[float64] `json:"sampleRate,omitzero"`
}
type EnvironmentCapabilities struct {
	Devices           Optional[EnvironmentDeviceCapabilities] `json:"devices,omitzero"`
	KeyboardLayout    Optional[map[string]string]             `json:"keyboardLayout,omitzero"`
	Media             Optional[EnvironmentMediaCapabilities]  `json:"media,omitzero"`
	StorageQuotaBytes Optional[int64]                         `json:"storageQuotaBytes,omitzero"`
}
type EnvironmentDeviceCapabilities struct {
	BluetoothAvailable Optional[bool]   `json:"bluetoothAvailable,omitzero"`
	Posture            Optional[string] `json:"posture,omitzero"`
}
type EnvironmentDisplay struct {
	AvailableHeight   Optional[int64]                        `json:"availableHeight,omitzero"`
	AvailableWidth    Optional[int64]                        `json:"availableWidth,omitzero"`
	ColorDepth        Optional[int64]                        `json:"colorDepth,omitzero"`
	DeviceScaleFactor Optional[float64]                      `json:"deviceScaleFactor,omitzero"`
	Height            Optional[int64]                        `json:"height,omitzero"`
	Orientation       Optional[EnvironmentScreenOrientation] `json:"orientation,omitzero"`
	Width             Optional[int64]                        `json:"width,omitzero"`
}
type EnvironmentFonts struct {
	Fallback  Optional[[]string]          `json:"fallback,omitzero"`
	Monospace Optional[string]            `json:"monospace,omitzero"`
	SansSerif Optional[string]            `json:"sansSerif,omitzero"`
	Serif     Optional[string]            `json:"serif,omitzero"`
	System    Optional[map[string]string] `json:"system,omitzero"`
	SystemUI  Optional[string]            `json:"systemUI,omitzero"`
}
type EnvironmentGPUAdapter struct {
	Architecture              Optional[string]           `json:"architecture,omitzero"`
	Description               Optional[string]           `json:"description,omitzero"`
	Device                    Optional[string]           `json:"device,omitzero"`
	Features                  Optional[[]string]         `json:"features,omitzero"`
	InitializationDelayMillis Optional[float64]          `json:"initializationDelayMillis,omitzero"`
	IsFallbackAdapter         Optional[bool]             `json:"isFallbackAdapter,omitzero"`
	Limits                    Optional[map[string]int64] `json:"limits,omitzero"`
	SubgroupMaxSize           Optional[int64]            `json:"subgroupMaxSize,omitzero"`
	SubgroupMinSize           Optional[int64]            `json:"subgroupMinSize,omitzero"`
	Vendor                    Optional[string]           `json:"vendor,omitzero"`
	WgslLanguageFeatures      Optional[[]string]         `json:"wgslLanguageFeatures,omitzero"`
}
type EnvironmentGraphics struct {
	MaxTextureSize        Optional[int64]                            `json:"maxTextureSize,omitzero"`
	Renderer              Optional[string]                           `json:"renderer,omitzero"`
	Vendor                Optional[string]                           `json:"vendor,omitzero"`
	WebGLCapabilitiesJSON Optional[string]                           `json:"webGLCapabilitiesJSON,omitzero"`
	WebGPU                Optional[EnvironmentGPUAdapter]            `json:"webGPU,omitzero"`
	WebGPUAdapters        Optional[map[string]EnvironmentGPUAdapter] `json:"webGPUAdapters,omitzero"`
}
type EnvironmentHardware struct {
	CpuPerformance      Optional[int64]   `json:"cpuPerformance,omitzero"`
	CpuPerformanceKnown Optional[bool]    `json:"cpuPerformanceKnown,omitzero"`
	DeviceMemoryGB      Optional[float64] `json:"deviceMemoryGB,omitzero"`
	LogicalProcessors   Optional[int64]   `json:"logicalProcessors,omitzero"`
}
type EnvironmentICEProfile struct {
	EndDelayMillis          Optional[float64] `json:"endDelayMillis,omitzero"`
	HostCandidateCount      Optional[int64]   `json:"hostCandidateCount,omitzero"`
	HostDelayMillis         Optional[float64] `json:"hostDelayMillis,omitzero"`
	NetworkCost             Optional[int64]   `json:"networkCost,omitzero"`
	PortOffsets             Optional[[]int64] `json:"portOffsets,omitzero"`
	PublicAddress           Optional[string]  `json:"publicAddress,omitzero"`
	ReflexiveCandidateCount Optional[int64]   `json:"reflexiveCandidateCount,omitzero"`
	ReflexiveDelayMillis    Optional[float64] `json:"reflexiveDelayMillis,omitzero"`
	ReflexivePortOffsets    Optional[[]int64] `json:"reflexivePortOffsets,omitzero"`
}
type EnvironmentIdentity struct {
	Metadata  Optional[EnvironmentUserAgentMetadata] `json:"metadata,omitzero"`
	Platform  Optional[string]                       `json:"platform,omitzero"`
	UserAgent Optional[string]                       `json:"userAgent,omitzero"`
}
type EnvironmentLocale struct {
	IntlLocale           Optional[string]   `json:"intlLocale,omitzero"`
	Languages            Optional[[]string] `json:"languages,omitzero"`
	ReduceAcceptLanguage Optional[bool]     `json:"reduceAcceptLanguage,omitzero"`
	Timezone             Optional[string]   `json:"timezone,omitzero"`
}
type EnvironmentMediaCapabilities struct {
	Formats              Optional[EnvironmentMediaFormatCatalog]         `json:"formats,omitzero"`
	Kinds                Optional[[]string]                              `json:"kinds,omitzero"`
	Rtp                  Optional[map[string]EnvironmentRTPMediaCatalog] `json:"rtp,omitzero"`
	SupportedConstraints Optional[[]string]                              `json:"supportedConstraints,omitzero"`
}
type EnvironmentMediaContainerPolicy struct {
	Codecs       Optional[[]string] `json:"codecs,omitzero"`
	DefaultCodec Optional[string]   `json:"defaultCodec,omitzero"`
	MediaSource  Optional[bool]     `json:"mediaSource,omitzero"`
}
type EnvironmentMediaFormatCatalog struct {
	Containers     Optional[map[string]EnvironmentMediaContainerPolicy] `json:"containers,omitzero"`
	EfficientVideo Optional[[]string]                                   `json:"efficientVideo,omitzero"`
}
type EnvironmentNetwork struct {
	CookiesEnabled Optional[bool]                  `json:"cookiesEnabled,omitzero"`
	DownlinkMbps   Optional[float64]               `json:"downlinkMbps,omitzero"`
	EffectiveType  Optional[string]                `json:"effectiveType,omitzero"`
	Ice            Optional[EnvironmentICEProfile] `json:"ice,omitzero"`
	Online         Optional[bool]                  `json:"online,omitzero"`
	Proxy          Optional[EnvironmentProxy]      `json:"proxy,omitzero"`
	RttMillis      Optional[float64]               `json:"rttMillis,omitzero"`
	SaveData       Optional[bool]                  `json:"saveData,omitzero"`
	WireProfile    Optional[string]                `json:"wireProfile,omitzero"`
}
type EnvironmentPreferences struct {
	ColorScheme   Optional[string]                       `json:"colorScheme,omitzero"`
	DoNotTrack    Optional[bool]                         `json:"doNotTrack,omitzero"`
	ReducedMotion Optional[bool]                         `json:"reducedMotion,omitzero"`
	SystemColors  Optional[map[string]map[string]string] `json:"systemColors,omitzero"`
}
type EnvironmentProfile struct {
	Audio         Optional[EnvironmentAudio]        `json:"audio,omitzero"`
	BaseProfile   Optional[string]                  `json:"baseProfile,omitzero"`
	Capabilities  Optional[EnvironmentCapabilities] `json:"capabilities,omitzero"`
	Display       Optional[EnvironmentDisplay]      `json:"display,omitzero"`
	Features      Optional[map[string]bool]         `json:"features,omitzero"`
	Fonts         Optional[EnvironmentFonts]        `json:"fonts,omitzero"`
	Graphics      Optional[EnvironmentGraphics]     `json:"graphics,omitzero"`
	Hardware      Optional[EnvironmentHardware]     `json:"hardware,omitzero"`
	Identity      Optional[EnvironmentIdentity]     `json:"identity,omitzero"`
	Locale        Optional[EnvironmentLocale]       `json:"locale,omitzero"`
	Network       Optional[EnvironmentNetwork]      `json:"network,omitzero"`
	Permissions   Optional[map[string]string]       `json:"permissions,omitzero"`
	Preferences   Optional[EnvironmentPreferences]  `json:"preferences,omitzero"`
	SchemaVersion Optional[int64]                   `json:"schemaVersion,omitzero"`
	Timing        Optional[EnvironmentTiming]       `json:"timing,omitzero"`
	Window        Optional[EnvironmentWindow]       `json:"window,omitzero"`
}
type EnvironmentProxy struct {
	Password Optional[string] `json:"password,omitzero"`
	Server   Optional[string] `json:"server,omitzero"`
	Username Optional[string] `json:"username,omitzero"`
}
type EnvironmentRTPCodec struct {
	Channels         Optional[int64]    `json:"channels,omitzero"`
	ClockRate        Optional[int64]    `json:"clockRate,omitzero"`
	Feedback         Optional[[]string] `json:"feedback,omitzero"`
	Name             Optional[string]   `json:"name,omitzero"`
	Parameters       Optional[string]   `json:"parameters,omitzero"`
	Payload          Optional[int64]    `json:"payload,omitzero"`
	Redundant        Optional[[]string] `json:"redundant,omitzero"`
	RtxPayload       Optional[int64]    `json:"rtxPayload,omitzero"`
	SenderParameters Optional[string]   `json:"senderParameters,omitzero"`
}
type EnvironmentRTPMediaCatalog struct {
	Codecs           Optional[map[string]EnvironmentRTPCodec] `json:"codecs,omitzero"`
	HeaderExtensions Optional[[]string]                       `json:"headerExtensions,omitzero"`
	OfferOrder       Optional[[]string]                       `json:"offerOrder,omitzero"`
	ReceiverOrder    Optional[[]string]                       `json:"receiverOrder,omitzero"`
	ReceiverRTT      Optional[bool]                           `json:"receiverRTT,omitzero"`
	SenderOrder      Optional[[]string]                       `json:"senderOrder,omitzero"`
}
type EnvironmentScreenOrientation struct {
	Angle Optional[int64]  `json:"angle,omitzero"`
	Type  Optional[string] `json:"type,omitzero"`
}
type EnvironmentTiming struct {
	ExecutionScale  Optional[float64] `json:"executionScale,omitzero"`
	NavigationScale Optional[float64] `json:"navigationScale,omitzero"`
	NetworkScale    Optional[float64] `json:"networkScale,omitzero"`
}
type EnvironmentUserAgentBrand struct {
	Brand       Optional[string] `json:"brand,omitzero"`
	FullVersion Optional[string] `json:"fullVersion,omitzero"`
	Version     Optional[string] `json:"version,omitzero"`
}
type EnvironmentUserAgentMetadata struct {
	Architecture    Optional[string]                      `json:"architecture,omitzero"`
	Bitness         Optional[string]                      `json:"bitness,omitzero"`
	Brands          Optional[[]EnvironmentUserAgentBrand] `json:"brands,omitzero"`
	FormFactors     Optional[[]string]                    `json:"formFactors,omitzero"`
	FullVersion     Optional[string]                      `json:"fullVersion,omitzero"`
	FullVersionList Optional[[]EnvironmentUserAgentBrand] `json:"fullVersionList,omitzero"`
	Mobile          Optional[bool]                        `json:"mobile,omitzero"`
	Model           Optional[string]                      `json:"model,omitzero"`
	Platform        Optional[string]                      `json:"platform,omitzero"`
	PlatformVersion Optional[string]                      `json:"platformVersion,omitzero"`
	Wow64           Optional[bool]                        `json:"wow64,omitzero"`
}
type EnvironmentWindow struct {
	OuterHeight    Optional[int64] `json:"outerHeight,omitzero"`
	OuterWidth     Optional[int64] `json:"outerWidth,omitzero"`
	ViewportHeight Optional[int64] `json:"viewportHeight,omitzero"`
	ViewportWidth  Optional[int64] `json:"viewportWidth,omitzero"`
	X              Optional[int64] `json:"x,omitzero"`
	Y              Optional[int64] `json:"y,omitzero"`
}
type ExecutionStatus struct {
	ElapsedMs int64  `json:"elapsedMs"`
	Phase     string `json:"phase"`
	Running   bool   `json:"running"`
	Source    string `json:"source"`
	TaskId    int64  `json:"taskId"`
}
type ExportProfileParams struct {
	Profile string `json:"profile"`
}
type ExportProfileResult struct {
	Profile  ProfileDescriptor `json:"profile"`
	Warnings []string          `json:"warnings"`
}
type GenerateProfileOptions struct {
	Browser  Optional[string] `json:"browser,omitzero"`
	Platform Optional[string] `json:"platform,omitzero"`
	Seed     Optional[string] `json:"seed,omitzero"`
	Version  Optional[int64]  `json:"version,omitzero"`
}
type GenerateProfileParams struct {
	Browser  Optional[string] `json:"browser,omitzero"`
	Platform Optional[string] `json:"platform,omitzero"`
	Seed     Optional[string] `json:"seed,omitzero"`
	Version  Optional[int64]  `json:"version,omitzero"`
}
type GenerateProfileResult struct {
	Mode      string   `json:"mode"`
	Profile   string   `json:"profile"`
	ProfileId string   `json:"profileId"`
	Warnings  []string `json:"warnings"`
}
type GenerateProfileSelection struct {
	Generate GenerateProfileOptions `json:"generate"`
}
type GetCompatibilityMatrixParams struct {
}
type GetCompatibilityMatrixResult struct {
	ChromeVersion string             `json:"chromeVersion"`
	Extensions    []ProtocolCoverage `json:"extensions"`
	Protocol      []ProtocolCoverage `json:"protocol"`
}
type GetDiagnosticsParams struct {
}
type GetDiagnosticsResult struct {
	Enabled     bool                                 `json:"enabled"`
	Costs       Optional[map[string]DiagnosticCost]  `json:"costs,omitzero"`
	CpuProfiles Optional[map[string]json.RawMessage] `json:"cpu_profiles,omitzero"`
	HostOnly    Optional[bool]                       `json:"hostOnly,omitzero"`
	Realms      Optional[[]RealmDiagnostics]         `json:"realms,omitzero"`
}
type GetMediaPresetsParams struct {
	BrowserContextId Optional[string] `json:"browserContextId,omitzero"`
}
type GetMediaPresetsResult struct {
	Presets []MediaPreset `json:"presets"`
}
type GetMediaProfileParams struct {
	BrowserContextId Optional[string] `json:"browserContextId,omitzero"`
}
type GetMediaProfileResult struct {
	Diagnostics map[string]string `json:"diagnostics"`
	Profile     *MediaProfile     `json:"profile"`
}
type GetMediaSourcesParams struct {
	BrowserContextId Optional[string] `json:"browserContextId,omitzero"`
}
type GetMediaSourcesResult struct {
	Diagnostics map[string]string `json:"diagnostics"`
	Sources     []MediaSource     `json:"sources"`
}
type GetProfileParams struct {
	BrowserContextId Optional[string] `json:"browserContextId,omitzero"`
	TargetId         Optional[string] `json:"targetId,omitzero"`
}
type GetProfileResult struct {
	Limitations []string           `json:"limitations"`
	Profile     EnvironmentProfile `json:"profile"`
}
type GetProfileSchemaParams struct {
}
type GetProfileSchemaResult struct {
	BaseProfiles []string                   `json:"baseProfiles"`
	Limitations  []string                   `json:"limitations"`
	Schema       map[string]json.RawMessage `json:"schema"`
}
type GetResourcePolicyParams struct {
	BrowserContextId string `json:"browserContextId"`
}
type GetResourcePolicyResult struct {
	Enabled    bool           `json:"enabled"`
	Generation int64          `json:"generation"`
	Policy     ResourcePolicy `json:"policy"`
}
type GetResourcePolicySchemaParams struct {
}
type GetResourcePolicySchemaResult struct {
	Schema map[string]json.RawMessage `json:"schema"`
}
type GetResourcePolicyStatsParams struct {
	BrowserContextId string `json:"browserContextId"`
}
type GetResourcePolicyStatsResult struct {
	Stats ResourcePolicyStats `json:"stats"`
}
type GetStatusParams struct {
}
type GetStatusResult struct {
	Execution ExecutionStatus `json:"execution"`
}
type GetTraceParams struct {
}
type GetTraceResult struct {
	CrashReports map[string]string `json:"crashReports"`
	Events       *[]TraceEvent     `json:"events"`
}
type GetVersionParams struct {
}
type GetVersionResult struct {
	BaseProfile   string `json:"baseProfile"`
	ChromeVersion string `json:"chromeVersion"`
	Version       string `json:"version"`
}
type ImportProfileParams struct {
	Profile json.RawMessage  `json:"profile"`
	Mode    Optional[string] `json:"mode,omitzero"`
}
type ImportProfileResult struct {
	Mode      string   `json:"mode"`
	Profile   string   `json:"profile"`
	ProfileId string   `json:"profileId"`
	Warnings  []string `json:"warnings"`
}
type ManualNetwork struct {
	CookiesEnabled Optional[bool]                  `json:"cookiesEnabled,omitzero"`
	DownlinkMbps   Optional[float64]               `json:"downlinkMbps,omitzero"`
	EffectiveType  Optional[string]                `json:"effectiveType,omitzero"`
	Ice            Optional[EnvironmentICEProfile] `json:"ice,omitzero"`
	Online         Optional[bool]                  `json:"online,omitzero"`
	RttMillis      Optional[float64]               `json:"rttMillis,omitzero"`
	SaveData       Optional[bool]                  `json:"saveData,omitzero"`
	WireProfile    Optional[string]                `json:"wireProfile,omitzero"`
}
type ManualProfile struct {
	Audio        Optional[EnvironmentAudio]        `json:"audio,omitzero"`
	Capabilities Optional[EnvironmentCapabilities] `json:"capabilities,omitzero"`
	Display      Optional[EnvironmentDisplay]      `json:"display,omitzero"`
	Features     Optional[map[string]bool]         `json:"features,omitzero"`
	Fonts        Optional[EnvironmentFonts]        `json:"fonts,omitzero"`
	Graphics     Optional[EnvironmentGraphics]     `json:"graphics,omitzero"`
	Hardware     Optional[EnvironmentHardware]     `json:"hardware,omitzero"`
	Identity     Optional[EnvironmentIdentity]     `json:"identity,omitzero"`
	Locale       Optional[EnvironmentLocale]       `json:"locale,omitzero"`
	Network      Optional[ManualNetwork]           `json:"network,omitzero"`
	Permissions  Optional[map[string]string]       `json:"permissions,omitzero"`
	Preferences  Optional[EnvironmentPreferences]  `json:"preferences,omitzero"`
	Timing       Optional[EnvironmentTiming]       `json:"timing,omitzero"`
	Window       Optional[EnvironmentWindow]       `json:"window,omitzero"`
}
type MediaCameraRequest struct {
	Overrides Optional[MediaDeviceOverride] `json:"overrides,omitzero"`
	Profile   Optional[string]              `json:"profile,omitzero"`
	Source    Optional[MediaSourceSelector] `json:"source,omitzero"`
}
type MediaConfiguration struct {
	Camera     Optional[MediaCameraRequest]     `json:"camera,omitzero"`
	Devices    Optional[[]MediaDeviceProfile]   `json:"devices,omitzero"`
	Microphone Optional[MediaMicrophoneRequest] `json:"microphone,omitzero"`
	Seed       Optional[string]                 `json:"seed,omitzero"`
}
type MediaDeviceOverride struct {
	DefaultMode Optional[CameraFormat]    `json:"defaultMode,omitzero"`
	Label       Optional[string]          `json:"label,omitzero"`
	Modes       Optional[[]CameraFormat]  `json:"modes,omitzero"`
	Processing  Optional[MediaProcessing] `json:"processing,omitzero"`
}
type MediaDeviceProfile struct {
	Key         string                    `json:"key"`
	Kind        string                    `json:"kind"`
	Label       string                    `json:"label"`
	Source      MediaSourceSelector       `json:"source"`
	DefaultMode Optional[CameraFormat]    `json:"defaultMode,omitzero"`
	Group       Optional[string]          `json:"group,omitzero"`
	Modes       Optional[[]CameraFormat]  `json:"modes,omitzero"`
	Processing  Optional[MediaProcessing] `json:"processing,omitzero"`
	Profile     Optional[string]          `json:"profile,omitzero"`
}
type MediaMicrophoneRequest struct {
	Profile Optional[string]              `json:"profile,omitzero"`
	Source  Optional[MediaSourceSelector] `json:"source,omitzero"`
}
type MediaPreset struct {
	Class    string   `json:"class"`
	Id       string   `json:"id"`
	Label    string   `json:"label"`
	Variants []string `json:"variants"`
}
type MediaProcessing struct {
	Noise  Optional[float64] `json:"noise,omitzero"`
	Resize Optional[string]  `json:"resize,omitzero"`
}
type MediaProfile struct {
	Devices []MediaDeviceProfile `json:"devices"`
	Seed    string               `json:"seed"`
}
type MediaSource struct {
	Default  bool   `json:"default"`
	Kind     string `json:"kind"`
	Label    string `json:"label"`
	SourceId string `json:"sourceId"`
}
type MediaSourceSelector = json.RawMessage
type PauseParams struct {
}
type PauseResult struct {
}
type ProfileDescriptor struct {
	BaseProfile string                  `json:"baseProfile"`
	Mode        string                  `json:"mode"`
	ProfileId   string                  `json:"profileId"`
	Environment Optional[ManualProfile] `json:"environment,omitzero"`
	Seed        Optional[string]        `json:"seed,omitzero"`
}
type ProfileErrorData struct {
	Message string `json:"message"`
	Path    string `json:"path"`
	Reason  string `json:"reason"`
}
type ProfilePatch struct {
	Audio        Optional[EnvironmentAudio]        `json:"audio,omitzero"`
	Capabilities Optional[EnvironmentCapabilities] `json:"capabilities,omitzero"`
	Display      Optional[EnvironmentDisplay]      `json:"display,omitzero"`
	Features     Optional[map[string]bool]         `json:"features,omitzero"`
	Fonts        Optional[EnvironmentFonts]        `json:"fonts,omitzero"`
	Graphics     Optional[EnvironmentGraphics]     `json:"graphics,omitzero"`
	Hardware     Optional[EnvironmentHardware]     `json:"hardware,omitzero"`
	Identity     Optional[EnvironmentIdentity]     `json:"identity,omitzero"`
	Locale       Optional[EnvironmentLocale]       `json:"locale,omitzero"`
	Network      Optional[ManualNetwork]           `json:"network,omitzero"`
	Permissions  Optional[map[string]string]       `json:"permissions,omitzero"`
	Preferences  Optional[EnvironmentPreferences]  `json:"preferences,omitzero"`
	Timing       Optional[EnvironmentTiming]       `json:"timing,omitzero"`
	Window       Optional[EnvironmentWindow]       `json:"window,omitzero"`
}
type ProfileSelection = json.RawMessage
type ProtocolCoverage struct {
	Kind                 string             `json:"kind"`
	Name                 string             `json:"name"`
	SemanticsImplemented bool               `json:"semanticsImplemented"`
	SemanticsVerified    bool               `json:"semanticsVerified"`
	Status               string             `json:"status"`
	SurfaceRegistered    bool               `json:"surfaceRegistered"`
	WireSchemaGenerated  bool               `json:"wireSchemaGenerated"`
	Notes                Optional[string]   `json:"notes,omitzero"`
	Tests                Optional[[]string] `json:"tests,omitzero"`
}
type ProtocolError struct {
	Code    int64                     `json:"code"`
	Message string                    `json:"message"`
	Data    Optional[json.RawMessage] `json:"data,omitzero"`
}
type Proxy struct {
	Password Optional[string] `json:"password,omitzero"`
	Server   Optional[string] `json:"server,omitzero"`
	Username Optional[string] `json:"username,omitzero"`
}
type RealmDiagnostics struct {
	Diagnostics Diagnostics `json:"diagnostics"`
	Realm       string      `json:"realm"`
}
type ResetProfileOverridesParams struct {
	TargetId string `json:"targetId"`
}
type ResetProfileOverridesResult struct {
	Profile EnvironmentProfile `json:"profile"`
}
type ResourceBudgets struct {
	MaxBodyBytes     Optional[int64] `json:"maxBodyBytes,omitzero"`
	MaxConcurrent    Optional[int64] `json:"maxConcurrent,omitzero"`
	MaxDecodedBytes  Optional[int64] `json:"maxDecodedBytes,omitzero"`
	MaxRequests      Optional[int64] `json:"maxRequests,omitzero"`
	MaxResponseBytes Optional[int64] `json:"maxResponseBytes,omitzero"`
	MaxRetainedBytes Optional[int64] `json:"maxRetainedBytes,omitzero"`
	MaxWireBytes     Optional[int64] `json:"maxWireBytes,omitzero"`
}
type ResourceMatch struct {
	Hosts        Optional[[]string] `json:"hosts,omitzero"`
	Kinds        Optional[[]string] `json:"kinds,omitzero"`
	Mechanisms   Optional[[]string] `json:"mechanisms,omitzero"`
	Origins      Optional[[]string] `json:"origins,omitzero"`
	Owners       Optional[[]string] `json:"owners,omitzero"`
	TopLevelSite Optional[string]   `json:"topLevelSite,omitzero"`
	UrlGlob      Optional[string]   `json:"urlGlob,omitzero"`
}
type ResourcePolicy struct {
	Budgets    Optional[ResourceBudgets] `json:"budgets,omitzero"`
	Presets    Optional[[]string]        `json:"presets,omitzero"`
	ReportOnly Optional[bool]            `json:"reportOnly,omitzero"`
	Rules      Optional[[]ResourceRule]  `json:"rules,omitzero"`
}
type ResourcePolicyStats struct {
	Blocked                    int64            `json:"blocked"`
	BodyBytesConsumed          int64            `json:"bodyBytesConsumed"`
	BudgetDenied               int64            `json:"budgetDenied"`
	ByRule                     map[string]int64 `json:"byRule"`
	CacheHits                  int64            `json:"cacheHits"`
	DecodedPixelWorkBytes      int64            `json:"decodedPixelWorkBytes"`
	EncodedNetworkBodyBytes    int64            `json:"encodedNetworkBodyBytes"`
	Generation                 int64            `json:"generation"`
	HeaderOnly                 int64            `json:"headerOnly"`
	KnownAvoidedBodyReadBytes  int64            `json:"knownAvoidedBodyReadBytes"`
	NetworkAcquisitions        int64            `json:"networkAcquisitions"`
	Prefixes                   int64            `json:"prefixes"`
	Requests                   int64            `json:"requests"`
	RetainedBodyBytes          int64            `json:"retainedBodyBytes"`
	UnknownAvoidedBodyRequests int64            `json:"unknownAvoidedBodyRequests"`
	WireBytesKnown             int64            `json:"wireBytesKnown"`
	WouldBlock                 int64            `json:"wouldBlock"`
	WouldBypassCache           int64            `json:"wouldBypassCache"`
}
type ResourceRule struct {
	Id    string                  `json:"id"`
	Match Optional[ResourceMatch] `json:"match,omitzero"`
	Work  Optional[ResourceWork]  `json:"work,omitzero"`
}
type ResourceWork struct {
	Body        Optional[string] `json:"body,omitzero"`
	CacheRead   Optional[bool]   `json:"cacheRead,omitzero"`
	CacheRetain Optional[bool]   `json:"cacheRetain,omitzero"`
	DebugRetain Optional[bool]   `json:"debugRetain,omitzero"`
	Decode      Optional[bool]   `json:"decode,omitzero"`
	Network     Optional[bool]   `json:"network,omitzero"`
	PrefixBytes Optional[int64]  `json:"prefixBytes,omitzero"`
}
type ResumeParams struct {
}
type ResumeResult struct {
}
type SetMediaProfileParams struct {
	BrowserContextId Optional[string]                 `json:"browserContextId,omitzero"`
	Camera           Optional[MediaCameraRequest]     `json:"camera,omitzero"`
	Devices          Optional[[]MediaDeviceProfile]   `json:"devices,omitzero"`
	Microphone       Optional[MediaMicrophoneRequest] `json:"microphone,omitzero"`
	Seed             Optional[string]                 `json:"seed,omitzero"`
}
type SetMediaProfileResult struct {
	NativeModesVerified bool         `json:"nativeModesVerified"`
	Profile             MediaProfile `json:"profile"`
}
type SetViewportParams struct {
	Height int64 `json:"height"`
	Width  int64 `json:"width"`
}
type SetViewportResult struct {
}
type StartTraceParams struct {
}
type StartTraceResult struct {
}
type StopTraceParams struct {
}
type StopTraceResult struct {
}
type TraceEvent struct {
	Kind     string                               `json:"kind"`
	Name     string                               `json:"name"`
	Sequence int64                                `json:"sequence"`
	Time     string                               `json:"time"`
	Data     Optional[map[string]json.RawMessage] `json:"data,omitzero"`
}
type UpdateProfileParams struct {
	Patch    ProfilePatch `json:"patch"`
	TargetId string       `json:"targetId"`
}
type UpdateProfileResult struct {
	Profile EnvironmentProfile `json:"profile"`
}
type UpdateResourcePolicyParams struct {
	BrowserContextId string         `json:"browserContextId"`
	Policy           ResourcePolicy `json:"policy"`
}
type UpdateResourcePolicyResult struct {
	Generation int64 `json:"generation"`
}
type ValidateMediaProfileParams struct {
	BrowserContextId Optional[string]                 `json:"browserContextId,omitzero"`
	Camera           Optional[MediaCameraRequest]     `json:"camera,omitzero"`
	Devices          Optional[[]MediaDeviceProfile]   `json:"devices,omitzero"`
	Microphone       Optional[MediaMicrophoneRequest] `json:"microphone,omitzero"`
	Seed             Optional[string]                 `json:"seed,omitzero"`
}
type ValidateMediaProfileResult struct {
	NativeModesVerified bool         `json:"nativeModesVerified"`
	Profile             MediaProfile `json:"profile"`
}
type ValidateResourcePolicyParams struct {
	Policy ResourcePolicy `json:"policy"`
}
type ValidateResourcePolicyResult struct {
	Policy ResourcePolicy `json:"policy"`
}

func (c *MimicCommands) CancelExecution(ctx context.Context, params CancelExecutionParams) (CancelExecutionResult, error) {
	var result CancelExecutionResult
	err := c.Sender.Call(ctx, "Mimic.cancelExecution", params, &result)
	return result, err
}
func (c *MimicCommands) CaptureSnapshot(ctx context.Context, params CaptureSnapshotParams) (CaptureSnapshotResult, error) {
	var result CaptureSnapshotResult
	err := c.Sender.Call(ctx, "Mimic.captureSnapshot", params, &result)
	return result, err
}
func (c *MimicCommands) ClearTrace(ctx context.Context, params ClearTraceParams) (ClearTraceResult, error) {
	var result ClearTraceResult
	err := c.Sender.Call(ctx, "Mimic.clearTrace", params, &result)
	return result, err
}
func (c *MimicCommands) ConfigureContext(ctx context.Context, params ConfigureContextParams) (ConfigureContextResult, error) {
	var result ConfigureContextResult
	err := c.Sender.Call(ctx, "Mimic.configureContext", params, &result)
	return result, err
}
func (c *MimicCommands) CreateContext(ctx context.Context, params CreateContextParams) (CreateContextResult, error) {
	var result CreateContextResult
	err := c.Sender.Call(ctx, "Mimic.createContext", params, &result)
	return result, err
}
func (c *MimicCommands) ExportProfile(ctx context.Context, params ExportProfileParams) (ExportProfileResult, error) {
	var result ExportProfileResult
	err := c.Sender.Call(ctx, "Mimic.exportProfile", params, &result)
	return result, err
}
func (c *MimicCommands) GenerateProfile(ctx context.Context, params GenerateProfileParams) (GenerateProfileResult, error) {
	var result GenerateProfileResult
	err := c.Sender.Call(ctx, "Mimic.generateProfile", params, &result)
	return result, err
}
func (c *MimicCommands) GetCompatibilityMatrix(ctx context.Context, params GetCompatibilityMatrixParams) (GetCompatibilityMatrixResult, error) {
	var result GetCompatibilityMatrixResult
	err := c.Sender.Call(ctx, "Mimic.getCompatibilityMatrix", params, &result)
	return result, err
}
func (c *MimicCommands) GetDiagnostics(ctx context.Context, params GetDiagnosticsParams) (GetDiagnosticsResult, error) {
	var result GetDiagnosticsResult
	err := c.Sender.Call(ctx, "Mimic.getDiagnostics", params, &result)
	return result, err
}
func (c *MimicCommands) GetMediaPresets(ctx context.Context, params GetMediaPresetsParams) (GetMediaPresetsResult, error) {
	var result GetMediaPresetsResult
	err := c.Sender.Call(ctx, "Mimic.getMediaPresets", params, &result)
	return result, err
}
func (c *MimicCommands) GetMediaProfile(ctx context.Context, params GetMediaProfileParams) (GetMediaProfileResult, error) {
	var result GetMediaProfileResult
	err := c.Sender.Call(ctx, "Mimic.getMediaProfile", params, &result)
	return result, err
}
func (c *MimicCommands) GetMediaSources(ctx context.Context, params GetMediaSourcesParams) (GetMediaSourcesResult, error) {
	var result GetMediaSourcesResult
	err := c.Sender.Call(ctx, "Mimic.getMediaSources", params, &result)
	return result, err
}
func (c *MimicCommands) GetProfile(ctx context.Context, params GetProfileParams) (GetProfileResult, error) {
	var result GetProfileResult
	err := c.Sender.Call(ctx, "Mimic.getProfile", params, &result)
	return result, err
}
func (c *MimicCommands) GetProfileSchema(ctx context.Context, params GetProfileSchemaParams) (GetProfileSchemaResult, error) {
	var result GetProfileSchemaResult
	err := c.Sender.Call(ctx, "Mimic.getProfileSchema", params, &result)
	return result, err
}
func (c *MimicCommands) GetResourcePolicy(ctx context.Context, params GetResourcePolicyParams) (GetResourcePolicyResult, error) {
	var result GetResourcePolicyResult
	err := c.Sender.Call(ctx, "Mimic.getResourcePolicy", params, &result)
	return result, err
}
func (c *MimicCommands) GetResourcePolicySchema(ctx context.Context, params GetResourcePolicySchemaParams) (GetResourcePolicySchemaResult, error) {
	var result GetResourcePolicySchemaResult
	err := c.Sender.Call(ctx, "Mimic.getResourcePolicySchema", params, &result)
	return result, err
}
func (c *MimicCommands) GetResourcePolicyStats(ctx context.Context, params GetResourcePolicyStatsParams) (GetResourcePolicyStatsResult, error) {
	var result GetResourcePolicyStatsResult
	err := c.Sender.Call(ctx, "Mimic.getResourcePolicyStats", params, &result)
	return result, err
}
func (c *MimicCommands) GetStatus(ctx context.Context, params GetStatusParams) (GetStatusResult, error) {
	var result GetStatusResult
	err := c.Sender.Call(ctx, "Mimic.getStatus", params, &result)
	return result, err
}
func (c *MimicCommands) GetTrace(ctx context.Context, params GetTraceParams) (GetTraceResult, error) {
	var result GetTraceResult
	err := c.Sender.Call(ctx, "Mimic.getTrace", params, &result)
	return result, err
}
func (c *MimicCommands) GetVersion(ctx context.Context, params GetVersionParams) (GetVersionResult, error) {
	var result GetVersionResult
	err := c.Sender.Call(ctx, "Mimic.getVersion", params, &result)
	return result, err
}
func (c *MimicCommands) ImportProfile(ctx context.Context, params ImportProfileParams) (ImportProfileResult, error) {
	var result ImportProfileResult
	err := c.Sender.Call(ctx, "Mimic.importProfile", params, &result)
	return result, err
}
func (c *MimicCommands) Pause(ctx context.Context, params PauseParams) (PauseResult, error) {
	var result PauseResult
	err := c.Sender.Call(ctx, "Mimic.pause", params, &result)
	return result, err
}
func (c *MimicCommands) ResetProfileOverrides(ctx context.Context, params ResetProfileOverridesParams) (ResetProfileOverridesResult, error) {
	var result ResetProfileOverridesResult
	err := c.Sender.Call(ctx, "Mimic.resetProfileOverrides", params, &result)
	return result, err
}
func (c *MimicCommands) Resume(ctx context.Context, params ResumeParams) (ResumeResult, error) {
	var result ResumeResult
	err := c.Sender.Call(ctx, "Mimic.resume", params, &result)
	return result, err
}
func (c *MimicCommands) SetMediaProfile(ctx context.Context, params SetMediaProfileParams) (SetMediaProfileResult, error) {
	var result SetMediaProfileResult
	err := c.Sender.Call(ctx, "Mimic.setMediaProfile", params, &result)
	return result, err
}
func (c *MimicCommands) SetViewport(ctx context.Context, params SetViewportParams) (SetViewportResult, error) {
	var result SetViewportResult
	err := c.Sender.Call(ctx, "Mimic.setViewport", params, &result)
	return result, err
}
func (c *MimicCommands) StartTrace(ctx context.Context, params StartTraceParams) (StartTraceResult, error) {
	var result StartTraceResult
	err := c.Sender.Call(ctx, "Mimic.startTrace", params, &result)
	return result, err
}
func (c *MimicCommands) StopTrace(ctx context.Context, params StopTraceParams) (StopTraceResult, error) {
	var result StopTraceResult
	err := c.Sender.Call(ctx, "Mimic.stopTrace", params, &result)
	return result, err
}
func (c *MimicCommands) UpdateProfile(ctx context.Context, params UpdateProfileParams) (UpdateProfileResult, error) {
	var result UpdateProfileResult
	err := c.Sender.Call(ctx, "Mimic.updateProfile", params, &result)
	return result, err
}
func (c *MimicCommands) UpdateResourcePolicy(ctx context.Context, params UpdateResourcePolicyParams) (UpdateResourcePolicyResult, error) {
	var result UpdateResourcePolicyResult
	err := c.Sender.Call(ctx, "Mimic.updateResourcePolicy", params, &result)
	return result, err
}
func (c *MimicCommands) ValidateMediaProfile(ctx context.Context, params ValidateMediaProfileParams) (ValidateMediaProfileResult, error) {
	var result ValidateMediaProfileResult
	err := c.Sender.Call(ctx, "Mimic.validateMediaProfile", params, &result)
	return result, err
}
func (c *MimicCommands) ValidateResourcePolicy(ctx context.Context, params ValidateResourcePolicyParams) (ValidateResourcePolicyResult, error) {
	var result ValidateResourcePolicyResult
	err := c.Sender.Call(ctx, "Mimic.validateResourcePolicy", params, &result)
	return result, err
}
