<?php
// Generated by generator/generate.py; DO NOT EDIT.
// Schema SHA-256: ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6

declare(strict_types=1);
namespace Mimic\Sdk\Generated;
const SCHEMA_SHA256 = "ea792e2f194bf831f5494bedd65a7112881e45695b3af3d504367c317684e7a6";

enum Missing { case Value; }
abstract class Model implements \JsonSerializable {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
    private static function decode(mixed $value, mixed $type): mixed {
        if ($value === null || $type === null) return $value;
        if (is_array($type)) {
            if ($type[0] === 'array') return array_map(fn($child) => self::decode($child, $type[1]), $value);
            $out = [];
            foreach ((array) $value as $key => $child) $out[$key] = self::decode($child, $type[1]);
            return $out;
        }
        return $type::fromWire($value);
    }
    public static function fromWire(object|array $wire): static {
        $model = new static();
        foreach ((array) $wire as $key => $value) {
            if (!property_exists($model, $key)) continue;
            $model->$key = self::decode($value, static::TYPES[$key] ?? null);
        }
        foreach (static::REQUIRED as $key) {
            if ($model->$key === Missing::Value) throw new \InvalidArgumentException("Missing result field: " . $key);
        }
        return $model;
    }
    public function jsonSerialize(): object {
        $out = [];
        foreach (get_object_vars($this) as $key => $value) {
            if ($value === Missing::Value) {
                if (in_array($key, static::REQUIRED, true)) throw new \InvalidArgumentException("Missing field: " . $key);
                continue;
            }
            $out[$key] = in_array($key, static::MAP_FIELDS, true) && is_array($value) ? (object) $value : $value;
        }
        return (object) $out;
    }
}

final class CameraFormat extends Model {
    protected const REQUIRED = ['width', 'height', 'frameRate'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['width' => null, 'height' => null, 'frameRate' => null];
    public float|Missing|null $frameRate = Missing::Value;
    public int|Missing|null $height = Missing::Value;
    public int|Missing|null $width = Missing::Value;
}
final class CancelExecutionParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class CancelExecutionResult extends Model {
    protected const REQUIRED = ['cancelled'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['cancelled' => null];
    public bool|Missing|null $cancelled = Missing::Value;
}
final class CaptureSnapshotParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['interrupt' => null];
    public bool|Missing|null $interrupt = Missing::Value;
}
final class CaptureSnapshotResult extends Model {
    protected const REQUIRED = ['url', 'files', 'warnings', 'timingsMs'];
    protected const MAP_FIELDS = ['files', 'timingsMs'];
    protected const TYPES = ['url' => null, 'files' => ['map', null], 'warnings' => ['array', null], 'timingsMs' => ['map', null]];
    public array|Missing|null $files = Missing::Value;
    public array|Missing|null $timingsMs = Missing::Value;
    public string|Missing|null $url = Missing::Value;
    public array|Missing|null $warnings = Missing::Value;
}
final class ClearTraceParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class ClearTraceResult extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class ConfigureContextParams extends Model {
    protected const REQUIRED = ['browserContextId'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => null, 'proxy' => Proxy::class, 'resourcePolicy' => ResourcePolicy::class, 'media' => MediaConfiguration::class, 'browserContextId' => null];
    public string|Missing|null $browserContextId = Missing::Value;
    public MediaConfiguration|Missing|null $media = Missing::Value;
    public mixed $profile = Missing::Value;
    public Proxy|Missing|null $proxy = Missing::Value;
    public ResourcePolicy|Missing|null $resourcePolicy = Missing::Value;
}
final class ConfigureContextResult extends Model {
    protected const REQUIRED = ['profile', 'profileId', 'mode', 'warnings', 'browserContextId'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => null, 'profileId' => null, 'mode' => null, 'warnings' => ['array', null], 'browserContextId' => null, 'media' => MediaProfile::class];
    public string|Missing|null $browserContextId = Missing::Value;
    public string|Missing|null $mode = Missing::Value;
    public string|Missing|null $profile = Missing::Value;
    public string|Missing|null $profileId = Missing::Value;
    public array|Missing|null $warnings = Missing::Value;
    public MediaProfile|Missing|null $media = Missing::Value;
}
final class CreateContextParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => null, 'proxy' => Proxy::class, 'resourcePolicy' => ResourcePolicy::class, 'disposeOnDetach' => null, 'media' => MediaConfiguration::class];
    public bool|Missing|null $disposeOnDetach = Missing::Value;
    public MediaConfiguration|Missing|null $media = Missing::Value;
    public mixed $profile = Missing::Value;
    public Proxy|Missing|null $proxy = Missing::Value;
    public ResourcePolicy|Missing|null $resourcePolicy = Missing::Value;
}
final class CreateContextResult extends Model {
    protected const REQUIRED = ['profile', 'profileId', 'mode', 'warnings', 'browserContextId'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => null, 'profileId' => null, 'mode' => null, 'warnings' => ['array', null], 'browserContextId' => null, 'media' => MediaProfile::class];
    public string|Missing|null $browserContextId = Missing::Value;
    public string|Missing|null $mode = Missing::Value;
    public string|Missing|null $profile = Missing::Value;
    public string|Missing|null $profileId = Missing::Value;
    public array|Missing|null $warnings = Missing::Value;
    public MediaProfile|Missing|null $media = Missing::Value;
}
final class DiagnosticCost extends Model {
    protected const REQUIRED = ['count', 'ns'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['count' => null, 'ns' => null];
    public int|Missing|null $count = Missing::Value;
    public int|Missing|null $ns = Missing::Value;
}
final class Diagnostics extends Model {
    protected const REQUIRED = ['enabled'];
    protected const MAP_FIELDS = ['costs', 'cpu_profiles'];
    protected const TYPES = ['enabled' => null, 'hostOnly' => null, 'costs' => ['map', DiagnosticCost::class], 'cpu_profiles' => ['map', null], 'realms' => ['array', RealmDiagnostics::class]];
    public bool|Missing|null $enabled = Missing::Value;
    public array|Missing|null $costs = Missing::Value;
    public array|Missing|null $cpu_profiles = Missing::Value;
    public bool|Missing|null $hostOnly = Missing::Value;
    public array|Missing|null $realms = Missing::Value;
}
final class EmptyValue extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class EnvironmentAudio extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['sampleRate' => null, 'channels' => null, 'bufferDuration' => null, 'maxBufferFrames' => null];
    public float|Missing|null $bufferDuration = Missing::Value;
    public int|Missing|null $channels = Missing::Value;
    public int|Missing|null $maxBufferFrames = Missing::Value;
    public float|Missing|null $sampleRate = Missing::Value;
}
final class EnvironmentCapabilities extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['keyboardLayout'];
    protected const TYPES = ['storageQuotaBytes' => null, 'devices' => EnvironmentDeviceCapabilities::class, 'media' => EnvironmentMediaCapabilities::class, 'keyboardLayout' => ['map', null]];
    public EnvironmentDeviceCapabilities|Missing|null $devices = Missing::Value;
    public array|Missing|null $keyboardLayout = Missing::Value;
    public EnvironmentMediaCapabilities|Missing|null $media = Missing::Value;
    public int|Missing|null $storageQuotaBytes = Missing::Value;
}
final class EnvironmentDeviceCapabilities extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['bluetoothAvailable' => null, 'posture' => null];
    public bool|Missing|null $bluetoothAvailable = Missing::Value;
    public string|Missing|null $posture = Missing::Value;
}
final class EnvironmentDisplay extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['width' => null, 'height' => null, 'availableWidth' => null, 'availableHeight' => null, 'deviceScaleFactor' => null, 'colorDepth' => null, 'orientation' => EnvironmentScreenOrientation::class];
    public int|Missing|null $availableHeight = Missing::Value;
    public int|Missing|null $availableWidth = Missing::Value;
    public int|Missing|null $colorDepth = Missing::Value;
    public float|Missing|null $deviceScaleFactor = Missing::Value;
    public int|Missing|null $height = Missing::Value;
    public EnvironmentScreenOrientation|Missing|null $orientation = Missing::Value;
    public int|Missing|null $width = Missing::Value;
}
final class EnvironmentFonts extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['system'];
    protected const TYPES = ['serif' => null, 'sansSerif' => null, 'monospace' => null, 'systemUI' => null, 'system' => ['map', null], 'fallback' => ['array', null]];
    public array|Missing|null $fallback = Missing::Value;
    public string|Missing|null $monospace = Missing::Value;
    public string|Missing|null $sansSerif = Missing::Value;
    public string|Missing|null $serif = Missing::Value;
    public array|Missing|null $system = Missing::Value;
    public string|Missing|null $systemUI = Missing::Value;
}
final class EnvironmentGPUAdapter extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['limits'];
    protected const TYPES = ['vendor' => null, 'architecture' => null, 'device' => null, 'description' => null, 'subgroupMinSize' => null, 'subgroupMaxSize' => null, 'isFallbackAdapter' => null, 'features' => ['array', null], 'limits' => ['map', null], 'wgslLanguageFeatures' => ['array', null], 'initializationDelayMillis' => null];
    public string|Missing|null $architecture = Missing::Value;
    public string|Missing|null $description = Missing::Value;
    public string|Missing|null $device = Missing::Value;
    public array|Missing|null $features = Missing::Value;
    public float|Missing|null $initializationDelayMillis = Missing::Value;
    public bool|Missing|null $isFallbackAdapter = Missing::Value;
    public array|Missing|null $limits = Missing::Value;
    public int|Missing|null $subgroupMaxSize = Missing::Value;
    public int|Missing|null $subgroupMinSize = Missing::Value;
    public string|Missing|null $vendor = Missing::Value;
    public array|Missing|null $wgslLanguageFeatures = Missing::Value;
}
final class EnvironmentGraphics extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['webGPUAdapters'];
    protected const TYPES = ['vendor' => null, 'renderer' => null, 'maxTextureSize' => null, 'webGLCapabilitiesJSON' => null, 'webGPU' => EnvironmentGPUAdapter::class, 'webGPUAdapters' => ['map', EnvironmentGPUAdapter::class]];
    public int|Missing|null $maxTextureSize = Missing::Value;
    public string|Missing|null $renderer = Missing::Value;
    public string|Missing|null $vendor = Missing::Value;
    public string|Missing|null $webGLCapabilitiesJSON = Missing::Value;
    public EnvironmentGPUAdapter|Missing|null $webGPU = Missing::Value;
    public array|Missing|null $webGPUAdapters = Missing::Value;
}
final class EnvironmentHardware extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['cpuPerformance' => null, 'cpuPerformanceKnown' => null, 'logicalProcessors' => null, 'deviceMemoryGB' => null];
    public int|Missing|null $cpuPerformance = Missing::Value;
    public bool|Missing|null $cpuPerformanceKnown = Missing::Value;
    public float|Missing|null $deviceMemoryGB = Missing::Value;
    public int|Missing|null $logicalProcessors = Missing::Value;
}
final class EnvironmentICEProfile extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['hostCandidateCount' => null, 'reflexiveCandidateCount' => null, 'portOffsets' => ['array', null], 'reflexivePortOffsets' => ['array', null], 'publicAddress' => null, 'networkCost' => null, 'hostDelayMillis' => null, 'reflexiveDelayMillis' => null, 'endDelayMillis' => null];
    public float|Missing|null $endDelayMillis = Missing::Value;
    public int|Missing|null $hostCandidateCount = Missing::Value;
    public float|Missing|null $hostDelayMillis = Missing::Value;
    public int|Missing|null $networkCost = Missing::Value;
    public array|Missing|null $portOffsets = Missing::Value;
    public string|Missing|null $publicAddress = Missing::Value;
    public int|Missing|null $reflexiveCandidateCount = Missing::Value;
    public float|Missing|null $reflexiveDelayMillis = Missing::Value;
    public array|Missing|null $reflexivePortOffsets = Missing::Value;
}
final class EnvironmentIdentity extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['userAgent' => null, 'platform' => null, 'metadata' => EnvironmentUserAgentMetadata::class];
    public EnvironmentUserAgentMetadata|Missing|null $metadata = Missing::Value;
    public string|Missing|null $platform = Missing::Value;
    public string|Missing|null $userAgent = Missing::Value;
}
final class EnvironmentLocale extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['reduceAcceptLanguage' => null, 'languages' => ['array', null], 'intlLocale' => null, 'timezone' => null];
    public string|Missing|null $intlLocale = Missing::Value;
    public array|Missing|null $languages = Missing::Value;
    public bool|Missing|null $reduceAcceptLanguage = Missing::Value;
    public string|Missing|null $timezone = Missing::Value;
}
final class EnvironmentMediaCapabilities extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['rtp'];
    protected const TYPES = ['rtp' => ['map', EnvironmentRTPMediaCatalog::class], 'formats' => EnvironmentMediaFormatCatalog::class, 'kinds' => ['array', null], 'supportedConstraints' => ['array', null]];
    public EnvironmentMediaFormatCatalog|Missing|null $formats = Missing::Value;
    public array|Missing|null $kinds = Missing::Value;
    public array|Missing|null $rtp = Missing::Value;
    public array|Missing|null $supportedConstraints = Missing::Value;
}
final class EnvironmentMediaContainerPolicy extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['codecs' => ['array', null], 'defaultCodec' => null, 'mediaSource' => null];
    public array|Missing|null $codecs = Missing::Value;
    public string|Missing|null $defaultCodec = Missing::Value;
    public bool|Missing|null $mediaSource = Missing::Value;
}
final class EnvironmentMediaFormatCatalog extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['containers'];
    protected const TYPES = ['containers' => ['map', EnvironmentMediaContainerPolicy::class], 'efficientVideo' => ['array', null]];
    public array|Missing|null $containers = Missing::Value;
    public array|Missing|null $efficientVideo = Missing::Value;
}
final class EnvironmentNetwork extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['saveData' => null, 'online' => null, 'effectiveType' => null, 'downlinkMbps' => null, 'rttMillis' => null, 'cookiesEnabled' => null, 'wireProfile' => null, 'ice' => EnvironmentICEProfile::class, 'proxy' => EnvironmentProxy::class];
    public bool|Missing|null $cookiesEnabled = Missing::Value;
    public float|Missing|null $downlinkMbps = Missing::Value;
    public string|Missing|null $effectiveType = Missing::Value;
    public EnvironmentICEProfile|Missing|null $ice = Missing::Value;
    public bool|Missing|null $online = Missing::Value;
    public EnvironmentProxy|Missing|null $proxy = Missing::Value;
    public float|Missing|null $rttMillis = Missing::Value;
    public bool|Missing|null $saveData = Missing::Value;
    public string|Missing|null $wireProfile = Missing::Value;
}
final class EnvironmentPreferences extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['systemColors'];
    protected const TYPES = ['colorScheme' => null, 'systemColors' => ['map', ['map', null]], 'reducedMotion' => null, 'doNotTrack' => null];
    public string|Missing|null $colorScheme = Missing::Value;
    public bool|Missing|null $doNotTrack = Missing::Value;
    public bool|Missing|null $reducedMotion = Missing::Value;
    public array|Missing|null $systemColors = Missing::Value;
}
final class EnvironmentProfile extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['permissions', 'features'];
    protected const TYPES = ['schemaVersion' => null, 'baseProfile' => null, 'identity' => EnvironmentIdentity::class, 'display' => EnvironmentDisplay::class, 'window' => EnvironmentWindow::class, 'hardware' => EnvironmentHardware::class, 'locale' => EnvironmentLocale::class, 'graphics' => EnvironmentGraphics::class, 'audio' => EnvironmentAudio::class, 'fonts' => EnvironmentFonts::class, 'preferences' => EnvironmentPreferences::class, 'network' => EnvironmentNetwork::class, 'permissions' => ['map', null], 'capabilities' => EnvironmentCapabilities::class, 'features' => ['map', null], 'timing' => EnvironmentTiming::class];
    public EnvironmentAudio|Missing|null $audio = Missing::Value;
    public string|Missing|null $baseProfile = Missing::Value;
    public EnvironmentCapabilities|Missing|null $capabilities = Missing::Value;
    public EnvironmentDisplay|Missing|null $display = Missing::Value;
    public array|Missing|null $features = Missing::Value;
    public EnvironmentFonts|Missing|null $fonts = Missing::Value;
    public EnvironmentGraphics|Missing|null $graphics = Missing::Value;
    public EnvironmentHardware|Missing|null $hardware = Missing::Value;
    public EnvironmentIdentity|Missing|null $identity = Missing::Value;
    public EnvironmentLocale|Missing|null $locale = Missing::Value;
    public EnvironmentNetwork|Missing|null $network = Missing::Value;
    public array|Missing|null $permissions = Missing::Value;
    public EnvironmentPreferences|Missing|null $preferences = Missing::Value;
    public int|Missing|null $schemaVersion = Missing::Value;
    public EnvironmentTiming|Missing|null $timing = Missing::Value;
    public EnvironmentWindow|Missing|null $window = Missing::Value;
}
final class EnvironmentProxy extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['server' => null, 'username' => null, 'password' => null];
    public string|Missing|null $password = Missing::Value;
    public string|Missing|null $server = Missing::Value;
    public string|Missing|null $username = Missing::Value;
}
final class EnvironmentRTPCodec extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['name' => null, 'clockRate' => null, 'channels' => null, 'parameters' => null, 'senderParameters' => null, 'feedback' => ['array', null], 'payload' => null, 'rtxPayload' => null, 'redundant' => ['array', null]];
    public int|Missing|null $channels = Missing::Value;
    public int|Missing|null $clockRate = Missing::Value;
    public array|Missing|null $feedback = Missing::Value;
    public string|Missing|null $name = Missing::Value;
    public string|Missing|null $parameters = Missing::Value;
    public int|Missing|null $payload = Missing::Value;
    public array|Missing|null $redundant = Missing::Value;
    public int|Missing|null $rtxPayload = Missing::Value;
    public string|Missing|null $senderParameters = Missing::Value;
}
final class EnvironmentRTPMediaCatalog extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['codecs'];
    protected const TYPES = ['codecs' => ['map', EnvironmentRTPCodec::class], 'senderOrder' => ['array', null], 'receiverOrder' => ['array', null], 'offerOrder' => ['array', null], 'headerExtensions' => ['array', null], 'receiverRTT' => null];
    public array|Missing|null $codecs = Missing::Value;
    public array|Missing|null $headerExtensions = Missing::Value;
    public array|Missing|null $offerOrder = Missing::Value;
    public array|Missing|null $receiverOrder = Missing::Value;
    public bool|Missing|null $receiverRTT = Missing::Value;
    public array|Missing|null $senderOrder = Missing::Value;
}
final class EnvironmentScreenOrientation extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['type' => null, 'angle' => null];
    public int|Missing|null $angle = Missing::Value;
    public string|Missing|null $type = Missing::Value;
}
final class EnvironmentTiming extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['executionScale' => null, 'navigationScale' => null, 'networkScale' => null];
    public float|Missing|null $executionScale = Missing::Value;
    public float|Missing|null $navigationScale = Missing::Value;
    public float|Missing|null $networkScale = Missing::Value;
}
final class EnvironmentUserAgentBrand extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['brand' => null, 'version' => null, 'fullVersion' => null];
    public string|Missing|null $brand = Missing::Value;
    public string|Missing|null $fullVersion = Missing::Value;
    public string|Missing|null $version = Missing::Value;
}
final class EnvironmentUserAgentMetadata extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['brands' => ['array', EnvironmentUserAgentBrand::class], 'fullVersionList' => ['array', EnvironmentUserAgentBrand::class], 'formFactors' => ['array', null], 'fullVersion' => null, 'platform' => null, 'platformVersion' => null, 'architecture' => null, 'model' => null, 'bitness' => null, 'mobile' => null, 'wow64' => null];
    public string|Missing|null $architecture = Missing::Value;
    public string|Missing|null $bitness = Missing::Value;
    public array|Missing|null $brands = Missing::Value;
    public array|Missing|null $formFactors = Missing::Value;
    public string|Missing|null $fullVersion = Missing::Value;
    public array|Missing|null $fullVersionList = Missing::Value;
    public bool|Missing|null $mobile = Missing::Value;
    public string|Missing|null $model = Missing::Value;
    public string|Missing|null $platform = Missing::Value;
    public string|Missing|null $platformVersion = Missing::Value;
    public bool|Missing|null $wow64 = Missing::Value;
}
final class EnvironmentWindow extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['x' => null, 'y' => null, 'outerWidth' => null, 'outerHeight' => null, 'viewportWidth' => null, 'viewportHeight' => null];
    public int|Missing|null $outerHeight = Missing::Value;
    public int|Missing|null $outerWidth = Missing::Value;
    public int|Missing|null $viewportHeight = Missing::Value;
    public int|Missing|null $viewportWidth = Missing::Value;
    public int|Missing|null $x = Missing::Value;
    public int|Missing|null $y = Missing::Value;
}
final class ExecutionStatus extends Model {
    protected const REQUIRED = ['running', 'taskId', 'source', 'phase', 'elapsedMs'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['running' => null, 'taskId' => null, 'source' => null, 'phase' => null, 'elapsedMs' => null];
    public int|Missing|null $elapsedMs = Missing::Value;
    public string|Missing|null $phase = Missing::Value;
    public bool|Missing|null $running = Missing::Value;
    public string|Missing|null $source = Missing::Value;
    public int|Missing|null $taskId = Missing::Value;
}
final class ExportProfileParams extends Model {
    protected const REQUIRED = ['profile'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => null];
    public string|Missing|null $profile = Missing::Value;
}
final class ExportProfileResult extends Model {
    protected const REQUIRED = ['profile', 'warnings'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => ProfileDescriptor::class, 'warnings' => ['array', null]];
    public ProfileDescriptor|Missing|null $profile = Missing::Value;
    public array|Missing|null $warnings = Missing::Value;
}
final class GenerateProfileOptions extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['browser' => null, 'version' => null, 'platform' => null, 'seed' => null];
    public string|Missing|null $browser = Missing::Value;
    public string|Missing|null $platform = Missing::Value;
    public string|Missing|null $seed = Missing::Value;
    public int|Missing|null $version = Missing::Value;
}
final class GenerateProfileParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['browser' => null, 'version' => null, 'platform' => null, 'seed' => null];
    public string|Missing|null $browser = Missing::Value;
    public string|Missing|null $platform = Missing::Value;
    public string|Missing|null $seed = Missing::Value;
    public int|Missing|null $version = Missing::Value;
}
final class GenerateProfileResult extends Model {
    protected const REQUIRED = ['profile', 'profileId', 'mode', 'warnings'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => null, 'profileId' => null, 'mode' => null, 'warnings' => ['array', null]];
    public string|Missing|null $mode = Missing::Value;
    public string|Missing|null $profile = Missing::Value;
    public string|Missing|null $profileId = Missing::Value;
    public array|Missing|null $warnings = Missing::Value;
}
final class GenerateProfileSelection extends Model {
    protected const REQUIRED = ['generate'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['generate' => GenerateProfileOptions::class];
    public GenerateProfileOptions|Missing|null $generate = Missing::Value;
}
final class GetCompatibilityMatrixParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class GetCompatibilityMatrixResult extends Model {
    protected const REQUIRED = ['chromeVersion', 'protocol', 'extensions'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['chromeVersion' => null, 'protocol' => ['array', ProtocolCoverage::class], 'extensions' => ['array', ProtocolCoverage::class]];
    public string|Missing|null $chromeVersion = Missing::Value;
    public array|Missing|null $extensions = Missing::Value;
    public array|Missing|null $protocol = Missing::Value;
}
final class GetDiagnosticsParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class GetDiagnosticsResult extends Model {
    protected const REQUIRED = ['enabled'];
    protected const MAP_FIELDS = ['costs', 'cpu_profiles'];
    protected const TYPES = ['enabled' => null, 'hostOnly' => null, 'costs' => ['map', DiagnosticCost::class], 'cpu_profiles' => ['map', null], 'realms' => ['array', RealmDiagnostics::class]];
    public bool|Missing|null $enabled = Missing::Value;
    public array|Missing|null $costs = Missing::Value;
    public array|Missing|null $cpu_profiles = Missing::Value;
    public bool|Missing|null $hostOnly = Missing::Value;
    public array|Missing|null $realms = Missing::Value;
}
final class GetMediaPresetsParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['browserContextId' => null];
    public string|Missing|null $browserContextId = Missing::Value;
}
final class GetMediaPresetsResult extends Model {
    protected const REQUIRED = ['presets'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['presets' => ['array', MediaPreset::class]];
    public array|Missing|null $presets = Missing::Value;
}
final class GetMediaProfileParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['browserContextId' => null];
    public string|Missing|null $browserContextId = Missing::Value;
}
final class GetMediaProfileResult extends Model {
    protected const REQUIRED = ['profile', 'diagnostics'];
    protected const MAP_FIELDS = ['diagnostics'];
    protected const TYPES = ['profile' => MediaProfile::class, 'diagnostics' => ['map', null]];
    public array|Missing|null $diagnostics = Missing::Value;
    public MediaProfile|null|Missing $profile = Missing::Value;
}
final class GetMediaSourcesParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['browserContextId' => null];
    public string|Missing|null $browserContextId = Missing::Value;
}
final class GetMediaSourcesResult extends Model {
    protected const REQUIRED = ['sources', 'diagnostics'];
    protected const MAP_FIELDS = ['diagnostics'];
    protected const TYPES = ['sources' => ['array', MediaSource::class], 'diagnostics' => ['map', null]];
    public array|Missing|null $diagnostics = Missing::Value;
    public array|Missing|null $sources = Missing::Value;
}
final class GetProfileParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['browserContextId' => null, 'targetId' => null];
    public string|Missing|null $browserContextId = Missing::Value;
    public string|Missing|null $targetId = Missing::Value;
}
final class GetProfileResult extends Model {
    protected const REQUIRED = ['profile', 'limitations'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => EnvironmentProfile::class, 'limitations' => ['array', null]];
    public array|Missing|null $limitations = Missing::Value;
    public EnvironmentProfile|Missing|null $profile = Missing::Value;
}
final class GetProfileSchemaParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class GetProfileSchemaResult extends Model {
    protected const REQUIRED = ['schema', 'baseProfiles', 'limitations'];
    protected const MAP_FIELDS = ['schema'];
    protected const TYPES = ['schema' => ['map', null], 'baseProfiles' => ['array', null], 'limitations' => ['array', null]];
    public array|Missing|null $baseProfiles = Missing::Value;
    public array|Missing|null $limitations = Missing::Value;
    public array|Missing|null $schema = Missing::Value;
}
final class GetResourcePolicyParams extends Model {
    protected const REQUIRED = ['browserContextId'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['browserContextId' => null];
    public string|Missing|null $browserContextId = Missing::Value;
}
final class GetResourcePolicyResult extends Model {
    protected const REQUIRED = ['policy', 'enabled', 'generation'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['policy' => ResourcePolicy::class, 'enabled' => null, 'generation' => null];
    public bool|Missing|null $enabled = Missing::Value;
    public int|Missing|null $generation = Missing::Value;
    public ResourcePolicy|Missing|null $policy = Missing::Value;
}
final class GetResourcePolicySchemaParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class GetResourcePolicySchemaResult extends Model {
    protected const REQUIRED = ['schema'];
    protected const MAP_FIELDS = ['schema'];
    protected const TYPES = ['schema' => ['map', null]];
    public array|Missing|null $schema = Missing::Value;
}
final class GetResourcePolicyStatsParams extends Model {
    protected const REQUIRED = ['browserContextId'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['browserContextId' => null];
    public string|Missing|null $browserContextId = Missing::Value;
}
final class GetResourcePolicyStatsResult extends Model {
    protected const REQUIRED = ['stats'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['stats' => ResourcePolicyStats::class];
    public ResourcePolicyStats|Missing|null $stats = Missing::Value;
}
final class GetStatusParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class GetStatusResult extends Model {
    protected const REQUIRED = ['execution'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['execution' => ExecutionStatus::class];
    public ExecutionStatus|Missing|null $execution = Missing::Value;
}
final class GetTraceParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class GetTraceResult extends Model {
    protected const REQUIRED = ['events', 'crashReports'];
    protected const MAP_FIELDS = ['crashReports'];
    protected const TYPES = ['events' => ['array', TraceEvent::class], 'crashReports' => ['map', null]];
    public array|Missing|null $crashReports = Missing::Value;
    public array|null|Missing $events = Missing::Value;
}
final class GetVersionParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class GetVersionResult extends Model {
    protected const REQUIRED = ['version', 'chromeVersion', 'baseProfile'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['version' => null, 'chromeVersion' => null, 'baseProfile' => null];
    public string|Missing|null $baseProfile = Missing::Value;
    public string|Missing|null $chromeVersion = Missing::Value;
    public string|Missing|null $version = Missing::Value;
}
final class ImportProfileParams extends Model {
    protected const REQUIRED = ['profile'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => null, 'mode' => null];
    public mixed $profile = Missing::Value;
    public string|Missing|null $mode = Missing::Value;
}
final class ImportProfileResult extends Model {
    protected const REQUIRED = ['profile', 'profileId', 'mode', 'warnings'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => null, 'profileId' => null, 'mode' => null, 'warnings' => ['array', null]];
    public string|Missing|null $mode = Missing::Value;
    public string|Missing|null $profile = Missing::Value;
    public string|Missing|null $profileId = Missing::Value;
    public array|Missing|null $warnings = Missing::Value;
}
final class ManualNetwork extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['saveData' => null, 'online' => null, 'effectiveType' => null, 'downlinkMbps' => null, 'rttMillis' => null, 'cookiesEnabled' => null, 'wireProfile' => null, 'ice' => EnvironmentICEProfile::class];
    public bool|Missing|null $cookiesEnabled = Missing::Value;
    public float|Missing|null $downlinkMbps = Missing::Value;
    public string|Missing|null $effectiveType = Missing::Value;
    public EnvironmentICEProfile|Missing|null $ice = Missing::Value;
    public bool|Missing|null $online = Missing::Value;
    public float|Missing|null $rttMillis = Missing::Value;
    public bool|Missing|null $saveData = Missing::Value;
    public string|Missing|null $wireProfile = Missing::Value;
}
final class ManualProfile extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['permissions', 'features'];
    protected const TYPES = ['identity' => EnvironmentIdentity::class, 'display' => EnvironmentDisplay::class, 'window' => EnvironmentWindow::class, 'hardware' => EnvironmentHardware::class, 'locale' => EnvironmentLocale::class, 'graphics' => EnvironmentGraphics::class, 'audio' => EnvironmentAudio::class, 'fonts' => EnvironmentFonts::class, 'preferences' => EnvironmentPreferences::class, 'network' => ManualNetwork::class, 'permissions' => ['map', null], 'capabilities' => EnvironmentCapabilities::class, 'features' => ['map', null], 'timing' => EnvironmentTiming::class];
    public EnvironmentAudio|Missing|null $audio = Missing::Value;
    public EnvironmentCapabilities|Missing|null $capabilities = Missing::Value;
    public EnvironmentDisplay|Missing|null $display = Missing::Value;
    public array|Missing|null $features = Missing::Value;
    public EnvironmentFonts|Missing|null $fonts = Missing::Value;
    public EnvironmentGraphics|Missing|null $graphics = Missing::Value;
    public EnvironmentHardware|Missing|null $hardware = Missing::Value;
    public EnvironmentIdentity|Missing|null $identity = Missing::Value;
    public EnvironmentLocale|Missing|null $locale = Missing::Value;
    public ManualNetwork|Missing|null $network = Missing::Value;
    public array|Missing|null $permissions = Missing::Value;
    public EnvironmentPreferences|Missing|null $preferences = Missing::Value;
    public EnvironmentTiming|Missing|null $timing = Missing::Value;
    public EnvironmentWindow|Missing|null $window = Missing::Value;
}
final class MediaCameraRequest extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['source' => null, 'profile' => null, 'overrides' => MediaDeviceOverride::class];
    public MediaDeviceOverride|Missing|null $overrides = Missing::Value;
    public string|Missing|null $profile = Missing::Value;
    public mixed $source = Missing::Value;
}
final class MediaConfiguration extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['seed' => null, 'camera' => MediaCameraRequest::class, 'microphone' => MediaMicrophoneRequest::class, 'devices' => ['array', MediaDeviceProfile::class]];
    public MediaCameraRequest|Missing|null $camera = Missing::Value;
    public array|Missing|null $devices = Missing::Value;
    public MediaMicrophoneRequest|Missing|null $microphone = Missing::Value;
    public string|Missing|null $seed = Missing::Value;
}
final class MediaDeviceOverride extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['label' => null, 'modes' => ['array', CameraFormat::class], 'defaultMode' => CameraFormat::class, 'processing' => MediaProcessing::class];
    public CameraFormat|Missing|null $defaultMode = Missing::Value;
    public string|Missing|null $label = Missing::Value;
    public array|Missing|null $modes = Missing::Value;
    public MediaProcessing|Missing|null $processing = Missing::Value;
}
final class MediaDeviceProfile extends Model {
    protected const REQUIRED = ['key', 'kind', 'source', 'label'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['key' => null, 'kind' => null, 'source' => null, 'profile' => null, 'label' => null, 'group' => null, 'modes' => ['array', CameraFormat::class], 'defaultMode' => CameraFormat::class, 'processing' => MediaProcessing::class];
    public string|Missing|null $key = Missing::Value;
    public string|Missing|null $kind = Missing::Value;
    public string|Missing|null $label = Missing::Value;
    public mixed $source = Missing::Value;
    public CameraFormat|Missing|null $defaultMode = Missing::Value;
    public string|Missing|null $group = Missing::Value;
    public array|Missing|null $modes = Missing::Value;
    public MediaProcessing|Missing|null $processing = Missing::Value;
    public string|Missing|null $profile = Missing::Value;
}
final class MediaMicrophoneRequest extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['source' => null, 'profile' => null];
    public string|Missing|null $profile = Missing::Value;
    public mixed $source = Missing::Value;
}
final class MediaPreset extends Model {
    protected const REQUIRED = ['id', 'label', 'class', 'variants'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['id' => null, 'label' => null, 'class' => null, 'variants' => ['array', null]];
    public string|Missing|null $class = Missing::Value;
    public string|Missing|null $id = Missing::Value;
    public string|Missing|null $label = Missing::Value;
    public array|Missing|null $variants = Missing::Value;
}
final class MediaProcessing extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['resize' => null, 'noise' => null];
    public float|Missing|null $noise = Missing::Value;
    public string|Missing|null $resize = Missing::Value;
}
final class MediaProfile extends Model {
    protected const REQUIRED = ['seed', 'devices'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['seed' => null, 'devices' => ['array', MediaDeviceProfile::class]];
    public array|Missing|null $devices = Missing::Value;
    public string|Missing|null $seed = Missing::Value;
}
final class MediaSource extends Model {
    protected const REQUIRED = ['sourceId', 'kind', 'label', 'default'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['sourceId' => null, 'kind' => null, 'label' => null, 'default' => null];
    public bool|Missing|null $default = Missing::Value;
    public string|Missing|null $kind = Missing::Value;
    public string|Missing|null $label = Missing::Value;
    public string|Missing|null $sourceId = Missing::Value;
}
final class PauseParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class PauseResult extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class ProfileDescriptor extends Model {
    protected const REQUIRED = ['mode', 'baseProfile', 'profileId'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['mode' => null, 'baseProfile' => null, 'seed' => null, 'profileId' => null, 'environment' => ManualProfile::class];
    public string|Missing|null $baseProfile = Missing::Value;
    public string|Missing|null $mode = Missing::Value;
    public string|Missing|null $profileId = Missing::Value;
    public ManualProfile|Missing|null $environment = Missing::Value;
    public string|Missing|null $seed = Missing::Value;
}
final class ProfileErrorData extends Model {
    protected const REQUIRED = ['path', 'reason', 'message'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['path' => null, 'reason' => null, 'message' => null];
    public string|Missing|null $message = Missing::Value;
    public string|Missing|null $path = Missing::Value;
    public string|Missing|null $reason = Missing::Value;
}
final class ProfilePatch extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = ['permissions', 'features'];
    protected const TYPES = ['identity' => EnvironmentIdentity::class, 'display' => EnvironmentDisplay::class, 'window' => EnvironmentWindow::class, 'hardware' => EnvironmentHardware::class, 'locale' => EnvironmentLocale::class, 'graphics' => EnvironmentGraphics::class, 'audio' => EnvironmentAudio::class, 'fonts' => EnvironmentFonts::class, 'preferences' => EnvironmentPreferences::class, 'network' => ManualNetwork::class, 'permissions' => ['map', null], 'capabilities' => EnvironmentCapabilities::class, 'features' => ['map', null], 'timing' => EnvironmentTiming::class];
    public EnvironmentAudio|Missing|null $audio = Missing::Value;
    public EnvironmentCapabilities|Missing|null $capabilities = Missing::Value;
    public EnvironmentDisplay|Missing|null $display = Missing::Value;
    public array|Missing|null $features = Missing::Value;
    public EnvironmentFonts|Missing|null $fonts = Missing::Value;
    public EnvironmentGraphics|Missing|null $graphics = Missing::Value;
    public EnvironmentHardware|Missing|null $hardware = Missing::Value;
    public EnvironmentIdentity|Missing|null $identity = Missing::Value;
    public EnvironmentLocale|Missing|null $locale = Missing::Value;
    public ManualNetwork|Missing|null $network = Missing::Value;
    public array|Missing|null $permissions = Missing::Value;
    public EnvironmentPreferences|Missing|null $preferences = Missing::Value;
    public EnvironmentTiming|Missing|null $timing = Missing::Value;
    public EnvironmentWindow|Missing|null $window = Missing::Value;
}
final class ProtocolCoverage extends Model {
    protected const REQUIRED = ['name', 'kind', 'surfaceRegistered', 'wireSchemaGenerated', 'status', 'semanticsImplemented', 'semanticsVerified'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['name' => null, 'kind' => null, 'surfaceRegistered' => null, 'wireSchemaGenerated' => null, 'status' => null, 'notes' => null, 'tests' => ['array', null], 'semanticsImplemented' => null, 'semanticsVerified' => null];
    public string|Missing|null $kind = Missing::Value;
    public string|Missing|null $name = Missing::Value;
    public bool|Missing|null $semanticsImplemented = Missing::Value;
    public bool|Missing|null $semanticsVerified = Missing::Value;
    public string|Missing|null $status = Missing::Value;
    public bool|Missing|null $surfaceRegistered = Missing::Value;
    public bool|Missing|null $wireSchemaGenerated = Missing::Value;
    public string|Missing|null $notes = Missing::Value;
    public array|Missing|null $tests = Missing::Value;
}
final class ProtocolError extends Model {
    protected const REQUIRED = ['code', 'message'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['code' => null, 'message' => null, 'data' => null];
    public int|Missing|null $code = Missing::Value;
    public string|Missing|null $message = Missing::Value;
    public mixed $data = Missing::Value;
}
final class Proxy extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['server' => null, 'username' => null, 'password' => null];
    public string|Missing|null $password = Missing::Value;
    public string|Missing|null $server = Missing::Value;
    public string|Missing|null $username = Missing::Value;
}
final class RealmDiagnostics extends Model {
    protected const REQUIRED = ['realm', 'diagnostics'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['realm' => null, 'diagnostics' => Diagnostics::class];
    public Diagnostics|Missing|null $diagnostics = Missing::Value;
    public string|Missing|null $realm = Missing::Value;
}
final class ResetProfileOverridesParams extends Model {
    protected const REQUIRED = ['targetId'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['targetId' => null];
    public string|Missing|null $targetId = Missing::Value;
}
final class ResetProfileOverridesResult extends Model {
    protected const REQUIRED = ['profile'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => EnvironmentProfile::class];
    public EnvironmentProfile|Missing|null $profile = Missing::Value;
}
final class ResourceBudgets extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['maxRequests' => null, 'maxConcurrent' => null, 'maxWireBytes' => null, 'maxBodyBytes' => null, 'maxResponseBytes' => null, 'maxDecodedBytes' => null, 'maxRetainedBytes' => null];
    public int|Missing|null $maxBodyBytes = Missing::Value;
    public int|Missing|null $maxConcurrent = Missing::Value;
    public int|Missing|null $maxDecodedBytes = Missing::Value;
    public int|Missing|null $maxRequests = Missing::Value;
    public int|Missing|null $maxResponseBytes = Missing::Value;
    public int|Missing|null $maxRetainedBytes = Missing::Value;
    public int|Missing|null $maxWireBytes = Missing::Value;
}
final class ResourceMatch extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['kinds' => ['array', null], 'hosts' => ['array', null], 'origins' => ['array', null], 'urlGlob' => null, 'owners' => ['array', null], 'mechanisms' => ['array', null], 'topLevelSite' => null];
    public array|Missing|null $hosts = Missing::Value;
    public array|Missing|null $kinds = Missing::Value;
    public array|Missing|null $mechanisms = Missing::Value;
    public array|Missing|null $origins = Missing::Value;
    public array|Missing|null $owners = Missing::Value;
    public string|Missing|null $topLevelSite = Missing::Value;
    public string|Missing|null $urlGlob = Missing::Value;
}
final class ResourcePolicy extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['reportOnly' => null, 'presets' => ['array', null], 'rules' => ['array', ResourceRule::class], 'budgets' => ResourceBudgets::class];
    public ResourceBudgets|Missing|null $budgets = Missing::Value;
    public array|Missing|null $presets = Missing::Value;
    public bool|Missing|null $reportOnly = Missing::Value;
    public array|Missing|null $rules = Missing::Value;
}
final class ResourcePolicyStats extends Model {
    protected const REQUIRED = ['generation', 'requests', 'networkAcquisitions', 'cacheHits', 'blocked', 'headerOnly', 'prefixes', 'wireBytesKnown', 'encodedNetworkBodyBytes', 'bodyBytesConsumed', 'retainedBodyBytes', 'decodedPixelWorkBytes', 'knownAvoidedBodyReadBytes', 'unknownAvoidedBodyRequests', 'wouldBlock', 'wouldBypassCache', 'budgetDenied', 'byRule'];
    protected const MAP_FIELDS = ['byRule'];
    protected const TYPES = ['generation' => null, 'requests' => null, 'networkAcquisitions' => null, 'cacheHits' => null, 'blocked' => null, 'headerOnly' => null, 'prefixes' => null, 'wireBytesKnown' => null, 'encodedNetworkBodyBytes' => null, 'bodyBytesConsumed' => null, 'retainedBodyBytes' => null, 'decodedPixelWorkBytes' => null, 'knownAvoidedBodyReadBytes' => null, 'unknownAvoidedBodyRequests' => null, 'wouldBlock' => null, 'wouldBypassCache' => null, 'budgetDenied' => null, 'byRule' => ['map', null]];
    public int|Missing|null $blocked = Missing::Value;
    public int|Missing|null $bodyBytesConsumed = Missing::Value;
    public int|Missing|null $budgetDenied = Missing::Value;
    public array|Missing|null $byRule = Missing::Value;
    public int|Missing|null $cacheHits = Missing::Value;
    public int|Missing|null $decodedPixelWorkBytes = Missing::Value;
    public int|Missing|null $encodedNetworkBodyBytes = Missing::Value;
    public int|Missing|null $generation = Missing::Value;
    public int|Missing|null $headerOnly = Missing::Value;
    public int|Missing|null $knownAvoidedBodyReadBytes = Missing::Value;
    public int|Missing|null $networkAcquisitions = Missing::Value;
    public int|Missing|null $prefixes = Missing::Value;
    public int|Missing|null $requests = Missing::Value;
    public int|Missing|null $retainedBodyBytes = Missing::Value;
    public int|Missing|null $unknownAvoidedBodyRequests = Missing::Value;
    public int|Missing|null $wireBytesKnown = Missing::Value;
    public int|Missing|null $wouldBlock = Missing::Value;
    public int|Missing|null $wouldBypassCache = Missing::Value;
}
final class ResourceRule extends Model {
    protected const REQUIRED = ['id'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['id' => null, 'match' => ResourceMatch::class, 'work' => ResourceWork::class];
    public string|Missing|null $id = Missing::Value;
    public ResourceMatch|Missing|null $match = Missing::Value;
    public ResourceWork|Missing|null $work = Missing::Value;
}
final class ResourceWork extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['cacheRead' => null, 'network' => null, 'body' => null, 'prefixBytes' => null, 'decode' => null, 'cacheRetain' => null, 'debugRetain' => null];
    public string|Missing|null $body = Missing::Value;
    public bool|Missing|null $cacheRead = Missing::Value;
    public bool|Missing|null $cacheRetain = Missing::Value;
    public bool|Missing|null $debugRetain = Missing::Value;
    public bool|Missing|null $decode = Missing::Value;
    public bool|Missing|null $network = Missing::Value;
    public int|Missing|null $prefixBytes = Missing::Value;
}
final class ResumeParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class ResumeResult extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class SetMediaProfileParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['seed' => null, 'camera' => MediaCameraRequest::class, 'microphone' => MediaMicrophoneRequest::class, 'devices' => ['array', MediaDeviceProfile::class], 'browserContextId' => null];
    public string|Missing|null $browserContextId = Missing::Value;
    public MediaCameraRequest|Missing|null $camera = Missing::Value;
    public array|Missing|null $devices = Missing::Value;
    public MediaMicrophoneRequest|Missing|null $microphone = Missing::Value;
    public string|Missing|null $seed = Missing::Value;
}
final class SetMediaProfileResult extends Model {
    protected const REQUIRED = ['profile', 'nativeModesVerified'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => MediaProfile::class, 'nativeModesVerified' => null];
    public bool|Missing|null $nativeModesVerified = Missing::Value;
    public MediaProfile|Missing|null $profile = Missing::Value;
}
final class SetViewportParams extends Model {
    protected const REQUIRED = ['width', 'height'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['width' => null, 'height' => null];
    public int|Missing|null $height = Missing::Value;
    public int|Missing|null $width = Missing::Value;
}
final class SetViewportResult extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class StartTraceParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class StartTraceResult extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class StopTraceParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class StopTraceResult extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = [];
}
final class TraceEvent extends Model {
    protected const REQUIRED = ['sequence', 'time', 'kind', 'name'];
    protected const MAP_FIELDS = ['data'];
    protected const TYPES = ['sequence' => null, 'time' => null, 'kind' => null, 'name' => null, 'data' => ['map', null]];
    public string|Missing|null $kind = Missing::Value;
    public string|Missing|null $name = Missing::Value;
    public int|Missing|null $sequence = Missing::Value;
    public string|Missing|null $time = Missing::Value;
    public array|Missing|null $data = Missing::Value;
}
final class UpdateProfileParams extends Model {
    protected const REQUIRED = ['targetId', 'patch'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['targetId' => null, 'patch' => ProfilePatch::class];
    public ProfilePatch|Missing|null $patch = Missing::Value;
    public string|Missing|null $targetId = Missing::Value;
}
final class UpdateProfileResult extends Model {
    protected const REQUIRED = ['profile'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => EnvironmentProfile::class];
    public EnvironmentProfile|Missing|null $profile = Missing::Value;
}
final class UpdateResourcePolicyParams extends Model {
    protected const REQUIRED = ['browserContextId', 'policy'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['browserContextId' => null, 'policy' => ResourcePolicy::class];
    public string|Missing|null $browserContextId = Missing::Value;
    public ResourcePolicy|Missing|null $policy = Missing::Value;
}
final class UpdateResourcePolicyResult extends Model {
    protected const REQUIRED = ['generation'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['generation' => null];
    public int|Missing|null $generation = Missing::Value;
}
final class ValidateMediaProfileParams extends Model {
    protected const REQUIRED = [];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['seed' => null, 'camera' => MediaCameraRequest::class, 'microphone' => MediaMicrophoneRequest::class, 'devices' => ['array', MediaDeviceProfile::class], 'browserContextId' => null];
    public string|Missing|null $browserContextId = Missing::Value;
    public MediaCameraRequest|Missing|null $camera = Missing::Value;
    public array|Missing|null $devices = Missing::Value;
    public MediaMicrophoneRequest|Missing|null $microphone = Missing::Value;
    public string|Missing|null $seed = Missing::Value;
}
final class ValidateMediaProfileResult extends Model {
    protected const REQUIRED = ['profile', 'nativeModesVerified'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['profile' => MediaProfile::class, 'nativeModesVerified' => null];
    public bool|Missing|null $nativeModesVerified = Missing::Value;
    public MediaProfile|Missing|null $profile = Missing::Value;
}
final class ValidateResourcePolicyParams extends Model {
    protected const REQUIRED = ['policy'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['policy' => ResourcePolicy::class];
    public ResourcePolicy|Missing|null $policy = Missing::Value;
}
final class ValidateResourcePolicyResult extends Model {
    protected const REQUIRED = ['policy'];
    protected const MAP_FIELDS = [];
    protected const TYPES = ['policy' => ResourcePolicy::class];
    public ResourcePolicy|Missing|null $policy = Missing::Value;
}
final class MimicCommands {
    public function __construct(private \Closure $sender) {}
    public function cancelExecution(CancelExecutionParams|array|null $params = null): CancelExecutionResult {
        return CancelExecutionResult::fromWire(($this->sender)("Mimic.cancelExecution", $params ?? new \stdClass()));
    }
    public function captureSnapshot(CaptureSnapshotParams|array|null $params = null): CaptureSnapshotResult {
        return CaptureSnapshotResult::fromWire(($this->sender)("Mimic.captureSnapshot", $params ?? new \stdClass()));
    }
    public function clearTrace(ClearTraceParams|array|null $params = null): ClearTraceResult {
        return ClearTraceResult::fromWire(($this->sender)("Mimic.clearTrace", $params ?? new \stdClass()));
    }
    public function configureContext(ConfigureContextParams|array $params): ConfigureContextResult {
        return ConfigureContextResult::fromWire(($this->sender)("Mimic.configureContext", $params ?? new \stdClass()));
    }
    public function createContext(CreateContextParams|array|null $params = null): CreateContextResult {
        return CreateContextResult::fromWire(($this->sender)("Mimic.createContext", $params ?? new \stdClass()));
    }
    public function exportProfile(ExportProfileParams|array $params): ExportProfileResult {
        return ExportProfileResult::fromWire(($this->sender)("Mimic.exportProfile", $params ?? new \stdClass()));
    }
    public function generateProfile(GenerateProfileParams|array|null $params = null): GenerateProfileResult {
        return GenerateProfileResult::fromWire(($this->sender)("Mimic.generateProfile", $params ?? new \stdClass()));
    }
    public function getCompatibilityMatrix(GetCompatibilityMatrixParams|array|null $params = null): GetCompatibilityMatrixResult {
        return GetCompatibilityMatrixResult::fromWire(($this->sender)("Mimic.getCompatibilityMatrix", $params ?? new \stdClass()));
    }
    public function getDiagnostics(GetDiagnosticsParams|array|null $params = null): GetDiagnosticsResult {
        return GetDiagnosticsResult::fromWire(($this->sender)("Mimic.getDiagnostics", $params ?? new \stdClass()));
    }
    public function getMediaPresets(GetMediaPresetsParams|array|null $params = null): GetMediaPresetsResult {
        return GetMediaPresetsResult::fromWire(($this->sender)("Mimic.getMediaPresets", $params ?? new \stdClass()));
    }
    public function getMediaProfile(GetMediaProfileParams|array|null $params = null): GetMediaProfileResult {
        return GetMediaProfileResult::fromWire(($this->sender)("Mimic.getMediaProfile", $params ?? new \stdClass()));
    }
    public function getMediaSources(GetMediaSourcesParams|array|null $params = null): GetMediaSourcesResult {
        return GetMediaSourcesResult::fromWire(($this->sender)("Mimic.getMediaSources", $params ?? new \stdClass()));
    }
    public function getProfile(GetProfileParams|array $params): GetProfileResult {
        return GetProfileResult::fromWire(($this->sender)("Mimic.getProfile", $params ?? new \stdClass()));
    }
    public function getProfileSchema(GetProfileSchemaParams|array|null $params = null): GetProfileSchemaResult {
        return GetProfileSchemaResult::fromWire(($this->sender)("Mimic.getProfileSchema", $params ?? new \stdClass()));
    }
    public function getResourcePolicy(GetResourcePolicyParams|array $params): GetResourcePolicyResult {
        return GetResourcePolicyResult::fromWire(($this->sender)("Mimic.getResourcePolicy", $params ?? new \stdClass()));
    }
    public function getResourcePolicySchema(GetResourcePolicySchemaParams|array|null $params = null): GetResourcePolicySchemaResult {
        return GetResourcePolicySchemaResult::fromWire(($this->sender)("Mimic.getResourcePolicySchema", $params ?? new \stdClass()));
    }
    public function getResourcePolicyStats(GetResourcePolicyStatsParams|array $params): GetResourcePolicyStatsResult {
        return GetResourcePolicyStatsResult::fromWire(($this->sender)("Mimic.getResourcePolicyStats", $params ?? new \stdClass()));
    }
    public function getStatus(GetStatusParams|array|null $params = null): GetStatusResult {
        return GetStatusResult::fromWire(($this->sender)("Mimic.getStatus", $params ?? new \stdClass()));
    }
    public function getTrace(GetTraceParams|array|null $params = null): GetTraceResult {
        return GetTraceResult::fromWire(($this->sender)("Mimic.getTrace", $params ?? new \stdClass()));
    }
    public function getVersion(GetVersionParams|array|null $params = null): GetVersionResult {
        return GetVersionResult::fromWire(($this->sender)("Mimic.getVersion", $params ?? new \stdClass()));
    }
    public function importProfile(ImportProfileParams|array $params): ImportProfileResult {
        return ImportProfileResult::fromWire(($this->sender)("Mimic.importProfile", $params ?? new \stdClass()));
    }
    public function pause(PauseParams|array|null $params = null): PauseResult {
        return PauseResult::fromWire(($this->sender)("Mimic.pause", $params ?? new \stdClass()));
    }
    public function resetProfileOverrides(ResetProfileOverridesParams|array $params): ResetProfileOverridesResult {
        return ResetProfileOverridesResult::fromWire(($this->sender)("Mimic.resetProfileOverrides", $params ?? new \stdClass()));
    }
    public function resume(ResumeParams|array|null $params = null): ResumeResult {
        return ResumeResult::fromWire(($this->sender)("Mimic.resume", $params ?? new \stdClass()));
    }
    public function setMediaProfile(SetMediaProfileParams|array $params): SetMediaProfileResult {
        return SetMediaProfileResult::fromWire(($this->sender)("Mimic.setMediaProfile", $params ?? new \stdClass()));
    }
    public function setViewport(SetViewportParams|array $params): SetViewportResult {
        return SetViewportResult::fromWire(($this->sender)("Mimic.setViewport", $params ?? new \stdClass()));
    }
    public function startTrace(StartTraceParams|array|null $params = null): StartTraceResult {
        return StartTraceResult::fromWire(($this->sender)("Mimic.startTrace", $params ?? new \stdClass()));
    }
    public function stopTrace(StopTraceParams|array|null $params = null): StopTraceResult {
        return StopTraceResult::fromWire(($this->sender)("Mimic.stopTrace", $params ?? new \stdClass()));
    }
    public function updateProfile(UpdateProfileParams|array $params): UpdateProfileResult {
        return UpdateProfileResult::fromWire(($this->sender)("Mimic.updateProfile", $params ?? new \stdClass()));
    }
    public function updateResourcePolicy(UpdateResourcePolicyParams|array $params): UpdateResourcePolicyResult {
        return UpdateResourcePolicyResult::fromWire(($this->sender)("Mimic.updateResourcePolicy", $params ?? new \stdClass()));
    }
    public function validateMediaProfile(ValidateMediaProfileParams|array $params): ValidateMediaProfileResult {
        return ValidateMediaProfileResult::fromWire(($this->sender)("Mimic.validateMediaProfile", $params ?? new \stdClass()));
    }
    public function validateResourcePolicy(ValidateResourcePolicyParams|array $params): ValidateResourcePolicyResult {
        return ValidateResourcePolicyResult::fromWire(($this->sender)("Mimic.validateResourcePolicy", $params ?? new \stdClass()));
    }
}
